// --------------------------------------------------------------------------------------------
// khtml javascript library
// --------------------------------------------------------------------------------------------
// (C) Copyright 2010-2011 by Bernhard Zwischenbrugger, Florian Hengartner, Stefan Kemper
//
// Project Info:  http://www.khtml.org
//				  http://www.khtml.org/iphonemap/help.php
//
// This library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with this library.  If not, see <http://www.gnu.org/licenses/>.
// --------------------------------------------------------------------------------------------
var khtml={};khtml.maplib={};khtml.maplib.base={};khtml.maplib.geometry={};khtml.maplib.overlay={};khtml.maplib.overlay.renderer={};khtml.maplib.parser={};khtml.maplib.ui={};khtml.maplib.util={};khtml.maplib.overlay.renderer={};khtml.maplib.version=function(){return"khtmlib_hsr v0.02"};khtml.maplib.Map=function(a){return new khtml.maplib.base.Map(a)};khtml.maplib.LatLng=function(a,c){return new khtml.maplib.geometry.LatLng(a,c)};khtml.maplib.standardimagepath="http://maplib.khtml.org/img/";khtml.maplib.base.helpers={};khtml.maplib.base.helpers.parseXml=function(a){var c;window.ActiveXObject?(c=new ActiveXObject("Microsoft.XMLDOM"),c.async=!1,c.loadXML(a)):document.implementation&&document.implementation.createDocument&&(c=(new DOMParser).parseFromString(a,"text/xml"));return c};
khtml.maplib.base.helpers.contains=function(a,c){var d=[a.sw().lat(),a.ne().lat()],e=[a.sw().lng(),a.ne().lng()];return(khtml.maplib.base.helpers.between(d,c.sw().lat())||khtml.maplib.base.helpers.between(d,c.ne().lat()))&&(khtml.maplib.base.helpers.between(e,c.sw().lng())||khtml.maplib.base.helpers.between(e,c.ne().lng()))?!0:!1};khtml.maplib.base.helpers.overlaps=function(a,c){return a.sw().lng()>c.ne().lng()||a.ne().lng()<c.sw().lng()||a.sw().lat()>c.ne().lat()||a.ne().lat()<c.sw().lat()?!1:!0};
khtml.maplib.base.helpers.overlapsBuggy=function(a,c){var d=[a.sw().lat(),a.ne().lat()],e=[a.sw().lng(),a.ne().lng()],g=[c.sw().lat(),c.ne().lat()],h=[c.sw().lng(),c.ne().lng()];return(khtml.maplib.base.helpers.between(d,c.sw().lat())||khtml.maplib.base.helpers.between(d,c.ne().lat()))&&(khtml.maplib.base.helpers.between(e,c.sw().lng())||khtml.maplib.base.helpers.between(e,c.ne().lng()))||(khtml.maplib.base.helpers.between(g,a.sw().lat())||khtml.maplib.base.helpers.between(g,a.ne().lat()))&&(khtml.maplib.base.helpers.between(h,
a.sw().lng())||khtml.maplib.base.helpers.between(h,a.ne().lng()))?!0:!1};
khtml.maplib.base.helpers.extendBBox=function(a,c){if(!(a instanceof khtml.maplib.geometry.Bounds)){var d=new khtml.maplib.geometry.LatLng(-90,-180),e=new khtml.maplib.geometry.LatLng(90,180);a=new khtml.maplib.geometry.Bounds(e,d)}if(!c)return a;c instanceof khtml.maplib.geometry.LatLng?a=khtml.maplib.base.helpers.extendBBoxByPoint(a,c):(a=khtml.maplib.base.helpers.extendBBoxByPoint(a,c.sw()),a=khtml.maplib.base.helpers.extendBBoxByPoint(a,c.ne()));return a};
khtml.maplib.base.helpers.extendBBoxByPoint=function(a,c){var d=a.sw().lng(),e=a.ne().lat(),g=a.sw().lat(),h=a.ne().lng();c.lat()>e&&(e=c.lat());c.lat()<g&&(g=c.lat());c.lng()<d&&(d=c.lng());c.lng()>h&&(h=c.lng());d=new khtml.maplib.geometry.LatLng(g,d);e=new khtml.maplib.geometry.LatLng(e,h);return new khtml.maplib.geometry.Bounds(d,e)};khtml.maplib.base.helpers.between=function(a,c){return a[0]<=c&&c<=a[1]?!0:!1};
khtml.maplib.base.helpers.cloneObject=function(a){var c={},d;for(d in a)c[d]=typeof a[d]=="object"?khtml.maplib.base.helpers.cloneObject(a[d]):a[d];return c};khtml.maplib.base.helpers.convertObjectToArray=function(a){for(var c=[],d=0,e=a.length;d<e;d++)c.push(a[d]);return c};
khtml.maplib.base.helpers.eventAttach=function(a,c,d,e,g){var h=arguments.length>5?$a(arguments).slice(5,arguments.length):[],b=function(b){h.unshift(b||window.event);return d.apply(e?e:a,h)};a.addEventListener?(navigator.appName.indexOf("Netscape")==-1&&c=="DOMMouseScroll"&&(c="mousewheel"),navigator.userAgent.indexOf("Safari")!=-1?c=="DOMMouseScroll"?a.onmousewheel=b:a.addEventListener(c,b,g):a.addEventListener(c,b,g)):(c=c=="DOMMouseScroll"?"onmousewheel":"on"+c,a.attachEvent(c,b));return{o:a,
type:c,fn:b,c:g}};khtml.maplib.base.helpers.eventRemove=function(a){a.o.removeEventListener&&a.o.removeEventListener(a.type,a.fn,a.c)};khtml.maplib.base.helpers.mixin=function(a,c,d){if(d)if(d instanceof Array)for(var e=0;e<d.length;e++)a[d[e]]=c[d[e]];else c[d]&&(a[d]=c[d]);else for(e in c)a[e]=c[e]};
khtml.maplib.base.helpers.showOnMap=function(a,c){var d=[];a instanceof khtml.maplib.geometry.Bounds&&(khtml.maplib.base.Log.log("Bounds"),khtml.maplib.base.Log.log("Northwest / Topleft",a.nw()),khtml.maplib.base.Log.log("Northeast / Topright",a.ne()),khtml.maplib.base.Log.log("Southeast / Bottomright",a.se()),khtml.maplib.base.Log.log("Southwest / Bottomleft",a.sw()),d.push(a.nw()),d.push(a.ne()),d.push(a.se()),d.push(a.sw()));for(var e=0;e<d.length;e++){var g=document.createElement("div");g.style.width=
"1px";g.style.height="1px";g.style.color="red";g.style["font-size"]="2em";g.textContent="X";g=new khtml.maplib.overlay.Marker(d[e],g);c.addOverlay(g)}};khtml.maplib.base.helpers.cancelEvent=function(a){a.cancelBubble=!0;a.stopPropagation&&a.stopPropagation()};khtml.maplib.base.helpers.stopEventPropagation=function(a){a.preventDefault?a.preventDefault():a.returnValue=!1};khtml.maplib.base.helpers.isIE=function(){return navigator.userAgent.indexOf("MSIE")!=-1};
khtml.maplib.base.helpers.isParentNodeEmpty=function(a){if(khtml.maplib.base.helpers.isIE())return a.parentNode.nodeValue==null;return!a.parentNode};
khtml.maplib.base.helpers.parseLine=function(a){if(a){if(typeof a=="string")a=khtml.maplib.base.helpers.parseLineString;if(typeof a=="object"){if(typeof a[0]=="string"&&typeof a[1]=="string"&&!isNaN(parseFloat(a[0]))&&!isNaN(parseFloat(a[1]))&&a.length==2){var c=parseFloat(a[1]),d=parseFloat(a[0]),e=khtml.maplib.LatLng(c,d);return e}if(typeof a[0]=="number"&&typeof a[0]=="number"&&a.length==2)a=new khtml.maplib.LatLng(a[0],a[1]);else for(e in a){var g=a[e];g instanceof khtml.maplib.geometry.LatLng||
(c=g[1],d=g[0],a[e]=typeof c=="number"&&typeof d=="number"&&g.length==2?new khtml.maplib.LatLng(c,d):khtml.maplib.base.helpers.parseLine(a[e]))}c=a}}else c=[];return c};khtml.maplib.base.helpers.parseLineString=function(a){if(typeof a=="string"){points=[];a=a.split(" ");for(var c=0;c<a.length;c++){var d=a[c].split(",");d.length==2&&(d[0]=parseFloat(d[0]),d[1]=parseFloat(d[1]),points.push(new khtml.maplib.LatLng(d[0],d[1])))}}return points};
khtml.maplib.base.helpers.parseMultiLine=function(a){if(a&&typeof a=="object")for(var c in a){var d=a[c],e;for(e in d){var g=d[e];if(!(g instanceof khtml.maplib.geometry.LatLng)){var h=g[0];g=g[1];typeof h=="number"&&typeof g=="number"&&(d[e]=new khtml.maplib.LatLng(h,g))}}}else a=[];return a};var stop=0;
khtml.maplib.base.helpers.stringify=function(a,c,d){var e=!0;typeof a.push=="undefined"&&(e=!1);for(var g="",h=c?c+1:c===!1?!1:1,b=g="",j=0;j<h-1;j++)b+="   ";c!==!1&&(b="\n"+b,g=b+"   ");j="";for(var f in a)if(f!="owner"&&typeof a[f]!="function")if(a[f]instanceof khtml.maplib.geometry.Bounds)j+=g+'"bbox":',j+="["+a[f].sw().lng()+","+a[f].sw().lat()+",",j+=""+a[f].ne().lng()+","+a[f].ne().lat()+"]",j+=",";else if(a[f]instanceof khtml.maplib.geometry.LatLng)a.type!="Marker"&&(a.type=="Point"&&(j+=
'"coordinates":'),j+="["+a[f].lng()+","+a[f].lat()+"],");else if(typeof a[f]=="string"){if((f=="type"||d)&&f!="animVal")a[f]!="Marker"&&(j+=g+'"'+f+'":"'+a[f]+'",')}else if(console.log(f,c),e||f=="type"||f=="features"||a[f]&&a[f].type=="Feature"||f=="geometry"||f=="coordinates"||f=="properties"||f=="bbox"||f=="className")console.log(f,c),j+=e?g+khtml.maplib.base.helpers.stringify(a[f],h)+",":f=="properties"?g+'"'+f+'":'+khtml.maplib.base.helpers.stringify(a[f],h)+",":g+'"'+f+'":'+khtml.maplib.base.helpers.stringify(a[f],
h,!0)+",";j=j.substring(0,j.length-1);return e?"["+j+"]":"{"+j+b+"}"};khtml.maplib.base.helpers.rotate=function(a,c){var d="rotate("+c+"deg)";a.style.webkitTransform=d;a.style.MozTransform=d;a.style.OTransform=d;if(document.all)rad=c*(Math.PI*2/360),costheta=Math.cos(rad),sintheta=Math.sin(rad),a.filters.item(0).M11=costheta,a.filters.item(0).M12=-sintheta,a.filters.item(0).M21=sintheta,a.filters.item(0).M22=costheta};
khtml.maplib.base.helpers.Boundingbox=function(a){this.map=a;this.div=document.createElement("div");this.div.style.border="1px dotted blue";this.div.style.position="absolute";this.div.style.strokeDasharray="4,4";this.div.style.zIndex=1;this.div.style.pointerEvents="none";a.mapParent.appendChild(this.div);this.show=function(a){this.div.style.display="";var c=this.map.latlngToXY(a.sw());a=this.map.latlngToXY(a.ne());this.div.style.top=a.y-parseInt(this.div.style.borderWidth)+"px";this.div.style.left=
c.x-parseInt(this.div.style.borderWidth)+"px";this.div.style.width=a.x-c.x+"px";this.div.style.height=-a.y+c.y+"px";this.div.zIndex=10};this.hide=function(){c.div.style.display="none"};var c=this;this.map.addCallbackFunction(c.hide)};khtml.maplib.base.helpers.ajaxload="data:image/gif;base64,R0lGODlhEAAQAPIAAP///wAAAMLCwkJCQgAAAGJiYoKCgpKSkiH/C05FVFNDQVBFMi4wAwEAAAAh/hpDcmVhdGVkIHdpdGggYWpheGxvYWQuaW5mbwAh+QQJCgAAACwAAAAAEAAQAAADMwi63P4wyklrE2MIOggZnAdOmGYJRbExwroUmcG2LmDEwnHQLVsYOd2mBzkYDAdKa+dIAAAh+QQJCgAAACwAAAAAEAAQAAADNAi63P5OjCEgG4QMu7DmikRxQlFUYDEZIGBMRVsaqHwctXXf7WEYB4Ag1xjihkMZsiUkKhIAIfkECQoAAAAsAAAAABAAEAAAAzYIujIjK8pByJDMlFYvBoVjHA70GU7xSUJhmKtwHPAKzLO9HMaoKwJZ7Rf8AYPDDzKpZBqfvwQAIfkECQoAAAAsAAAAABAAEAAAAzMIumIlK8oyhpHsnFZfhYumCYUhDAQxRIdhHBGqRoKw0R8DYlJd8z0fMDgsGo/IpHI5TAAAIfkECQoAAAAsAAAAABAAEAAAAzIIunInK0rnZBTwGPNMgQwmdsNgXGJUlIWEuR5oWUIpz8pAEAMe6TwfwyYsGo/IpFKSAAAh+QQJCgAAACwAAAAAEAAQAAADMwi6IMKQORfjdOe82p4wGccc4CEuQradylesojEMBgsUc2G7sDX3lQGBMLAJibufbSlKAAAh+QQJCgAAACwAAAAAEAAQAAADMgi63P7wCRHZnFVdmgHu2nFwlWCI3WGc3TSWhUFGxTAUkGCbtgENBMJAEJsxgMLWzpEAACH5BAkKAAAALAAAAAAQABAAAAMyCLrc/jDKSatlQtScKdceCAjDII7HcQ4EMTCpyrCuUBjCYRgHVtqlAiB1YhiCnlsRkAAAOwAAAAAAAAAAAA%3D%3D";
khtml.maplib.base.helpers.close="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAABGdBTUEAALGOfPtRkwAAACBjSFJNAAB6JQAAgIMAAPn/AACA6QAAdTAAAOpgAAA6mAAAF2+SX8VGAAAA5ElEQVR42tRTQYoEIQwsl/2Bl3gQoY9eBKEf5kvyG8G7h4Z+S38gIu5lp5lZ2R7YPm1BDhZJSFWiGmPgDj5wE7cbfD4/mBkAHprUj9yTTyn9OsGIMSLG+Fxwxc8SiAi9d4QQHskjhIDeO4jorQcq5wwiQmsN3nt479FaAxEh5zxJmyZIKalSClprL1FKQUpJXZr4DBH52xqZeRhjICKw1sJaCxGBMQbMPN41GFpriAicc6i1otYK5xxEBFrraQuThGVZAADbtp2amXms6woAOI7j0gO17/t5MN+HNfEvBf//M30NAKe7aRqUOIlfAAAAAElFTkSuQmCC";
khtml.maplib.base.helpers.imageNotSelectable=function(a){a.style.MozUserSelect="none";a.style.webkitUserSelect="none";a.style.webkitUserDrag="none";a.style.KhtmlUserSelect="none";a.style.OUserSelect="none";a.style.userSelect="none"};
khtml.maplib.base.helpers.setCursor=function(a,c){if(navigator.userAgent.indexOf("MSIE")!=-1)a.style.cursor=c=="grab"?"url('"+khtml.maplib.standardimagepath+"hand.cur'), default":c=="grabbing"?"url('"+khtml.maplib.standardimagepath+"fist.cur'), move":"pointer";else if(a.style.cursor="-moz-"+c,a.style.cursor!="-moz-"+c&&(a.style.cursor="-webkit-"+c,a.style.cursor!="-webkit-"+c&&(a.style.cursor="-ms-"+c,a.style.cursor!="-ms-"+c&&(a.style.cursor="-khtml-"+c,a.style.cursor!="-khtml-"+c&&(a.style.cursor=
c,a.style.cursor!=c)))))a.style.cursor="pointer"};khtml.maplib.base.Map=function(a){typeof a=="string"&&(a=document.getElementById(a));(typeof a!="object"||null==a)&&console.log("Error: map is null or not an object. (map: "+a+")");this.addOverlay=function(b){if(null==b||b instanceof Array)return console.log('Map.addOverlay(): Illegal argument (was "null" or "Array")'),!1;this.overlays.push(b);typeof b.init=="function"&&b.init(this);this.renderOverlay(b)};this.addOverlays=function(b){if(b instanceof Array)for(var j=0;j<b.length;j++)this.addOverlay(b[j]);
else this.addOverlay(b)};this.renderOverlay=function(b){try{b.render()}catch(j){}};this.renderOverlays=function(){this.overlayDiv.style.display="";for(obj in this.overlays)this.overlays[obj].render()};this._hideOverlays=function(){this.overlayDiv.style.display="none";for(obj in this.overlays)this.overlays[obj].hide&&this.overlays[obj].hide(g)};this.removeOverlays=function(){for(;this.overlays.length>0;)this.overlays.pop().clear()};this.stopRenderOverlays=function(){for(obj in this.overlays)typeof this.overlays[obj].cancel==
"function"&&this.overlays[obj].cancel()};this.removeOverlay=function(b){for(var j=0;j<this.overlays.length;j++)if(b==this.overlays[j]){b.clear();this.overlays.splice(j,1);break}};this.callbackFunctions=[];this.addCallbackFunction=function(b){typeof b=="function"&&this.callbackFunctions.push(b)};this._executeCallbackFunctions=function(){for(var b=0;b<this.callbackFunctions.length;b++)this.callbackFunctions[b].call(this)};this.myTimer=function(b){this.reset=function(){this._isRunning=!1};this.isTimeRunning=
function(){if(!1==this._isRunning)return!1;if(this.time+this.myInterval>(new Date).getTime())return!1;this._isRunning=!1;return!0};this.start=function(){this._isRunning=!0;this.time=(new Date).getTime()};this.interval=function(b){if(typeof b!="undefined")this.myInterval=parseInt(b);return this.myInterval};this.reset();this.interval(b);return this};this.oldMoveY=this.oldMoveX=0;this.moving=!1;this._start=function(b){b.preventDefault?b.preventDefault():b.returnValue=!1;this.moving=this.center();this.downEvent=
b;this.moveAnimationBlocked=!0;if(b.touches.length==1){this.startMoveX=this.moveX-this.pageX(b.touches[0])/this.faktor/this.sc;this.startMoveY=this.moveY-this.pageY(b.touches[0])/this.faktor/this.sc;if(this.mousedownTime!=null&&(new Date).getTime()-this.mousedownTime<this._doubleclickTime){var j=Math.ceil(0.01+this._getZoom()-this.intZoom);this._autoZoomIn(this.pageX(b.touches[0]),this.pageY(b.touches[0]),j)}this.mousedownTime=(new Date).getTime();clearTimeout(this.zoomOutInterval);this.zoomOutInterval=
window.setInterval(function(){},20)}if(b.touches.length==2){window.clearInterval(this.zoomOutInterval);this.moveok=!1;j=this.pageX(b.touches[0]);var a=this.pageY(b.touches[0]),c=this.pageX(b.touches[1]);b=this.pageY(b.touches[1]);this.startDistance=Math.sqrt(Math.pow(c-j,2)+Math.pow(b-a,2));this.startZZ=this.position.zoom;b=(a+b)/2/this.faktor/this.sc;this.startMoveX=this.moveX-(j+c)/2/this.faktor/this.sc;this.startMoveY=this.moveY-b}this.oldMoveX=this.moveX;this.oldMoveY=this.moveY};this.moveok=
!0;this._move=function(b){b.preventDefault?b.preventDefault():b.returnValue=!1;this.moveEvent=b;if(b.touches.length==1&&this.moveok){this.lastMoveX=this.moveX;this.lastMoveY=this.moveY;this.lastMoveTime=new Date(b.timeStamp);this.moveX=this.pageX(b.touches[0])/this.faktor/this.sc+this.startMoveX;this.moveY=this.pageY(b.touches[0])/this.faktor/this.sc+this.startMoveY;if(!this.zoomOutStarted){if(Math.abs(this.moveX-this.oldMoveX)>5||Math.abs(this.moveY-this.oldMoveY)>5)window.clearInterval(this.zoomOutInterval),
this.zoomOutSpeed=0.01,this.mousedownTime=null;var j=new khtml.maplib.LatLng(this.lat,this.lng);this.setCenter2(j,this.position.zoom);this.moveAnimationBlocked=!1}if(Math.abs(this.moveX-this.oldMoveX)>5||Math.abs(this.moveY-this.oldMoveY)>5)this.mousedownTime=null}if(b.touches.length==2){this.mousedownTime=null;var a=this.pageX(b.touches[0]),c=this.pageY(b.touches[0]),e=this.pageX(b.touches[1]),d=this.pageY(b.touches[1]);j=Math.sqrt(Math.pow(e-a,2)+Math.pow(d-c,2))/this.startDistance;b=this.startZZ+
j-1;b>this.tileSource.maxzoom?(b=this.tileSource.maxzoom,j=this.zoomDeltaOld):this.zoomDeltaOld=j;a=(a+e)/2;c=(c+d)/2;faktor=Math.pow(2,b);e=a/faktor-this.width/2;d=c/faktor-this.height/2;j=Math.pow(2,j-1);this.moveX=(a+(e-e*j))/faktor+this.startMoveX;this.moveY=(c+(d-d*j))/faktor+this.startMoveY;j=new khtml.maplib.LatLng(this.lat,this.lng);this.setCenter2(j,b)}};this._end=function(b){b.preventDefault?b.preventDefault():b.returnValue=!1;window.clearInterval(this.zoomOutInterval);this.zoomOutStarted=
!1;this.zoomOutSpeed=0.01;if(b.touches.length==0&&(this.moveok=!0,this.moveAnimationMobile&&this.moveAnimationBlocked==!1)){var a=new Date(b.timeStamp)-this.lastMoveTime,f=(this.lastMoveX-this.moveX)/a*4;a=(this.lastMoveY-this.moveY)/a*4;var c=this.wheelSpeedConfig.animateMaxSpeed;f>c&&(f=c);a>c&&(a=c);f<-c&&(f=-c);a<-c&&(a=-c);c=Math.pow(2,this.zoom());this._animateMove(f,a,c)}if(b.touches.length==1)this.startMoveX=this.moveX-b.touches[0].pageX/this.faktor/this.sc,this.startMoveY=this.moveY-b.touches[0].pageY/
this.faktor/this.sc};this.pageX=function(b){try{return(b.pageX===void 0?b.clientX+document.body.scrollLeft+document.documentElement.scrollLeft:b.pageX)-this.mapLeft}catch(a){return this.lastMouseX}};this.pageY=function(b){try{return(b.pageY===void 0?b.clientY+document.body.scrollTop+document.documentElement.scrollTop:b.pageY)-this.mapTop}catch(a){return this.lastMouseY}};this.doubleclickBlocked=!1;this._doubleclick=function(b){var a;if(!b)b=window.event;b.which?a=b.which==3:b.button&&(a=b.button==
2);a?this._discretZoom(-1,this.pageX(b),this.pageY(b)):this._discretZoom(1,this.pageX(b),this.pageY(b))};this._mousedown=function(b){this.mapParent.focus();b.preventDefault?b.preventDefault():window.event.returnValue=!1;this.downEvent=b;this.lastMouseX=this.pageX(b);this.lastMouseY=this.pageY(b);this.moveAnimationBlocked=!0;if(this.mousedownTime2!=null&&(new Date).getTime()-this.mousedownTime2<this._doubleclickTime2)this._doubleclick(b);else{this.mousedownTime2=(new Date).getTime();if(b.shiftKey){this.selectRectLeft=
this.pageX(b);this.selectRectTop=this.pageY(b);this.selectRect=document.createElement("div");this.selectRect.style.left=this.selectRectLeft+"px";this.selectRect.style.top=this.selectRectTop+"px";this.selectRect.style.border="1px solid gray";if(!this.internetExplorer)this.selectRect.style.opacity=0.5,this.selectRect.style.backgroundColor="white";this.selectRect.style.position="absolute";this.map.parentNode.appendChild(this.selectRect);khtml.maplib.base.helpers.setCursor(this.mapParent,"crosshair")}else this.moving=
this.center(),this.startMoveX=this.moveX-this.pageX(b)/this.faktor/this.sc,this.startMoveY=this.moveY-this.pageY(b)/this.faktor/this.sc,this.movestarted=!0,khtml.maplib.base.helpers.setCursor(this.mapParent,"grabbing");return!1}};this._mousemove=function(b){b.preventDefault?b.preventDefault():window.event.returnValue=!1;this.moveEvent=b;this.lastMouseX=this.pageX(b);this.lastMouseY=this.pageY(b);if(b.shiftKey){if(this.selectRect){this.selectRect.style.width=Math.abs(this.pageX(b)-this.selectRectLeft)+
"px";this.selectRect.style.height=Math.abs(this.pageY(b)-this.selectRectTop)+"px";if(this.pageX(b)<this.selectRectLeft)this.selectRect.style.left=this.pageX(b)+"px";if(this.pageY(b)<this.selectRectTop)this.selectRect.style.top=this.pageY(b)+"px"}}else if(this.movestarted)this.lastMoveX=this.moveX,this.lastMoveY=this.moveY,this.lastMoveTime=new Date(b.timeStamp),this.moveX=this.pageX(b)/this.faktor/this.sc+this.startMoveX,this.moveY=this.pageY(b)/this.faktor/this.sc+this.startMoveY,this.setCenter2(new khtml.maplib.LatLng(this.lat,
this.lng),this.position.zoom),this.moveAnimationBlocked=!1;return!1};this._mouseup=function(b){khtml.maplib.base.helpers.setCursor(this.mapParent,"grab");this.lastMouseX=this.pageX(b);this.lastMouseY=this.pageY(b);if(this.moveMarker)this.moveMarker=null;if(this.selectRect){var a=this.XYTolatlng(this.selectRect.offsetLeft,this.selectRect.offsetTop+this.selectRect.offsetHeight),f=this.XYTolatlng(this.selectRect.offsetLeft+this.selectRect.offsetWidth,this.selectRect.offsetTop);this._setBounds(new khtml.maplib.geometry.Bounds(a,
f));this.selectRect.parentNode.removeChild(this.selectRect);this.selectRect=null}a=new Date(b.timeStamp)-this.lastMoveTime;if(this.wheelSpeedConfig.moveAnimateDesktop&&a!=0&&this.movestarted&&this.moveAnimationBlocked==!1)b=(this.lastMoveX-this.moveX)/a,a=(this.lastMoveY-this.moveY)/a,f=this.wheelSpeedConfig.animateMaxSpeed,b>f&&(b=f),a>f&&(a=f),b<-f&&(b=-f),a<-f&&(a=-f),f=Math.pow(2,this.zoom()),this._animateMove(b,a,f);var c=this;setTimeout(function(){c.movestarted=!1},1)};this._mouseupIE=function(b){b.preventDefault?
b.preventDefault():b.returnValue=!1;this.lastMouseX=this.pageX(b);this.lastMouseY=this.pageY(b);this.setCenter2(this.XYTolatlng(this.lastMouseX,this.lastMouseY),this.zoom())};this.startZoomTime=null;this._mousewheel=function(b){b.preventDefault?b.preventDefault():b.returnValue=!1;this.mapParent.focus();if(!b)b=window.event;if(b.wheelDelta)var a=b.wheelDelta/60;else if(b.detail)a=-b.detail/3,this.lastWheelDelta*a<0&&(this.wheelSpeedConfig.digizoom||(a=0)),this.lastWheelDelta=-b.detail/3;a=a<0?-1:1;
if(this.wheelSpeedConfig.digizoom)this._discretZoom(a,this.pageX(b),this.pageY(b));else{if(!this.startZoomTime)this.startZoomTime=new Date,this.startZoomTime2=new Date,this.oldZoom=this.zoom(),this.speed=1;var f=new Date-this.startZoomTime,c=new Date-this.startZoomTime2;this.startZoomTime=new Date;if(f>300)this.startZoomTime2=new Date,this.oldZoom=this.zoom(),this.speed=1,c=0.1;this.speed*=2;if(this.speed>5)this.speed=5;a=this.oldZoom+c/3E3*this.speed*a*(b.shiftKey?0.1:1);if(a>this.position.maxZoom)a=
this.position.maxZoom;if(a<this.position.minZoom)a=this.position.minZoom;this.centerAndZoomXY(this.center(),a,this.pageX(b),this.pageY(b))}};this._shiftkeydown=function(b){b.shiftKey&&khtml.maplib.base.helpers.setCursor(this.mapParent,"crosshair")};this._shiftkeyup=function(){khtml.maplib.base.helpers.setCursor(this.mapParent,"grab")};this.zoomTimeouts=[];this.discretZoomBlocked=!1;this._discretZoom=function(b,a,f){if(!this.discretZoomBlocked){var c=this;this.discretZoomBlockedTimeout=setTimeout(function(){c.discretZoomBlocked=
!1},200);this.discretZoomBlocked=!0;for(var e=1;e<=20;e++)this.zoomTimeouts[e]&&clearTimeout(this.zoomTimeouts[e]);e=this.zoom();var d=b==1?Math.ceil(this.zoom()+0.9):Math.floor(this.zoom()-0.9);d=Math.abs(e-d);var g=0;for(e=1;e<=20;e++){var h=b*Math.sin(e/20*Math.PI/2)*d;this.zoomTimeouts[e]=this._discretZoomExec(a,f,h-g,e,20);g=h}}};this._discretZoomExec=function(b,a,f,c,e){var d=this;return setTimeout(function(){var g=d.zoom()+f;c==e&&(g=Math.round(g));d.centerAndZoomXY(d.center(),g,b,a)},c*20)};
this.digizoomblocked=!1;this.wheelZoomTimeout=this.digizoomblockedTimeout=null;this._animateMove=function(b,a,f){if(!this.internetExplorer){clearTimeout(this.animateMoveTimeout);if(Math.abs(b)<this.wheelSpeedConfig.animateMinSpeed/f&&Math.abs(a)<this.wheelSpeedConfig.animateMinSpeed/f)this.moving=!1;else{this.moveX+=-b;this.moveY+=-a;var c=this,e=Math.sqrt(Math.pow(b,2)+Math.pow(a,2)),d=b/e,g=a/e;this.animateMoveTimeout=window.setTimeout(function(){c._animateMove(b-d*c.wheelSpeedConfig.moveAnimationSlowdown/
f,a-g*c.wheelSpeedConfig.moveAnimationSlowdown/f,f)},20)}this.setCenter2(this.position.center,this.position.zoom)}};this.autoZoomStartTime=this.autoZoomInTimeout=null;this._autoZoomIn=function(b,a,f){this.autoZoomInTimeout&&window.clearTimeout(this.autoZoomInTimeout);var c=0.2;f<0&&(c=-c);zoomGap=!1;Math.abs(f)<=Math.abs(c)&&(zoomGap=!0);var e=this.position.zoom+c;e=Math.round(e*1E3)/1E3;zoomGap&&(e=f<0?Math.floor(e):Math.ceil(e-0.2),c=e-this.position.zoom);faktor=Math.pow(2,e);var d=b-this.mapLeft-
this.width/2,g=a-this.mapTop-this.height/2,h=Math.pow(2,c);d-=d*h;g-=g*h;var x=this;h=(new Date).getMilliseconds();var m=this.autoZoomStartTime?h-this.autoZoomStartTime:0;this.autoZoomStartTime=h;if(m<100||zoomGap){e>=this.tileSource.minzoom&&e<=this.tileSource.maxzoom&&(this.moveX+=d/faktor,this.moveY+=g/faktor);var l=new khtml.maplib.LatLng(this.lat,this.lng);if(e>this.tileSource.maxzoom)e=this.tileSource.maxzoom;if(e<this.tileSource.minzoom)e=this.tileSource.minzoom;setTimeout(function(){x.setCenter2(l,
e)},1)}var o=f-c;zoomGap?this.digizoomblocked=!1:this.autoZoomInTimeout=window.setTimeout(function(){x._autoZoomIn(b,a,o)},40)};this.centerAndZoomXY=function(b,a,c,e){faktor=Math.pow(2,a);b=c-this.size.width/2;e-=this.size.height/2;c=a-this.zoom();c=Math.pow(2,c);b-=b*c;e-=e*c;a>=this.tileSource.minzoom&&a<=this.tileSource.maxzoom&&(this.moveX+=b/faktor,this.moveY+=e/faktor);b=new khtml.maplib.LatLng(this.lat,this.lng);if(a>this.tileSource.maxzoom)a=this.tileSource.maxzoom;if(a<this.tileSource.minzoom)a=
this.tileSource.minzoom;this.setCenter2(b,a)};this.centerAndZoom=function(b,a){this.moveY=this.moveX=0;if(a>this.tileSource.maxzoom)a=this.tileSource.maxzoom;if(a<this.tileSource.minzoom)a=this.tileSource.minzoom;this.record();this.setCenterNoLog(b,a)};this.render=function(){this.center(this.center())};this._setCenter3=function(b,a){this.moveY=this.moveX=0;this.setCenterNoLog(b,a)};this.setCenter2=function(b,a){this.record();this.setCenterNoLog(b,a)};this.setCenterNoLog=function(b,a){this.position.center=
b;this.lat=b.lat();this.lng=b.lng();a=parseFloat(a);if(a>this.tileSource.maxzoom)a=this.tileSource.maxzoom;if(a<this.tileSource.minzoom)a=this.tileSource.minzoom;this.position.center=b;this.position.zoom=a;this.layer(this.map,this.lat,this.lng,this.moveX,this.moveY,a);this._executeCallbackFunctions();this._getBounds()};this.center=function(b){typeof b!="undefined"&&this.centerAndZoom(b,this._getZoom());if(this.moveX!=0||this.moveY!=0)return b=new khtml.maplib.LatLng(this.movedLat,this.movedLng);return this.position.center};
this.zoom=function(b){typeof b!="undefined"&&this.centerAndZoom(this.position.center,b);return this.position.zoom};this.moveXY=function(b,a){this.moveX=parseFloat(b)/this.faktor/this.sc+this.moveDelayedX;this.moveY=parseFloat(a)/this.faktor/this.sc+this.moveDelayedY;this.setCenter2(this.center(),this.zoom())};this.tiles=function(b){this.clearMap();this.tileSource=b};this.tileOverlays=[];this.addTilesOverlay=function(b){this.tileOverlays.push(b);b=this.tileOverlays[this.tileOverlays.length-1];this.clearMap();
return b};this.removeTilesOverlay=function(b){for(var a=0;a<this.tileOverlays.length;a++)if(b==this.tileOverlays[a]){this.tileOverlays.splice(a,1);break}this.clearMap()};this._getCenter=function(){if(this.moveX&&this.moveX!=0||this.moveY&&this.moveY!=0)var b=new khtml.maplib.LatLng(this.movedLat,this.movedLng);else if(this.position.center)b=this.position.center;return b};this.bounds=function(b){if(typeof b!="undefined")this._setBounds(b);else return this.mapBounds};this.mapBounds=null;this._getBounds=
function(){var b=this.XYTolatlng(0,this.height),a=this.XYTolatlng(this.width,0);this.mapBounds=new khtml.maplib.geometry.Bounds(b,a)};this._setBounds=function(b){if(typeof khtml.maplib.geometry.Bounds=="undefined"||!(b instanceof khtml.maplib.geometry.Bounds))return!1;var a=b.sw();b=b.ne();var c=a.lat(),g=b.lat();a=a.lng();b=b.lng();c=d(c);var h=d(g);g=(a+b)/2;var i=e((c+h)/2);g=new khtml.maplib.LatLng(i,g);c=Math.abs(h-c);a=Math.abs(b-a);a/this.width>c/this.height?b=this.width:(a=c,b=this.height);
a=Math.log(360/a/(512/b))/Math.log(2)+1;if(a>this.tileSource.maxzoom)a=this.tileSource.maxzoom;if(a<this.tileSource.minzoom)a=this.tileSource.minzoom;this.position.center?this.wheelSpeedConfig.rectShiftAnimate?this.animatedGoto(g,a,this.wheelSpeedConfig.rectShiftAnimationTime):this.centerAndZoom(g,a):this.centerAndZoom(g,a)};this.animatedGotoStep=null;this.animatedGotoTimeout=[];this.animatedGoto=function(b,a,c){c/=10;var e=this._getCenter(),d=b.lat();b=b.lng();var g=e.lat(),h=e.lng(),n=this._getZoom(),
x=(d-g)/c,m=(b-h)/c,l=(a-n)/c,o=this.moveX/c,B=this.moveY/c,C=this.moveX,p=this.moveY;this.animatedGotoStep=0;for(var r=this;timeout=this.animatedGotoTimeout.pop();)clearTimeout(timeout);for(a=0;a<=c;a++)this.animatedGotoTimeout[a]=window.setTimeout(function(){r._animatedGotoExec(g,h,n,x,m,l,C,p,o,B)},10*a)};this._animatedGotoExec=function(b,a,c,e,d,g,h,n,x,m){this.moveX=-x;this.moveY=-m;b+=e*this.animatedGotoStep;a+=d*this.animatedGotoStep;c+=g*this.animatedGotoStep;this.animatedGotoStep++;this.centerAndZoom(new khtml.maplib.LatLng(b,
a),c)};this._getZoom=function(){return this.position.zoom};this._getIntZoom=function(){return this.intZoom};this.latlngToXY=function(b){var a=b.lat();b=b.lng();a>90&&(a-=180);a<-90&&(a+=180);var e=this._getIntZoom();b=c(a,b,e);a=this._getCenter();a=c(a.lat(),a.lng(),e);e=(a[0]-b[0])*this.tileW*this.sc-this.width/2;a=(a[1]-b[1])*this.tileW*this.sc-this.height/2;b=[];b.x=-e;b.y=-a;return b};this.XYTolatlng=function(b,a){var f=this._getCenter();if(f){var d=Math.pow(2,this.intZoom),g=f.lat();f=f.lng();
f=c(g,f,this.intZoom);g=(f[0]+(b-this.width/2)/this.tileW/this.sc)/d*360-180;d=-e((f[1]+(a-this.height/2)/this.tileH/this.sc)/d*360-180)+0;return new khtml.maplib.LatLng(d,g)}};this.mouseToLatLng=function(b){var a=this.pageX(b);b=this.pageY(b);return this.XYTolatlng(a,b)};this.reSize=function(){var b=this;window.setTimeout(function(){b._getSize(b)},1050)};this._getSize=function(){this.width=this.map.parentNode.offsetWidth;this.height=this.map.parentNode.offsetHeight;var b=this.map,a=0,c=0;do a+=b.offsetLeft,
c+=b.offsetTop,b=b.offsetParent;while(b.offsetParent);this.mapTop=c;this.mapLeft=a};this.recordArray=[];this.record=function(){var b=this._getCenter();if(b){var a=b.lat();b=b.lng();var c=this._getZoom();this.recordArray.push([a,b,c])}};this.play=function(b){if(!(b<1)&&!(b>this.recordArray.length-1)){b=this.recordArray[b];var a=new khtml.maplib.LatLng(b[0],b[1]);this.moveY=this.moveX=0;this._setCenter3(a,b[2])}};this.layerDrawLastFrame=null;this.doTheOverlays=!0;this.finalDraw=!1;this.moveDelayedY=
this.moveDelayedX=this.layerOldZoom=0;this.layerTimer=new this.myTimer(300);this.layer=function(b,a,c,e,d,g){this.stopRenderOverlays();g||(g=this._getZoom());var h=this.wheelSpeedConfig.digizoom?Math.floor(g):Math.round(g);this.layerDrawLastFrame&&window.clearTimeout(this.layerDrawLastFrame);if(this.layerTimer.isTimeRunning()||this.finalDraw==!1){var n=this;h=function(){n.finalDraw=!0;n.layer(b,a,c,e,d,g)};this.visibleZoom=parseInt(this.visibleZoom);this.visibleZoom=parseInt(this.visibleZoom);if(!n.finalDraw)this.layerDrawLastFrame=
window.setTimeout(h,100);if(this.layerTimer.isTimeRunning()){this.moveDelayedX=e;this.moveDelayedY=d;return}}this.layerTimer.start();for(h=this.moveDelayedY=this.moveDelayedX=0;h<22;h++)if(this.layers[h])this.layers[h].layerDiv.style.visibility="hidden";h=this.wheelSpeedConfig.digizoom?Math.floor(g):Math.round(g);if(this.layerOldZoom>g&&!this.finalDraw&&this.layers[h]&&!this.layers[h].loadComplete)this.visibleZoom=h+1;this.intZoom=h;if(h>this.tileSource.maxzoom)h=this.tileSource.maxzoom;if(!this.visibleZoom)this.oldIntZoom=
this.visibleZoom=h;this.faktor=Math.pow(2,h);this.sc=Math.pow(2,g-h);this.loadingZoomLevel=h;if(this.visibleZoom<h&&Math.abs(this.visibleZoom-h)<40)this.loadingZoomLevel=parseInt(this.visibleZoom)+1;this.draw(this.map,a,c,e,d,this.loadingZoomLevel,g,this.tileSource.src);this.layers[this.loadingZoomLevel].layerDiv.style.visibility="";if(h!=this.visibleZoom)this.visibleZoom<h+2?(this.draw(this.map,a,c,e,d,this.visibleZoom,g,this.tileSource.src),this.layers[this.visibleZoom].layerDiv.style.visibility=
""):this.layers[this.visibleZoom].layerDiv.style.visibility="hidden";if(h==this.visibleZoom)this.draw(this.map,a,c,e,d,this.visibleZoom-1,g,this.tileSource.src),this.layers[this.visibleZoom-1].layerDiv.style.visibility="hidden";if(this.layers[this.loadingZoomLevel].loadComplete&&this.visibleLayer!=h)this.layers[this.loadingZoomLevel].loadComplete=!1,this._hideLayer(this.visibleZoom),this.visibleZoom=this.loadingZoomLevel;this.quadtreeTimeout&&clearTimeout(this.quadtreeTimeout);if(this.loadingZoomLevel!=
h)n=this,this.quadtreeTimeout=window.setTimeout(function(){n.layer(b,a,c,e,d)},200);this.oldIntZoom!=this.intZoom&&this.oldIntZoom!=this.visibleZoom&&this._hideLayer(this.oldIntZoom);this.oldIntZoom=h;this.delayedOverlay&&window.clearTimeout(this.delayedOverlay);this.doTheOverlays||this.finalDraw||this.layerOldZoom==this.zoom()?(h=new Date,this.lastDX=this.moveX,this.lastDY=this.moveY,this.renderOverlays(),this.layerOldZoom=this.zoom(),this.doTheOverlays=new Date-h>10&&!this.finalDraw?!1:!0):this._hideOverlays();
n=this;this.layerBlockTimeout&&clearTimeout(this.layerBlockTimeout);this.layerBlockTimeout=window.setTimeout(function(){n.layerTimer.reset()},20);this.finalDraw=!1};this.draw=function(b,a,f,g,h,i,t,n){this.framesCounter++;var x=this;window.setTimeout(function(){x.framesCounter--},1E3);var m=Math.pow(2,i);if(this.layers[i])l=this.layers[i].layerDiv,o=d(a)-this.layers[i].startLat,f-=this.layers[i].startLng;else{o=c(a,f,i);this.layers[i]=[];this.layers[i].startTileX=o[0];this.layers[i].startTileY=o[1];
this.layers[i].startLat=d(a);this.layers[i].startLng=f;this.layers[i].images={};var l=document.createElement("div");l.setAttribute("zoomlevel",i);l.style.position="absolute";o=b.childNodes;b=!1;for(f=o.length-1;f>=0;f--)a=o.item(f),a.getAttribute("zoomlevel")<i&&(this.map.insertBefore(l,a),b=!0);b||this.map.appendChild(l);this.layers[i].layerDiv=l;var o=0;f=0}l.style.visibility="hidden";l.style.opacity=1;l.style.filter="alpha(opacity=100)";this.movedLng=(this.layers[i].startTileX/m-g/this.tileW)*
360-180+f;this.movedLat=-e((this.layers[i].startTileY/m-h/this.tileH)*360-180-o);o=c(this.movedLat,this.movedLng,i);g=o[0];f=o[1];h=Math.floor(g);b=Math.floor(f);a=this.layers[i].startTileX;var B=this.layers[i].startTileY;g=g-a-(-a+Math.floor(a));var C=f-B-(-B+Math.floor(B)),p;for(p in this.layers[i].images)this.layers[i].images[p].visibility=!1;f=this.width;var r=this.height;u=Math.pow(2,t-i);minX=Math.floor(-f/2/u/this.tileW+g);maxX=Math.ceil(f/2/u/this.tileW+g);minY=Math.floor(-r/2/u/this.tileH+
C);maxY=Math.ceil(r/2/u/this.tileH+C);for(f=minX;f<maxX;f++)for(r=minY;r<maxY;r++){var q=Math.floor(a+f),k=Math.floor(B+r),v=q%m,s=k;v<0&&(v+=m);if(!(s<0)&&!(s>=m)){var y=n(v,s,i);q=y+"-"+q+"-"+k;minsc=this.wheelSpeedConfig.digizoom?1:0.5;if(this.layers[i].images[q]==null&&u>=minsc){k=document.createElement("img");k.style.visibility="hidden";k.style.position="absolute";k.style.padding="0px";k.style.margin="0px";k.style.borderWidth="0px";k.style.left=f*this.tileW+"px";k.style.top=r*this.tileH+"px";
k.style.width=this.tileW+"px";k.style.height=this.tileH+"px";if(this.tileSource.opacity)k.style.opacity=this.tileSource.opacity;l.childNodes.length>0?l.insertBefore(k,l.childNodes.item(0)):l.appendChild(k);this.layers[i].images[q]={};this.layers[i].images[q].img=k;this.layers[i].images[q].array=[];this.layers[i].images[q].array.push(k);this.layers[i].loadComplete=!1;for(ov in this.tileOverlays){var z=this.tileOverlays[ov],w=k.cloneNode(!0);z=z.src(v,s,i);w.setAttribute("overlay",ov);khtml.maplib.base.helpers.eventAttach(w,
"load",this._imgLoaded,this,!1);l.appendChild(w);w.setAttribute("src",z);this.layers[i].images[q].array.push(w)}khtml.maplib.base.helpers.eventAttach(k,"load",this._imgLoaded,this,!1);khtml.maplib.base.helpers.eventAttach(k,"error",this._imgError,this,!1);k.setAttribute("src",y)}if(!this.css3d&&this.layers[i].images[q]){v=this.layers[i].images[q].array;for(s=0;s<v.length;s++){var D=o[0]-h+Math.floor(g);w=o[1]-b+Math.floor(C);var E=Math.round(this.tileW*u);z=Math.round(this.tileH*u);y=Math.floor(-D*
E+f*E);k=Math.floor(-w*z+r*z);D=Math.floor(-D*E+(f+1)*E);w=Math.floor(-w*z+(r+1)*z);v[s].style.left=y+"px";v[s].style.top=k+"px";v[s].style.height=D-y+"px";v[s].style.width=w-k+"px"}}this.layers[i].images[q]&&(this.layers[i].images[q].visibility=!0)}}for(p in this.layers[i].images)if(this.layers[i].images[p].visibility){if(this.layers[i].images[p].array[0].getAttribute("loaded")=="yes"){n=this.layers[i].images[p].array;for(m=0;m<n.length;m++)if(n[m].getAttribute("loaded")=="yes")n[m].style.visibility=
""}}else{n=this.layers[i].images[p].array;for(m=0;m<n.length;m++)this.layers[i].images[p].array[m].style.visibility="hidden",this.layers[i].images[p].array[m].getAttribute("loaded")!="yes"&&l.removeChild(this.layers[i].images[p].array[m]);delete this.layers[i].images[p].img;delete this.layers[i].images[p]}var u=Math.pow(2,t-i);y=-g*this.tileW;k=-C*this.tileH;if(this.css3d)l.style["-webkit-transform-origin"]=-1*y+"px "+-1*k+"px",l.style.webkitTransform="translate3d("+y+"px,"+k+"px,0px)  "+(" scale3d("+
u+","+u+",1) ");l.style.visibility="";l.style.opacity=1;l.style.filter="";l=t=0;for(p in this.layers[this.loadingZoomLevel].images)l++,k=this.layers[this.loadingZoomLevel].images[p].array[0],k.getAttribute("loaded")!="yes"&&t++;this.notLoadedImages=t;t<1&&(this.layers[this.loadingZoomLevel].loadComplete=!0);this.loadingZoomLevel==i&&this._imgLoadInfo(l,t)};this.fadeOutTimeout=null;this._fadeOut=function(a,c){this.fadeOutTimeout&&clearTimeout(this.fadeOutTimeout);if(c>0){a.style.opacity=c;a.style.filter=
"alpha( opacity="+c*100+" )";var e=this;this.fadeOutTimeout=setTimeout(function(){e._fadeOut(a,c-0.2)},40)}else a.style.visibility="hidden"};this._hideLayer=function(a){if(this.intZoom!=a&&this.layers[a])this.layers[a].layerDiv.style.opacity=1,this.layers[a].layerDiv.style.filter="alpha(opacity=100)",this._fadeOut(this.layers[a].layerDiv,1);if(this.layers[a])for(var c in this.layers[a].images)if(this.layers[a].images[c]&&this.layers[a].images[c].img&&this.layers[a].images[c].img.getAttribute("loaded")!=
"yes"&&a!=this.intZoom){for(var e=this.layers[a].images[c].array,d=0;d<e.length;d++)this.layers[a].layerDiv.removeChild(this.layers[a].images[c].array[d]);delete this.layers[a].images[c].img;delete this.layers[a].images[c]}};this._imgLoaded=function(a){a=a.target?a.target:a.srcElement;var c=!0;a.style.visibility="";a.setAttribute("loaded","yes");if(a.parentNode){for(var e=0,d=0,g=a.parentNode.getAttribute("zoomlevel"),h=0;h<a.parentNode.getElementsByTagName("img").length;h++){var t=a.parentNode.getElementsByTagName("img").item(h);
t.getAttribute("overlay")||(d++,t.getAttribute("loaded")!="yes"&&(e++,c=!1))}this.notLoadedImages=e;this.loadingZoomLevel==g&&this._imgLoadInfo(d,e);if((this.layers[g].loadComplete=c)&&this.loadingZoomLevel==g)this._hideLayer(this.visibleZoom),this._hideLayer(this.visibleZoom+1),this.visibleZoom=g}};this._imgError=function(a){var c=a.target?a.target:a.srcElement;c.parentNode&&(c.src!="http://khtml.org/notfound.png"&&c.setAttribute("src","http://khtml.org/notfound.png"),this._imgLoaded(a))};var c=
function(a,c,e){return[(c+180)/360*(1<<e),(1-Math.log(Math.tan(a*Math.PI/180)+1/Math.cos(a*Math.PI/180))/Math.PI)/2*(1<<e)]};this._calculateMapSize=function(){var a=this.mapParent.getBoundingClientRect();return{top:a.top-document.body.scrollTop,left:a.left-document.body.scrollLeft,width:a.width?a.width:a.right-a.left,height:a.height?a.height:a.bottom-a.top,deltaTop:a.top-document.body.scrollTop,deltaLeft:a.left-document.body.scrollLeft,deltaBottom:a.bottom,deltaRight:a.right}};this.redraw=function(){this._setMapPosition()};
this._setMapPosition=function(){this.size=this._calculateMapSize();var a=this.mapParent;a.currentStyle||window.getComputedStyle&&document.defaultView.getComputedStyle(a,null);this.mapTop=this.size.top;this.mapLeft=this.size.left;this.width=this.size.width;this.height=this.size.height;relativetop=this.size.deltaTop;relativeleft=this.size.deltaLeft;this.clone.style.top="0px";this.clone.style.left="0px";this.clone.style.width="100%";this.clone.style.height="100%";this.clone.style.position="relative";
this.clone.style.overflow="hidden";this.map.style.left="50%";this.map.style.top="50%";this._getCenter()&&this._getZoom()&&this.centerAndZoom(this._getCenter(),this._getZoom());this._copyright()};this.clearMap=function(){if(this.map){for(;this.map.firstChild;)this.map.removeChild(this.map.firstChild);for(;this.layers.length>0;)this.layers.pop();this.redraw()}};var d=function(a){return 180/Math.PI*Math.log(Math.tan(Math.PI/4+a*(Math.PI/180)/2))},e=function(a){return 180/Math.PI*(2*Math.atan(Math.exp(a*
Math.PI/180))-Math.PI/2)};this._imgLoadInfo=function(a,c){if(!this.loadInfoDiv)this.loadInfoDiv=document.createElement("div"),this.loadInfoDiv.style.position="absolute",this.loadInfoDiv.style.top="0px",this.loadInfoDiv.style.right="0px",this.loadInfoDiv.style.backgroundColor="white",this.loadInfoDiv.style.border="1px solid gray",this.loadInfoDiv.style.fontSize="10px",this.map.parentNode.appendChild(this.loadInfoDiv);if(c==0)this.loadInfoDiv.style.display="none";else{for(this.loadInfoDiv.style.display=
"";this.loadInfoDiv.firstChild;)this.loadInfoDiv.removeChild(this.loadInfoDiv.firstChild);this.loadInfoDiv.appendChild(document.createTextNode(c+" images to load"))}};this.copyrightdiv=null;this._copyright=function(){if(this.copyrightdiv==null)this.copyrightdiv=document.createElement("div"),this.overlayDiv.appendChild(this.copyrightdiv);for(;this.copyrightdiv.firstChild;)this.copyrightdiv.removeChild(this.copyrightdiv.firstChild);var a=document.createElement("img"),c=document.createElement("a");c.setAttribute("href",
"http://maplib.khtml.org");c.setAttribute("target","_blank");a.setAttribute("src","http://maplib.khtml.org/favicon.png");a.style.border="0px solid black";a.style.position="absolute";a.style.backgroundColor="transparent";a.style.margin="0px";a.style.padding="0px";var e=this.size.height-26;a.style.top=e+"px";a.style.left="3px";a.style.width="24px";a.style.height="24px";c.appendChild(a);this.copyrightdiv.appendChild(c);a=document.createElement("a");a.appendChild(document.createTextNode("openstreetmap"));
a.style.position="absolute";a.style.top=e+2+"px";a.style.left="28px";a.style.textDecoration="none";a.style.color="gray";a.setAttribute("href","http://www.openstreetmap.org/copyright");this.copyrightdiv.appendChild(a)};this.internetExplorer=!1;if(navigator.userAgent.indexOf("MSIE")!=-1)this.internetExplorer=!0;if(navigator.userAgent.indexOf("Android")!=-1){var g=this;setInterval(function(){g.layerTimer.reset()},300)}this.position={};this.tiles({maxzoom:18,minzoom:1,src:function(a,c,e){switch((a+c)%
3){case 0:var d="a";break;case 1:d="b";break;case 2:d="c";break;default:d="f"}return"http://"+d+".tile.openstreetmap.org/"+e+"/"+a+"/"+c+".png"},copyright:"osm"});this.wheelSpeedConfig=[];this.wheelSpeedConfig.acceleration=2;this.wheelSpeedConfig.maxSpeed=2;this.wheelSpeedConfig.animate=!1;navigator.userAgent.indexOf("AppleWebKit")!=-1&&(this.wheelSpeedConfig.animate=!0);navigator.userAgent.indexOf("Opera")!=-1&&(this.wheelSpeedConfig.animate=!1);this.wheelSpeedConfig.animate=!1;this.wheelSpeedConfig.digizoom=
!0;this.wheelSpeedConfig.zoomAnimationSlowdown=0.02;this.wheelSpeedConfig.animationFPS=50;this.wheelSpeedConfig.moveAnimateDesktop=!0;this.wheelSpeedConfig.rectShiftAnimate=!1;this.wheelSpeedConfig.rectShiftAnimationTime=500;this.wheelSpeedConfig.animateMinSpeed=0.4;this.wheelSpeedConfig.animateMaxSpeed=200;this.wheelSpeedConfig.moveAnimationSlowdown=0.4;this.framesCounter=this.wheelEventCounter=0;this.mapParent=a;khtml.maplib.base.helpers.setCursor(this.mapParent,"grab");this.clone=a.cloneNode(!0);
this.clone=document.createElement("div");this.clone.removeAttribute("id");a.firstChild?a.insertBefore(this.clone,a.firstChild):a.appendChild(this.clone);this.map=document.createElement("div");this.map.style.position="relative";this.clone.appendChild(this.map);this.overlayDiv=document.createElement("div");this.overlayDiv.style.position="absolute";this.clone.appendChild(this.overlayDiv);this._setMapPosition();this.overlays=[];if(khtml.maplib.overlay.GeoJson){var h=new khtml.maplib.overlay.GeoJson;this.addOverlay(h);
this.featureCollection=h.featureCollection}this.distanceMeasuring="no";this.measureLine=this.moveMarker=null;this.moveAnimationMobile=!0;this.moveAnimationBlocked=this.moveAnimationDesktop=!1;this.lastMouseX=this.width/2;this.lastMouseY=this.height/2;this.layers=[];this.intZoom=this.oldVisibleZoom=this.visibleZoom=null;this.lastMoveTime=this.lastMoveY=this.lastMoveX=this.moveY=this.moveX=0;this.zoomDeltaOld=1;this.startMoveY=this.startMoveX=0;this.sc=1;this.blocked=!1;this.tileH=this.tileW=256;this.position.zoom=
1;this.movestarted=!1;this.mousedownTime=null;this._doubleclickTime=400;this.mousedownTime2=null;this._doubleclickTime2=500;this.zoomOutTime=1E3;this.zoomOutSpeed=0.01;this.zoomOutInterval=null;this.zoomOutStarted=!1;this.zoomSpeedTimer=null;this.zoomAcceleration=1;this.css3d=!1;if(navigator.userAgent.indexOf("iPhone OS")!=-1)this.css3d=!0;if(navigator.userAgent.indexOf("iPad")!=-1)this.css3d=!1;if(navigator.userAgent.indexOf("Safari")!=-1)this.css3d=navigator.userAgent.indexOf("Mac")!=-1?!1:!0;if(navigator.userAgent.indexOf("iPhone OS")!=
-1)this.css3d=!0;if(navigator.userAgent.indexOf("Android")!=-1)this.css3d=!1;this.internetExplorer?(h=a,navigator.userAgent.indexOf("Windows Phone OS")!=-1&&khtml.maplib.base.helpers.eventAttach(h,"mouseup",this._mouseupIE,this,!1)):h=window;khtml.maplib.base.helpers.eventAttach(window,"resize",this._setMapPosition,this,!1);navigator.userAgent.indexOf("Konqueror")!=-1&&(h=a);khtml.maplib.base.helpers.eventAttach(a,"touchstart",this._start,this,!1);khtml.maplib.base.helpers.eventAttach(a,"touchmove",
this._move,this,!1);khtml.maplib.base.helpers.eventAttach(a,"touchend",this._end,this,!1);khtml.maplib.base.helpers.eventAttach(h,"mousemove",this._mousemove,this,!1);khtml.maplib.base.helpers.eventAttach(a,"mousedown",this._mousedown,this,!1);khtml.maplib.base.helpers.eventAttach(h,"mouseup",this._mouseup,this,!0);khtml.maplib.base.helpers.eventAttach(h,"orientationchange",this.reSize,this,!1);khtml.maplib.base.helpers.eventAttach(a,"DOMMouseScroll",this._mousewheel,this,!1);khtml.maplib.base.helpers.eventAttach(a,
"dblclick",this._doubleclick,this,!1);khtml.maplib.base.helpers.eventAttach(h,"keydown",this._shiftkeydown,this,!1);khtml.maplib.base.helpers.eventAttach(h,"keyup",this._shiftkeyup,this,!1);khtml.maplib.base.helpers.eventAttach(a,"contextmenu",function(a){a.preventDefault()},this,!1)};khtml.maplib.geometry.Bounds=function(a,c){this.enlarge=function(a){a.lng()>this.southwest.lng()&&a.lng()>this.northeast.lng()&&this.northeast.lng(a.lng());a.lng()<this.southwest.lng()&&a.lng()<this.northeast.lng()&&this.southwest.lng(a.lng());a.lat()>this.southwest.lat()&&a.lat()>this.northeast.lat()&&this.northeast.lat(a.lat());a.lat()<this.southwest.lat()&&a.lat()<this.northeast.lat()&&this.southwest.lat(a.lat())};this.sw=function(a){if(a)this.southwest=a;return this.southwest};this.se=function(){return new khtml.maplib.LatLng(this.southwest.lat(),
this.northeast.lng())};this.ne=function(a){if(a)this.northeast=a;return this.northeast};this.nw=function(){return new khtml.maplib.LatLng(this.northeast.lat(),this.southwest.lng())};this.getCenter=function(){return this.center};this.getOpticalCenter=function(a){var c=a.latlngToXY(this.southwest),d=a.latlngToXY(this.northeast);return a.XYTolatlng(Math.abs(c.x+d.x)/2,Math.abs(c.y+d.y)/2)};this.getZoomLevel=function(a){origZoom=a.getZoom();var c=a.latlngToXY(this.southwest),d=a.latlngToXY(this.northeast),
b=a.width/Math.abs(c.x-d.x);a=a.height/Math.abs(c.y-d.y);if(b>a)var j=a;b<=a&&(j=b);return origZoom+Math.log(j)/Math.log(2)};this.getDistance=function(){return this.distance(this.southwest.lat(),this.southwest.lng(),this.northeast.lat(),this.northeast.lng())};this.getInnerRadius=function(){var a=this.distance(this.center.lat(),this.southwest.lng(),this.center.lat(),this.northeast.lng()),c=this.distance(this.southwest.lat(),this.center.lng(),this.northeast.lat(),this.center.lng());return a>c?c/2:a/
2};this.distance=function(a,c,d,b){a=a*Math.PI/180;d=d*Math.PI/180;return Math.acos(Math.sin(a)*Math.sin(d)+Math.cos(a)*Math.cos(d)*Math.cos(b*Math.PI/180-c*Math.PI/180))*180/Math.PI/360*4E7};this.intersects=function(a){if(!(a instanceof khtml.maplib.geometry.Bounds))return khtml.maplib.base.Log.warn('Bounds.intersects(): Illegal argument. Has to be "khtml.maplib.geometry.Bounds"!'),!1;var c=Math.min(this.sw().lat(),this.ne().lat()),d=Math.max(this.sw().lat(),this.ne().lat()),b=Math.min(this.sw().lng(),
this.ne().lng()),j=Math.max(this.sw().lng(),this.ne().lng()),f=[];f.push(a.ne());f.push(a.se());f.push(a.sw());f.push(a.nw());for(a=0;a<f.length;a++){var A=f[a],F=A.lat()>=c&&A.lat()<=d;A=A.lng()>=b&&A.lng()<=j;if(F&&A)return!0}return!1};this.createBoundsFrom2Points=function(a,c){var d=new khtml.maplib.LatLng(Math.min(a.lat(),c.lat()),Math.min(a.lng(),c.lng())),b=new khtml.maplib.LatLng(Math.max(a.lat(),c.lat()),Math.max(a.lng(),c.lng()));return{sw:d,ne:b}};var d=this.createBoundsFrom2Points(a,c);
this.southwest=d.sw;this.northeast=d.ne;this.center=new khtml.maplib.LatLng((this.southwest.lat()+this.northeast.lat())/2,(this.southwest.lng()+this.northeast.lng())/2)};khtml.maplib.geometry.LatLng=function(a,c){this.callbackFunctions=[];this.addCallbackFunction=function(a){typeof a=="function"&&this.callbackFunctions.push(a)};this.removeCallbackFunction=function(a){for(var c=0;c<this.callbackFunctions.length;c++)this.callbackFunctions[c]==a&&this.callbackFunctions.splice(c,1)};this._executeCallbackFunctions=function(){for(var a=0;a<this.callbackFunctions.length;a++)this.callbackFunctions[a].call(this)};this.lat=function(a){if(typeof a=="number")this.latitude=a,
this._executeCallbackFunctions();else if(typeof a=="string")this.latitude=parseFloat(a),this._executeCallbackFunctions();return this.latitude};this.lng=function(a){if(typeof a=="number")this.longitude=a,this._executeCallbackFunctions();else if(typeof a=="string")this.longitude=parseFloat(a),this._executeCallbackFunctions();return this.longitude};this.equals=function(a){if(null==a)return!1;if(!(a instanceof khtml.maplib.LatLng))return khtml.maplib.base.Log.warn("Point.equals(): Error - illegal argument!",
a),!1;return a.lat()===this.lat()&&a.lng()===this.lng()};a instanceof khtml.maplib.geometry.LatLng?(this.lat(a.lat()),this.lng(a.lng())):typeof a=="object"?(a.lat&&this.lat(a.lat),a.lng&&this.lng(a.lng)):(this.lat(a),this.lng(c))};khtml.maplib.ui.KeyBoard=function(){this.zoomtime=400;this.init=function(a){this.map=a;khtml.maplib.base.helpers.eventAttach(a.mapParent,"keydown",this.keydown,this,!1)};this.keydown=function(a){switch(a.keyCode){case 37:this.moveit(30,0);break;case 38:this.moveit(0,30);break;case 39:this.moveit(-30,0);break;case 40:this.moveit(0,-30);break;case 35:this.moveit(this.map.size.width*0.4,0);break;case 36:this.moveit(-this.map.size.width*0.4,0);break;case 33:this.moveit(0,this.map.size.height*0.4);break;
case 34:this.moveit(0,-this.map.size.height*0.4);break;case 187:case 61:case 43:this.zoomin();break;case 189:case 190:case 109:case 45:this.zoomout();break;default:return}a.preventDefault?a.preventDefault():a.returnValue=!1};this.render=function(){};this.zoomingIn=!1;this.zoomin=function(){var a=Math.ceil(this.map.zoom()+0.1);this.zoomingIn&&a++;this.map.animatedGoto(this.map.center(),a,this.zoomtime);var c=this;setTimeout(function(){c.zoomingIn=!1},this.zoomtime);this.zoomingIn=!0};this.zoomout=
function(){var a=Math.floor(this.map.zoom()-0.1);this.zoomingOut&&a--;this.map.animatedGoto(this.map.center(),a,this.zoomtime);var c=this;setTimeout(function(){c.zoomingOut=!1},this.zoomtime);this.zoomingOut=!0};this.keyup=function(){};this.moveit=function(a,c){for(var d=a/20,e=c/20,g=0;g<20;g++){var h=Math.cos(3*(-10+g)/20)*5;this.moveitexec(d*h,e*h,g)}};this.moveitexec=function(a,c,d){setTimeout(function(){this.map.moveXY(a,c)},20*d)}};
