// --------------------------------------------------------------------------------------------
// khtml javascript library
// --------------------------------------------------------------------------------------------
// (C) Copyright 2010-2011 by Bernhard Zwischenbrugger, Florian Hengartner, Stefan Kemper
//
// Project Info:  http://www.khtml.org
//				  http://www.khtml.org/iphonemap/help.php
//
// This library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with this library.  If not, see <http://www.gnu.org/licenses/>.
// --------------------------------------------------------------------------------------------
var khtml={};khtml.maplib={};khtml.maplib.base={};khtml.maplib.geometry={};khtml.maplib.overlay={};khtml.maplib.overlay.renderer={};khtml.maplib.parser={};khtml.maplib.ui={};khtml.maplib.util={};khtml.maplib.overlay.renderer={};khtml.maplib.version=function(){return"khtmlib_hsr v0.02"};khtml.maplib.Map=function(a){return new khtml.maplib.base.Map(a)};khtml.maplib.LatLng=function(a,c){return new khtml.maplib.geometry.LatLng(a,c)};khtml.maplib.standardimagepath="http://maplib.khtml.org/img/";khtml.maplib.base.helpers={};khtml.maplib.base.helpers.parseXml=function(a){var c;window.ActiveXObject?(c=new ActiveXObject("Microsoft.XMLDOM"),c.async=!1,c.loadXML(a)):document.implementation&&document.implementation.createDocument&&(c=(new DOMParser).parseFromString(a,"text/xml"));return c};
khtml.maplib.base.helpers.contains=function(a,c){var d=[a.sw().lat(),a.ne().lat()],e=[a.sw().lng(),a.ne().lng()];return(khtml.maplib.base.helpers.between(d,c.sw().lat())||khtml.maplib.base.helpers.between(d,c.ne().lat()))&&(khtml.maplib.base.helpers.between(e,c.sw().lng())||khtml.maplib.base.helpers.between(e,c.ne().lng()))?!0:!1};khtml.maplib.base.helpers.overlaps=function(a,c){return a.sw().lng()>c.ne().lng()||a.ne().lng()<c.sw().lng()||a.sw().lat()>c.ne().lat()||a.ne().lat()<c.sw().lat()?!1:!0};
khtml.maplib.base.helpers.overlapsBuggy=function(a,c){var d=[a.sw().lat(),a.ne().lat()],e=[a.sw().lng(),a.ne().lng()],f=[c.sw().lat(),c.ne().lat()],h=[c.sw().lng(),c.ne().lng()];return(khtml.maplib.base.helpers.between(d,c.sw().lat())||khtml.maplib.base.helpers.between(d,c.ne().lat()))&&(khtml.maplib.base.helpers.between(e,c.sw().lng())||khtml.maplib.base.helpers.between(e,c.ne().lng()))||(khtml.maplib.base.helpers.between(f,a.sw().lat())||khtml.maplib.base.helpers.between(f,a.ne().lat()))&&(khtml.maplib.base.helpers.between(h,
a.sw().lng())||khtml.maplib.base.helpers.between(h,a.ne().lng()))?!0:!1};
khtml.maplib.base.helpers.extendBBox=function(a,c){if(!(a instanceof khtml.maplib.geometry.Bounds)){var d=new khtml.maplib.geometry.LatLng(-90,-180),e=new khtml.maplib.geometry.LatLng(90,180);a=new khtml.maplib.geometry.Bounds(e,d)}if(!c)return a;c instanceof khtml.maplib.geometry.LatLng?a=khtml.maplib.base.helpers.extendBBoxByPoint(a,c):(a=khtml.maplib.base.helpers.extendBBoxByPoint(a,c.sw()),a=khtml.maplib.base.helpers.extendBBoxByPoint(a,c.ne()));return a};
khtml.maplib.base.helpers.extendBBoxByPoint=function(a,c){var d=a.sw().lng(),e=a.ne().lat(),f=a.sw().lat(),h=a.ne().lng();c.lat()>e&&(e=c.lat());c.lat()<f&&(f=c.lat());c.lng()<d&&(d=c.lng());c.lng()>h&&(h=c.lng());d=new khtml.maplib.geometry.LatLng(f,d);e=new khtml.maplib.geometry.LatLng(e,h);return new khtml.maplib.geometry.Bounds(d,e)};khtml.maplib.base.helpers.between=function(a,c){return a[0]<=c&&c<=a[1]?!0:!1};
khtml.maplib.base.helpers.cloneObject=function(a){var c={},d;for(d in a)c[d]=typeof a[d]=="object"?khtml.maplib.base.helpers.cloneObject(a[d]):a[d];return c};khtml.maplib.base.helpers.convertObjectToArray=function(a){for(var c=[],d=0,e=a.length;d<e;d++)c.push(a[d]);return c};
khtml.maplib.base.helpers.eventAttach=function(a,c,d,e,f){var h=arguments.length>5?$a(arguments).slice(5,arguments.length):[],b=function(b){h.unshift(b||window.event);return d.apply(e?e:a,h)};a.addEventListener?(navigator.appName.indexOf("Netscape")==-1&&c=="DOMMouseScroll"&&(c="mousewheel"),navigator.userAgent.indexOf("Safari")!=-1?c=="DOMMouseScroll"?a.onmousewheel=b:a.addEventListener(c,b,f):a.addEventListener(c,b,f)):(c=c=="DOMMouseScroll"?"onmousewheel":"on"+c,a.attachEvent(c,b));return{o:a,
type:c,fn:b,c:f}};khtml.maplib.base.helpers.eventRemove=function(a){a.o.removeEventListener&&a.o.removeEventListener(a.type,a.fn,a.c)};khtml.maplib.base.helpers.mixin=function(a,c,d){if(d)if(d instanceof Array)for(var e=0;e<d.length;e++)a[d[e]]=c[d[e]];else c[d]&&(a[d]=c[d]);else for(e in c)a[e]=c[e]};
khtml.maplib.base.helpers.showOnMap=function(a,c){var d=[];a instanceof khtml.maplib.geometry.Bounds&&(khtml.maplib.base.Log.log("Bounds"),khtml.maplib.base.Log.log("Northwest / Topleft",a.nw()),khtml.maplib.base.Log.log("Northeast / Topright",a.ne()),khtml.maplib.base.Log.log("Southeast / Bottomright",a.se()),khtml.maplib.base.Log.log("Southwest / Bottomleft",a.sw()),d.push(a.nw()),d.push(a.ne()),d.push(a.se()),d.push(a.sw()));for(var e=0;e<d.length;e++){var f=document.createElement("div");f.style.width=
"1px";f.style.height="1px";f.style.color="red";f.style["font-size"]="2em";f.textContent="X";f=new khtml.maplib.overlay.Marker(d[e],f);c.addOverlay(f)}};khtml.maplib.base.helpers.cancelEvent=function(a){a.cancelBubble=!0;a.stopPropagation&&a.stopPropagation()};khtml.maplib.base.helpers.stopEventPropagation=function(a){a.preventDefault?a.preventDefault():a.returnValue=!1};khtml.maplib.base.helpers.isIE=function(){return navigator.userAgent.indexOf("MSIE")!=-1};
khtml.maplib.base.helpers.isParentNodeEmpty=function(a){if(khtml.maplib.base.helpers.isIE())return a.parentNode.nodeValue==null;return!a.parentNode};
khtml.maplib.base.helpers.parseLine=function(a){if(a){if(typeof a=="string")a=khtml.maplib.base.helpers.parseLineString;if(typeof a=="object"){if(typeof a[0]=="string"&&typeof a[1]=="string"&&!isNaN(parseFloat(a[0]))&&!isNaN(parseFloat(a[1]))&&a.length==2){var c=parseFloat(a[1]),d=parseFloat(a[0]),e=khtml.maplib.LatLng(c,d);return e}if(typeof a[0]=="number"&&typeof a[0]=="number"&&a.length==2)a=new khtml.maplib.LatLng(a[0],a[1]);else for(e in a){var f=a[e];f instanceof khtml.maplib.geometry.LatLng||
(c=f[1],d=f[0],a[e]=typeof c=="number"&&typeof d=="number"&&f.length==2?new khtml.maplib.LatLng(c,d):khtml.maplib.base.helpers.parseLine(a[e]))}c=a}}else c=[];return c};khtml.maplib.base.helpers.parseLineString=function(a){if(typeof a=="string"){points=[];a=a.split(" ");for(var c=0;c<a.length;c++){var d=a[c].split(",");d.length==2&&(d[0]=parseFloat(d[0]),d[1]=parseFloat(d[1]),points.push(new khtml.maplib.LatLng(d[0],d[1])))}}return points};
khtml.maplib.base.helpers.parseMultiLine=function(a){if(a&&typeof a=="object")for(var c in a){var d=a[c],e;for(e in d){var f=d[e];if(!(f instanceof khtml.maplib.geometry.LatLng)){var h=f[0];f=f[1];typeof h=="number"&&typeof f=="number"&&(d[e]=new khtml.maplib.LatLng(h,f))}}}else a=[];return a};var stop=0;
khtml.maplib.base.helpers.stringify=function(a,c,d){var e=!0;typeof a.push=="undefined"&&(e=!1);for(var f="",h=c?c+1:c===!1?!1:1,b=f="",k=0;k<h-1;k++)b+="   ";c!==!1&&(b="\n"+b,f=b+"   ");c="";for(var g in a)if(g!="owner"&&typeof a[g]!="function")if(a[g]instanceof khtml.maplib.geometry.Bounds)c+=f+'"bbox":',c+="["+a[g].sw().lng()+","+a[g].sw().lat()+",",c+=""+a[g].ne().lng()+","+a[g].ne().lat()+"]",c+=",";else if(a[g]instanceof khtml.maplib.geometry.LatLng)a.type!="Marker"&&(a.type=="Point"&&(c+=
'"coordinates":'),c+="["+a[g].lng()+","+a[g].lat()+"],");else if(typeof a[g]=="string"){if((g=="type"||d)&&g!="animVal")a[g]!="Marker"&&(c+=f+'"'+g+'":"'+a[g]+'",')}else if(e||g=="type"||g=="features"||a[g]&&a[g].type=="Feature"||g=="geometry"||g=="coordinates"||g=="properties"||g=="bbox"||g=="className")c+=e?f+khtml.maplib.base.helpers.stringify(a[g],h)+",":g=="properties"?f+'"'+g+'":'+khtml.maplib.base.helpers.stringify(a[g],h)+",":f+'"'+g+'":'+khtml.maplib.base.helpers.stringify(a[g],h,!0)+",";
c=c.substring(0,c.length-1);return e?"["+c+"]":"{"+c+b+"}"};khtml.maplib.base.helpers.rotate=function(a,c){var d="rotate("+c+"deg)";a.style.webkitTransform=d;a.style.MozTransform=d;a.style.OTransform=d;if(document.all)rad=c*(Math.PI*2/360),costheta=Math.cos(rad),sintheta=Math.sin(rad),a.filters.item(0).M11=costheta,a.filters.item(0).M12=-sintheta,a.filters.item(0).M21=sintheta,a.filters.item(0).M22=costheta};
khtml.maplib.base.helpers.Boundingbox=function(a){this.map=a;this.div=document.createElement("div");this.div.style.border="1px solid black";this.div.style.position="absolute";this.div.style.strokeDasharray="4,4";this.div.style.zIndex=1;a.mapParent.appendChild(this.div);this.show=function(a){this.div.style.display="";var d=this.map.latlngToXY(a.sw());a=this.map.latlngToXY(a.ne());this.div.style.top=a.y-parseInt(this.div.style.borderWidth)+"px";this.div.style.left=d.x-parseInt(this.div.style.borderWidth)+
"px";this.div.style.width=a.x-d.x+"px";this.div.style.height=-a.y+d.y+"px";this.div.zIndex=10};this.hide=function(){this.div.style.display="none"}};khtml.maplib.base.helpers.imageNotSelectable=function(a){a.style.MozUserSelect="none";a.style.webkitUserSelect="none";a.style.webkitUserDrag="none";a.style.KhtmlUserSelect="none";a.style.OUserSelect="none";a.style.userSelect="none"};
khtml.maplib.base.helpers.setCursor=function(a,c){if(navigator.userAgent.indexOf("MSIE")!=-1)a.style.cursor=c=="grab"?"url('"+khtml.maplib.standardimagepath+"hand.cur'), default":c=="grabbing"?"url('"+khtml.maplib.standardimagepath+"fist.cur'), move":"pointer";else if(a.style.cursor="-moz-"+c,a.style.cursor!="-moz-"+c&&(a.style.cursor="-webkit-"+c,a.style.cursor!="-webkit-"+c&&(a.style.cursor="-ms-"+c,a.style.cursor!="-ms-"+c&&(a.style.cursor="-khtml-"+c,a.style.cursor!="-khtml-"+c&&(a.style.cursor=
c,a.style.cursor!=c)))))a.style.cursor="pointer"};khtml.maplib.base.Map=function(a){typeof a=="string"&&(a=document.getElementById(a));(typeof a!="object"||null==a)&&console.log("Error: map is null or not an object. (map: "+a+")");this.addOverlay=function(b){if(null==b||b instanceof Array)return khtml.maplib.base.Log.warn('Map.addOverlay(): Illegal argument (was "null" or "Array")'),!1;this.overlays.push(b);typeof b.init=="function"&&b.init(this);this.renderOverlay(b)};this.addOverlays=function(b){if(b instanceof Array)for(var k=0;k<b.length;k++)this.addOverlay(b[k]);
else this.addOverlay(b)};this.renderOverlay=function(b){try{b.render()}catch(k){}};this.renderOverlays=function(){for(obj in this.overlays)this.overlays[obj].render()};this._hideOverlays=function(){for(obj in this.overlays)try{this.overlays[obj].clear(f)}catch(b){}};this.removeOverlays=function(){for(;this.overlays.length>0;)this.overlays.pop().clear()};this.stopRenderOverlays=function(){for(obj in this.overlays)typeof this.overlays[obj].cancel=="function"&&this.overlays[obj].cancel()};this.removeOverlay=
function(b){for(var k=0;k<this.overlays.length;k++)if(b==this.overlays[k]){b.clear();this.overlays.splice(k,1);break}};this.callbackFunctions=[];this.addCallbackFunction=function(b){typeof b=="function"&&this.callbackFunctions.push(b)};this._executeCallbackFunctions=function(){for(var b=0;b<this.callbackFunctions.length;b++)this.callbackFunctions[b].call(this)};this.myTimer=function(b){this.reset=function(){this._isRunning=!1};this.isTimeRunning=function(){if(!1==this._isRunning)return!1;if(this.time+
this.myInterval>(new Date).getTime())return!1;this._isRunning=!1;return!0};this.start=function(){this._isRunning=!0;this.time=(new Date).getTime()};this.interval=function(b){if(typeof b!="undefined")this.myInterval=parseInt(b);return this.myInterval};this.reset();this.interval(b);return this};this.oldMoveY=this.oldMoveX=0;this._start=function(b){b.preventDefault?b.preventDefault():b.returnValue=!1;this.moveAnimationBlocked=!0;if(b.touches.length==1){this.startMoveX=this.moveX-this.pageX(b.touches[0])/
this.faktor/this.sc;this.startMoveY=this.moveY-this.pageY(b.touches[0])/this.faktor/this.sc;if(this.mousedownTime!=null&&(new Date).getTime()-this.mousedownTime<this._doubleclickTime){var k=Math.ceil(0.01+this._getZoom()-this.intZoom);this._autoZoomIn(this.pageX(b.touches[0]),this.pageY(b.touches[0]),k)}this.mousedownTime=(new Date).getTime();clearTimeout(this.zoomOutInterval);this.zoomOutInterval=window.setInterval(function(){},20)}if(b.touches.length==2){window.clearInterval(this.zoomOutInterval);
this.moveok=!1;k=this.pageX(b.touches[0]);var a=this.pageY(b.touches[0]),c=this.pageX(b.touches[1]);b=this.pageY(b.touches[1]);this.startDistance=Math.sqrt(Math.pow(c-k,2)+Math.pow(b-a,2));this.startZZ=this.position.zoom;b=(a+b)/2/this.faktor/this.sc;this.startMoveX=this.moveX-(k+c)/2/this.faktor/this.sc;this.startMoveY=this.moveY-b}this.oldMoveX=this.moveX;this.oldMoveY=this.moveY};this.moveok=!0;this._move=function(b){b.preventDefault?b.preventDefault():b.returnValue=!1;if(b.touches.length==1&&
this.moveok){this.lastMoveX=this.moveX;this.lastMoveY=this.moveY;this.lastMoveTime=new Date(b.timeStamp);this.moveX=this.pageX(b.touches[0])/this.faktor/this.sc+this.startMoveX;this.moveY=this.pageY(b.touches[0])/this.faktor/this.sc+this.startMoveY;if(!this.zoomOutStarted){if(Math.abs(this.moveX-this.oldMoveX)>5||Math.abs(this.moveY-this.oldMoveY)>5)window.clearInterval(this.zoomOutInterval),this.zoomOutSpeed=0.01,this.mousedownTime=null;var k=new khtml.maplib.LatLng(this.lat,this.lng);this.setCenter2(k,
this.position.zoom);this.moveAnimationBlocked=!1}if(Math.abs(this.moveX-this.oldMoveX)>5||Math.abs(this.moveY-this.oldMoveY)>5)this.mousedownTime=null}if(b.touches.length==2){this.mousedownTime=null;var a=this.pageX(b.touches[0]),c=this.pageY(b.touches[0]),d=this.pageX(b.touches[1]),e=this.pageY(b.touches[1]);k=Math.sqrt(Math.pow(d-a,2)+Math.pow(e-c,2))/this.startDistance;b=this.startZZ+k-1;b>this.tileSource.maxzoom?(b=this.tileSource.maxzoom,k=this.zoomDeltaOld):this.zoomDeltaOld=k;a=(a+d)/2;c=(c+
e)/2;faktor=Math.pow(2,b);d=a/faktor-this.width/2;e=c/faktor-this.height/2;k=Math.pow(2,k-1);this.moveX=(a+(d-d*k))/faktor+this.startMoveX;this.moveY=(c+(e-e*k))/faktor+this.startMoveY;k=new khtml.maplib.LatLng(this.lat,this.lng);this.setCenter2(k,b)}};this._end=function(b){b.preventDefault?b.preventDefault():b.returnValue=!1;window.clearInterval(this.zoomOutInterval);this.zoomOutStarted=!1;this.zoomOutSpeed=0.01;if(b.touches.length==0&&(this.moveok=!0,this.moveAnimationMobile&&this.moveAnimationBlocked==
!1)){var a=new Date(b.timeStamp)-this.lastMoveTime,g=(this.lastMoveX-this.moveX)/a*4;a=(this.lastMoveY-this.moveY)/a*4;var c=this.wheelSpeedConfig.animateMaxSpeed;g>c&&(g=c);a>c&&(a=c);g<-c&&(g=-c);a<-c&&(a=-c);c=Math.pow(2,this.zoom());(Math.abs(g)>this.wheelSpeedConfig.animateMinSpeed/c||Math.abs(a)>this.wheelSpeedConfig.animateMinSpeed/c)&&this._animateMove(g,a,c)}if(b.touches.length==1)this.startMoveX=this.moveX-b.touches[0].pageX/this.faktor/this.sc,this.startMoveY=this.moveY-b.touches[0].pageY/
this.faktor/this.sc};this.pageX=function(b){try{return(b.pageX===void 0?b.clientX+document.body.scrollLeft:b.pageX)-this.mapLeft}catch(a){return this.lastMouseX}};this.pageY=function(b){try{return(b.pageY===void 0?b.clientY+document.body.scrollTop:b.pageY)-this.mapTop}catch(a){return this.lastMouseY}};this.doubleclickBlocked=!1;this._doubleclick=function(b){var a;if(!b)b=window.event;b.which?a=b.which==3:b.button&&(a=b.button==2);a?this._discretZoom(-1,this.pageX(b),this.pageY(b)):this._discretZoom(1,
this.pageX(b),this.pageY(b))};this._mousedown=function(b){this.mapParent.focus();b.preventDefault?b.preventDefault():window.event.returnValue=!1;this.lastMouseX=this.pageX(b);this.lastMouseY=this.pageY(b);this.moveAnimationBlocked=!0;if(this.mousedownTime2!=null&&(new Date).getTime()-this.mousedownTime2<this.doubleclickTime2)this._doubleclick(b);else{this.mousedownTime2=(new Date).getTime();if(b.shiftKey){this.selectRectLeft=this.pageX(b);this.selectRectTop=this.pageY(b);this.selectRect=document.createElement("div");
this.selectRect.style.left=this.selectRectLeft+"px";this.selectRect.style.top=this.selectRectTop+"px";this.selectRect.style.border="1px solid gray";if(!this.internetExplorer)this.selectRect.style.opacity=0.5,this.selectRect.style.backgroundColor="white";this.selectRect.style.position="absolute";this.map.parentNode.appendChild(this.selectRect);khtml.maplib.base.helpers.setCursor(this.mapParent,"crosshair")}else this.startMoveX=this.moveX-this.pageX(b)/this.faktor/this.sc,this.startMoveY=this.moveY-
this.pageY(b)/this.faktor/this.sc,this.movestarted=!0,khtml.maplib.base.helpers.setCursor(this.mapParent,"grabbing");return!1}};this._mousemove=function(b){b.preventDefault?b.preventDefault():window.event.returnValue=!1;this.lastMouseX=this.pageX(b);this.lastMouseY=this.pageY(b);if(b.shiftKey){if(this.selectRect){this.selectRect.style.width=Math.abs(this.pageX(b)-this.selectRectLeft)+"px";this.selectRect.style.height=Math.abs(this.pageY(b)-this.selectRectTop)+"px";if(this.pageX(b)<this.selectRectLeft)this.selectRect.style.left=
this.pageX(b)+"px";if(this.pageY(b)<this.selectRectTop)this.selectRect.style.top=this.pageY(b)+"px"}}else if(this.movestarted)this.lastMoveX=this.moveX,this.lastMoveY=this.moveY,this.lastMoveTime=new Date(b.timeStamp),this.moveX=this.pageX(b)/this.faktor/this.sc+this.startMoveX,this.moveY=this.pageY(b)/this.faktor/this.sc+this.startMoveY,this.setCenter2(new khtml.maplib.LatLng(this.lat,this.lng),this.position.zoom),this.moveAnimationBlocked=!1;return!1};this._mouseup=function(b){b.preventDefault?
b.preventDefault():b.returnValue=!1;khtml.maplib.base.helpers.setCursor(this.mapParent,"grab");this.lastMouseX=this.pageX(b);this.lastMouseY=this.pageY(b);if(this.moveMarker)this.moveMarker=null;if(this.selectRect){var a=this.XYTolatlng(this.selectRect.offsetLeft,this.selectRect.offsetTop+this.selectRect.offsetHeight),g=this.XYTolatlng(this.selectRect.offsetLeft+this.selectRect.offsetWidth,this.selectRect.offsetTop);this._setBounds(new khtml.maplib.geometry.Bounds(a,g));this.selectRect.parentNode.removeChild(this.selectRect);
this.selectRect=null}a=new Date(b.timeStamp)-this.lastMoveTime;if(this.wheelSpeedConfig.moveAnimateDesktop&&a!=0&&this.movestarted&&this.moveAnimationBlocked==!1)b=(this.lastMoveX-this.moveX)/a,a=(this.lastMoveY-this.moveY)/a,g=this.wheelSpeedConfig.animateMaxSpeed,b>g&&(b=g),a>g&&(a=g),b<-g&&(b=-g),a<-g&&(a=-g),g=Math.pow(2,this.zoom()),(Math.abs(b)>this.wheelSpeedConfig.animateMinSpeed/g||Math.abs(a)>this.wheelSpeedConfig.animateMinSpeed/g)&&this._animateMove(b,a,g);var c=this;setTimeout(function(){c.movestarted=
!1},1)};this._mouseupIE=function(b){b.preventDefault?b.preventDefault():b.returnValue=!1;this.lastMouseX=this.pageX(b);this.lastMouseY=this.pageY(b);this.setCenter2(this.XYTolatlng(this.lastMouseX,this.lastMouseY),this.zoom())};this.startZoomTime=null;this._mousewheel=function(b){b.preventDefault?b.preventDefault():b.returnValue=!1;this.mapParent.focus();if(!b)b=window.event;if(b.wheelDelta)var a=b.wheelDelta/60;else if(b.detail)a=-b.detail/3,this.lastWheelDelta*a<0&&(this.wheelSpeedConfig.digizoom||
(a=0)),this.lastWheelDelta=-b.detail/3;a=a<0?-1:1;if(this.wheelSpeedConfig.digizoom)this._discretZoom(a,this.pageX(b),this.pageY(b));else{if(!this.startZoomTime)this.startZoomTime=new Date,this.startZoomTime2=new Date,this.oldZoom=this.zoom(),this.speed=1;var g=new Date-this.startZoomTime,c=new Date-this.startZoomTime2;this.startZoomTime=new Date;if(g>300)this.startZoomTime2=new Date,this.oldZoom=this.zoom(),this.speed=1,c=0.1;this.speed*=2;if(this.speed>5)this.speed=5;a=this.oldZoom+c/3E3*this.speed*
a;if(a>this.position.maxZoom)a=this.position.maxZoom;if(a<this.position.minZoom)a=this.position.minZoom;this.centerAndZoomXY(this.center(),a,this.pageX(b),this.pageY(b))}};this._shiftkeydown=function(b){b.shiftKey&&khtml.maplib.base.helpers.setCursor(this.mapParent,"crosshair")};this._shiftkeyup=function(){khtml.maplib.base.helpers.setCursor(this.mapParent,"grab")};this.zoomTimeouts=[];this.discretZoomBlocked=!1;this._discretZoom=function(b,a,g){if(!this.discretZoomBlocked){var c=this;this.discretZoomBlockedTimeout=
setTimeout(function(){c.discretZoomBlocked=!1},200);this.discretZoomBlocked=!0;for(var d=1;d<=20;d++)this.zoomTimeouts[d]&&clearTimeout(this.zoomTimeouts[d]);d=this.zoom();var e=b==1?Math.ceil(this.zoom()+0.9):Math.floor(this.zoom()-0.9);e=Math.abs(d-e);var f=0;for(d=1;d<=20;d++){var j=b*Math.sin(d/20*Math.PI/2)*e;this.zoomTimeouts[d]=this._discretZoomExec(a,g,j-f,d,20);f=j}}};this._discretZoomExec=function(b,a,g,c,d){var e=this;return setTimeout(function(){var f=e.zoom()+g;c==d&&(f=Math.round(f));
e.centerAndZoomXY(e.center(),f,b,a)},c*20)};this.digizoomblocked=!1;this.wheelZoomTimeout=this.digizoomblockedTimeout=null;this._animateMove=function(b,a,g){clearTimeout(this.animateMoveTimeout);if(!(Math.abs(b)<this.wheelSpeedConfig.animateMinSpeed/g&&Math.abs(a)<this.wheelSpeedConfig.animateMinSpeed/g)){this.moveX+=-b;this.moveY+=-a;var c=this,d=Math.sqrt(Math.pow(b,2)+Math.pow(a,2)),e=b/d,f=a/d;this.animateMoveTimeout=window.setTimeout(function(){c._animateMove(b-e*c.wheelSpeedConfig.moveAnimationSlowdown/
g,a-f*c.wheelSpeedConfig.moveAnimationSlowdown/g,g)},20);this.setCenter2(this.position.center,this.position.zoom)}};this.autoZoomStartTime=this.autoZoomInTimeout=null;this._autoZoomIn=function(b,a,c){this.autoZoomInTimeout&&window.clearTimeout(this.autoZoomInTimeout);var d=0.2;c<0&&(d=-d);zoomGap=!1;Math.abs(c)<=Math.abs(d)&&(zoomGap=!0);var e=this.position.zoom+d;e=Math.round(e*1E3)/1E3;zoomGap&&(e=c<0?Math.floor(e):Math.ceil(e-0.2),d=e-this.position.zoom);faktor=Math.pow(2,e);var i=b-this.mapLeft-
this.width/2,f=a-this.mapTop-this.height/2,j=Math.pow(2,d);i-=i*j;f-=f*j;var h=this;j=(new Date).getMilliseconds();var n=this.autoZoomStartTime?j-this.autoZoomStartTime:0;this.autoZoomStartTime=j;if(n<100||zoomGap){e>=this.tileSource.minzoom&&e<=this.tileSource.maxzoom&&(this.moveX+=i/faktor,this.moveY+=f/faktor);var l=new khtml.maplib.LatLng(this.lat,this.lng);if(e>this.tileSource.maxzoom)e=this.tileSource.maxzoom;if(e<this.tileSource.minzoom)e=this.tileSource.minzoom;setTimeout(function(){h.setCenter2(l,
e)},1)}var o=c-d;zoomGap?this.digizoomblocked=!1:this.autoZoomInTimeout=window.setTimeout(function(){h._autoZoomIn(b,a,o)},40)};this.centerAndZoomXY=function(b,a,c,d){faktor=Math.pow(2,a);b=c-this.size.width/2;d-=this.size.height/2;c=a-this.zoom();c=Math.pow(2,c);b-=b*c;d-=d*c;a>=this.tileSource.minzoom&&a<=this.tileSource.maxzoom&&(this.moveX+=b/faktor,this.moveY+=d/faktor);b=new khtml.maplib.LatLng(this.lat,this.lng);if(a>this.tileSource.maxzoom)a=this.tileSource.maxzoom;if(a<this.tileSource.minzoom)a=
this.tileSource.minzoom;this.setCenter2(b,a)};this.centerAndZoom=function(b,a){this.moveY=this.moveX=0;if(a>this.tileSource.maxzoom)a=this.tileSource.maxzoom;if(a<this.tileSource.minzoom)a=this.tileSource.minzoom;this.record();this.setCenterNoLog(b,a)};this.render=function(){this.center(this.center())};this._setCenter3=function(b,a){this.moveY=this.moveX=0;this.setCenterNoLog(b,a)};this.setCenter2=function(b,a){this.record();this.setCenterNoLog(b,a)};this.setCenterNoLog=function(b,a){this.position.center=
b;this.lat=b.lat();this.lng=b.lng();a=parseFloat(a);if(a>this.tileSource.maxzoom)a=this.tileSource.maxzoom;if(a<this.tileSource.minzoom)a=this.tileSource.minzoom;this.position.center=b;this.position.zoom=a;this.layer(this.map,this.lat,this.lng,this.moveX,this.moveY,a);this._executeCallbackFunctions();this._getBounds()};this.center=function(b){typeof b!="undefined"&&this.centerAndZoom(b,this._getZoom());if(this.moveX!=0||this.moveY!=0)return b=new khtml.maplib.LatLng(this.movedLat,this.movedLng);return this.position.center};
this.zoom=function(b){typeof b!="undefined"&&this.centerAndZoom(this.position.center,b);return this.position.zoom};this.moveXY=function(b,a){this.moveX=parseFloat(b)/this.faktor/this.sc+this.moveDelayedX;this.moveY=parseFloat(a)/this.faktor/this.sc+this.moveDelayedY;this.setCenter2(this.center(),this.zoom())};this.tiles=function(b){this.clearMap();this.tileSource=b};this.tileOverlays=[];this.addTilesOverlay=function(b){this.tileOverlays.push(b);b=this.tileOverlays[this.tileOverlays.length-1];this.clearMap();
return b};this.removeTilesOverlay=function(b){for(var a=0;a<this.tileOverlays.length;a++)if(b==this.tileOverlays[a]){this.tileOverlays.splice(a,1);break}this.clearMap()};this._getCenter=function(){if(this.moveX!=0||this.moveY!=0)var b=new khtml.maplib.LatLng(this.movedLat,this.movedLng);else if(this.position.center)b=this.position.center;return b};this.bounds=function(b){if(typeof b!="undefined")this._setBounds(b);else return this.mapBounds};this.mapBounds=null;this._getBounds=function(){var b=this.XYTolatlng(0,
this.height),a=this.XYTolatlng(this.width,0);this.mapBounds=new khtml.maplib.geometry.Bounds(b,a)};this._setBounds=function(b){if(typeof khtml.maplib.geometry.Bounds=="undefined"||!(b instanceof khtml.maplib.geometry.Bounds))return!1;var a=b.sw();b=b.ne();var c=a.lat(),f=b.lat();a=a.lng();b=b.lng();c=d(c);var h=d(f);f=(a+b)/2;var i=e((c+h)/2);f=new khtml.maplib.LatLng(i,f);c=Math.abs(h-c);a=Math.abs(b-a);a/this.width>c/this.height?b=this.width:(a=c,b=this.height);a=Math.log(360/a/(512/b))/Math.log(2)+
1;if(a>this.tileSource.maxzoom)a=this.tileSource.maxzoom;if(a<this.tileSource.minzoom)a=this.tileSource.minzoom;this.position.center?this.wheelSpeedConfig.rectShiftAnimate?this.animatedGoto(f,a,this.wheelSpeedConfig.rectShiftAnimationTime):this.centerAndZoom(f,a):this.centerAndZoom(f,a)};this.animatedGotoStep=null;this.animatedGotoTimeout=[];this.animatedGoto=function(b,a,c){c/=10;var d=this._getCenter(),e=b.lat();b=b.lng();var f=d.lat(),h=d.lng(),j=this._getZoom(),s=(e-f)/c,n=(b-h)/c,l=(a-j)/c,o=
this.moveX/c,v=this.moveY/c,C=this.moveX,q=this.moveY;this.animatedGotoStep=0;for(var t=this;timeout=this.animatedGotoTimeout.pop();)clearTimeout(timeout);for(a=0;a<=c;a++)this.animatedGotoTimeout[a]=window.setTimeout(function(){t._animatedGotoExec(f,h,j,s,n,l,C,q,o,v)},10*a)};this._animatedGotoExec=function(b,a,c,d,e,f,h,j,s,n){this.moveX=-s;this.moveY=-n;b+=d*this.animatedGotoStep;a+=e*this.animatedGotoStep;c+=f*this.animatedGotoStep;this.animatedGotoStep++;this.centerAndZoom(new khtml.maplib.LatLng(b,
a),c)};this._getZoom=function(){return this.position.zoom};this._getIntZoom=function(){return this.intZoom};this.latlngToXY=function(b){var a=b.lat(),d=b.lng();a>90&&(a-=180);a<-90&&(a+=180);b=this._getIntZoom();tileTest=c(a,d,b);a=this._getCenter();b=c(a.lat(),a.lng(),b);a=(b[0]-tileTest[0])*this.tileW*this.sc-this.width/2;d=(b[1]-tileTest[1])*this.tileW*this.sc-this.height/2;b=[];b.x=-a;b.y=-d;return b};this.XYTolatlng=function(b,a){var d=this._getCenter();if(d){var f=Math.pow(2,this.intZoom),h=
d.lat();d=d.lng();d=c(h,d,this.intZoom);h=(d[0]+(b-this.width/2)/this.tileW/this.sc)/f*360-180;f=-e((d[1]+(a-this.height/2)/this.tileH/this.sc)/f*360-180)+0;return new khtml.maplib.LatLng(f,h)}};this.mouseToLatLng=function(b){var a=this.pageX(b);b=this.pageY(b);return this.XYTolatlng(a,b)};this.reSize=function(){var b=this;window.setTimeout(function(){b._getSize(b)},1050)};this._getSize=function(){this.width=this.map.parentNode.offsetWidth;this.height=this.map.parentNode.offsetHeight;var b=this.map,
a=0,c=0;do a+=b.offsetLeft,c+=b.offsetTop,b=b.offsetParent;while(b.offsetParent);this.mapTop=c;this.mapLeft=a};this.recordArray=[];this.record=function(){var b=this._getCenter();if(b){var a=b.lat();b=b.lng();var c=this._getZoom();this.recordArray.push([a,b,c])}};this.play=function(b){if(!(b<1)&&!(b>this.recordArray.length-1)){b=this.recordArray[b];var a=new khtml.maplib.LatLng(b[0],b[1]);this.moveY=this.moveX=0;this._setCenter3(a,b[2])}};this.layerDrawLastFrame=null;this.doTheOverlayes=!0;this.finalDraw=
!1;this.moveDelayedY=this.moveDelayedX=this.layerOldZoom=0;this.layerTimer=new this.myTimer(300);this.layer=function(b,a,c,d,e,f){this.stopRenderOverlays();f||(f=this._getZoom());if(this.layerDrawLastFrame)window.clearTimeout(this.layerDrawLastFrame),this.layerDrawLastFrame=null;if(this.layerTimer.isTimeRunning()||this.finalDraw==!1){var h=this,j=function(){h.finalDraw=!0;h.layer(b,a,c,d,e,f)};if(!h.finalDraw)this.layerDrawLastFrame=window.setTimeout(j,100);if(this.layerTimer.isTimeRunning()){this.moveDelayedX=
d;this.moveDelayedY=e;return}}this.layerTimer.start();for(j=this.moveDelayedY=this.moveDelayedX=0;j<22;j++)if(this.layers[j])this.layers[j].layerDiv.style.visibility="hidden";j=this.wheelSpeedConfig.digizoom?Math.floor(f):Math.round(f);if(this.layerOldZoom>f&&!this.finalDraw&&this.layers[j]&&!this.layers[j].loadComplete)this.visibleZoom=j+1;this.intZoom=j;if(j>this.tileSource.maxzoom)j=this.tileSource.maxzoom;if(!this.visibleZoom)this.oldIntZoom=this.visibleZoom=j;this.faktor=Math.pow(2,j);this.sc=
Math.pow(2,f-j);this.loadingZoomLevel=j;if(this.visibleZoom<j&&Math.abs(this.visibleZoom-j)<4)this.loadingZoomLevel=parseInt(this.visibleZoom)+1;this.draw(this.map,a,c,d,e,this.loadingZoomLevel,f,this.tileSource.src);this.layers[this.loadingZoomLevel].layerDiv.style.visibility="";if(j!=this.visibleZoom)this.visibleZoom<j+2?(this.draw(this.map,a,c,d,e,this.visibleZoom,f,this.tileSource.src),this.layers[this.visibleZoom].layerDiv.style.visibility=""):this.layers[this.visibleZoom].layerDiv.style.visibility=
"hidden";if(j==this.visibleZoom)this.draw(this.map,a,c,d,e,this.visibleZoom-1,f,this.tileSource.src),this.layers[this.visibleZoom-1].layerDiv.style.visibility="hidden";if(this.layers[this.loadingZoomLevel].loadComplete&&this.visibleLayer!=j)this.layers[this.loadingZoomLevel].loadComplete=!1,this._hideLayer(this.visibleZoom),this.visibleZoom=this.loadingZoomLevel;this.quadtreeTimeout&&clearTimeout(this.quadtreeTimeout);if(this.loadingZoomLevel!=j)h=this,this.quadtreeTimeout=window.setTimeout(function(){h.layer(b,
a,c,d,e)},200);this.oldIntZoom!=this.intZoom&&this.oldIntZoom!=this.visibleZoom&&this._hideLayer(this.oldIntZoom);this.oldIntZoom=j;this.delayedOverlay&&window.clearTimeout(this.delayedOverlay);this.doTheOverlayes||this.finalDraw||this.layerOldZoom==this.zoom()?(j=new Date,this.lastDX=this.moveX,this.lastDY=this.moveY,this.renderOverlays(),this.layerOldZoom=this.zoom(),this.doTheOverlayes=new Date-j>10&&!this.finalDraw?!1:!0):this._hideOverlays();h=this;this.layerBlockTimeout&&clearTimeout(this.layerBlockTimeout);
this.layerBlockTimeout=window.setTimeout(function(){h.layerTimer.reset()},20);this.finalDraw=!1};this.draw=function(b,a,g,f,h,i,p,j){this.framesCounter++;var s=this;window.setTimeout(function(){s.framesCounter--},1E3);var n=Math.pow(2,i);if(this.layers[i])l=this.layers[i].layerDiv,o=d(a)-this.layers[i].startLat,g-=this.layers[i].startLng;else{o=c(a,g,i);this.layers[i]=[];this.layers[i].startTileX=o[0];this.layers[i].startTileY=o[1];this.layers[i].startLat=d(a);this.layers[i].startLng=g;this.layers[i].images=
{};var l=document.createElement("div");l.setAttribute("zoomlevel",i);l.style.position="absolute";o=b.childNodes;b=!1;for(g=o.length-1;g>=0;g--)a=o.item(g),a.getAttribute("zoomlevel")<i&&(this.map.insertBefore(l,a),b=!0);b||this.map.appendChild(l);this.layers[i].layerDiv=l;var o=0;g=0}l.style.visibility="hidden";l.style.opacity=1;l.style.filter="alpha(opacity=100)";this.movedLng=(this.layers[i].startTileX/n-f/this.tileW)*360-180+g;this.movedLat=-e((this.layers[i].startTileY/n-h/this.tileH)*360-180-
o);o=c(this.movedLat,this.movedLng,i);f=o[0];g=o[1];h=Math.floor(f);b=Math.floor(g);a=this.layers[i].startTileX;var v=this.layers[i].startTileY;f=f-a-(-a+Math.floor(a));var C=g-v-(-v+Math.floor(v)),q;for(q in this.layers[i].images)this.layers[i].images[q].visibility=!1;g=this.width;var t=this.height;w=Math.pow(2,p-i);minX=Math.floor(-g/2/w/this.tileW+f);maxX=Math.ceil(g/2/w/this.tileW+f);minY=Math.floor(-t/2/w/this.tileH+C);maxY=Math.ceil(t/2/w/this.tileH+C);for(g=minX;g<maxX;g++)for(t=minY;t<maxY;t++){var r=
Math.floor(a+g),m=Math.floor(v+t),x=r%n,u=m;x<0&&(x+=n);if(!(u<0)&&!(u>=n)){var z=j(x,u,i);r=z+"-"+r+"-"+m;minsc=this.wheelSpeedConfig.digizoom?1:0.5;if(this.layers[i].images[r]==null&&w>=minsc){m=document.createElement("img");m.style.visibility="hidden";m.style.position="absolute";m.style.left=g*this.tileW+"px";m.style.top=t*this.tileH+"px";m.style.width=this.tileW+"px";m.style.height=this.tileH+"px";if(this.tileSource.opacity)m.style.opacity=this.tileSource.opacity;l.childNodes.length>0?l.insertBefore(m,
l.childNodes.item(0)):l.appendChild(m);this.layers[i].images[r]={};this.layers[i].images[r].img=m;this.layers[i].images[r].array=[];this.layers[i].images[r].array.push(m);this.layers[i].loadComplete=!1;for(ov in this.tileOverlays){var A=this.tileOverlays[ov],y=m.cloneNode(!0);A=A.src(x,u,i);y.setAttribute("overlay",ov);khtml.maplib.base.helpers.eventAttach(y,"load",this._imgLoaded,this,!1);l.appendChild(y);y.setAttribute("src",A);this.layers[i].images[r].array.push(y)}khtml.maplib.base.helpers.eventAttach(m,
"load",this._imgLoaded,this,!1);khtml.maplib.base.helpers.eventAttach(m,"error",this._imgError,this,!1);m.setAttribute("src",z)}if(!this.css3d&&this.layers[i].images[r]){x=this.layers[i].images[r].array;for(u=0;u<x.length;u++){var D=o[0]-h+Math.floor(f);y=o[1]-b+Math.floor(C);var E=Math.round(this.tileW*w);A=Math.round(this.tileH*w);z=Math.floor(-D*E+g*E);m=Math.floor(-y*A+t*A);D=Math.floor(-D*E+(g+1)*E);y=Math.floor(-y*A+(t+1)*A);x[u].style.left=z+"px";x[u].style.top=m+"px";x[u].style.height=D-z+
"px";x[u].style.width=y-m+"px"}}this.layers[i].images[r]&&(this.layers[i].images[r].visibility=!0)}}for(q in this.layers[i].images)if(this.layers[i].images[q].visibility){if(this.layers[i].images[q].array[0].getAttribute("loaded")=="yes"){j=this.layers[i].images[q].array;for(n=0;n<j.length;n++)if(j[n].getAttribute("loaded")=="yes")j[n].style.visibility=""}}else{j=this.layers[i].images[q].array;for(n=0;n<j.length;n++)this.layers[i].images[q].array[n].style.visibility="hidden",this.layers[i].images[q].array[n].getAttribute("loaded")!=
"yes"&&l.removeChild(this.layers[i].images[q].array[n]);delete this.layers[i].images[q].img;delete this.layers[i].images[q]}var w=Math.pow(2,p-i);z=-f*this.tileW;m=-C*this.tileH;if(this.css3d)l.style["-webkit-transform-origin"]=-1*z+"px "+-1*m+"px",l.style.webkitTransform="translate3d("+z+"px,"+m+"px,0px)  "+(" scale3d("+w+","+w+",1) ");l.style.visibility="";l.style.opacity=1;l.style.filter="";l=p=0;for(q in this.layers[this.loadingZoomLevel].images)l++,m=this.layers[this.loadingZoomLevel].images[q].array[0],
m.getAttribute("loaded")!="yes"&&p++;this.notLoadedImages=p;p<1&&(this.layers[this.loadingZoomLevel].loadComplete=!0);this.loadingZoomLevel==i&&this._imgLoadInfo(l,p)};this.fadeOutTimeout=null;this._fadeOut=function(a,c){this.fadeOutTimeout&&clearTimeout(this.fadeOutTimeout);if(c>0){a.style.opacity=c;a.style.filter="alpha( opacity="+c*100+" )";var d=this;this.fadeOutTimeout=setTimeout(function(){d._fadeOut(a,c-0.2)},40)}else a.style.visibility="hidden"};this._hideLayer=function(a){if(this.intZoom!=
a&&this.layers[a])this.layers[a].layerDiv.style.opacity=1,this.layers[a].layerDiv.style.filter="alpha(opacity=100)",this._fadeOut(this.layers[a].layerDiv,1);if(this.layers[a])for(var c in this.layers[a].images)if(this.layers[a].images[c]&&this.layers[a].images[c].img&&this.layers[a].images[c].img.getAttribute("loaded")!="yes"&&a!=this.intZoom){for(var d=this.layers[a].images[c].array,e=0;e<d.length;e++)this.layers[a].layerDiv.removeChild(this.layers[a].images[c].array[e]);delete this.layers[a].images[c].img;
delete this.layers[a].images[c]}};this._imgLoaded=function(a){a=a.target?a.target:a.srcElement;var c=!0;a.style.visibility="";a.setAttribute("loaded","yes");if(a.parentNode){for(var d=0,e=0,f=a.parentNode.getAttribute("zoomlevel"),h=0;h<a.parentNode.getElementsByTagName("img").length;h++){var p=a.parentNode.getElementsByTagName("img").item(h);p.getAttribute("overlay")||(e++,p.getAttribute("loaded")!="yes"&&(d++,c=!1))}this.notLoadedImages=d;this.loadingZoomLevel==f&&this._imgLoadInfo(e,d);if((this.layers[f].loadComplete=
c)&&this.loadingZoomLevel==f)this._hideLayer(this.visibleZoom),this._hideLayer(this.visibleZoom+1),this.visibleZoom=f}};this._imgError=function(a){var c=a.target?a.target:a.srcElement;c.parentNode&&(c.src!="http://khtml.org/notfound.png"&&c.setAttribute("src","http://khtml.org/notfound.png"),this._imgLoaded(a))};var c=function(a,c,d){return[(c+180)/360*(1<<d),(1-Math.log(Math.tan(a*Math.PI/180)+1/Math.cos(a*Math.PI/180))/Math.PI)/2*(1<<d)]};this._calculateMapSize=function(){var a=this.mapParent;if(a.currentStyle)var c=
a.currentStyle;else window.getComputedStyle&&(c=document.defaultView.getComputedStyle(a,null));var d=parseInt(c.borderTopWidth);isNaN(d)&&(d=0);var e=parseInt(c.borderLeftWidth);isNaN(e)&&(e=0);var f=parseInt(c.borderRightWidth);isNaN(f)&&(f=0);var h=parseInt(c.borderBottomWidth);isNaN(h)&&(h=0);var p=parseInt(c.paddingTop),j=parseInt(c.paddingBottom),s=parseInt(c.paddingLeft),n=parseInt(c.paddingRight),l=p,o=s;f=a.offsetWidth-e-f-s-n;h=a.offsetHeight-d-h-j-p;p=d+p;s=e+s;for(var v=!0;a&&!isNaN(a.offsetLeft)&&
!isNaN(a.offsetTop);)s+=a.offsetLeft-a.scrollLeft,p+=a.offsetTop-a.scrollTop,a.currentStyle?c=a.currentStyle:window.getComputedStyle&&(c=document.defaultView.getComputedStyle(a,null)),v&&(c&&c.position=="absolute"&&(v=!1),v&&(o+=a.offsetLeft+a.scrollLeft,l+=a.offsetTop+a.scrollTop),o+=e/2,l+=d/2),a=a.offsetParent;return{top:p,left:s,width:f,height:h,deltaTop:l,deltaLeft:o,deltaBottom:j,deltaRight:n}};this.redraw=function(){this._setMapPosition()};this._setMapPosition=function(){this.size=this._calculateMapSize();
var a=this.mapParent;a.currentStyle||window.getComputedStyle&&document.defaultView.getComputedStyle(a,null);this.mapTop=this.size.top;this.mapLeft=this.size.left;this.width=this.size.width;this.height=this.size.height;relativetop=this.size.deltaTop;relativeleft=this.size.deltaLeft;this.clone.style.top=relativetop+"px";this.clone.style.left=relativeleft+"px";this.clone.style.width=this.size.width+"px";this.clone.style.height=this.size.height+"px";this.clone.style.position="absolute";this.clone.style.overflow=
"hidden";this.map.style.left=this.size.width/2+"px";this.map.style.top=this.size.height/2+"px";this._getCenter()&&this._getZoom()&&this.centerAndZoom(this._getCenter(),this._getZoom());this._copyright()};this.clearMap=function(){if(this.map){for(;this.map.firstChild;)this.map.removeChild(this.map.firstChild);for(;this.layers.length>0;)this.layers.pop();this.redraw()}};var d=function(a){return 180/Math.PI*Math.log(Math.tan(Math.PI/4+a*(Math.PI/180)/2))},e=function(a){return 180/Math.PI*(2*Math.atan(Math.exp(a*
Math.PI/180))-Math.PI/2)};this._imgLoadInfo=function(a,c){if(!this.loadInfoDiv)this.loadInfoDiv=document.createElement("div"),this.loadInfoDiv.style.position="absolute",this.loadInfoDiv.style.top="0px",this.loadInfoDiv.style.right="0px",this.loadInfoDiv.style.backgroundColor="white",this.loadInfoDiv.style.border="1px solid gray",this.loadInfoDiv.style.fontSize="10px",this.map.parentNode.appendChild(this.loadInfoDiv);if(c==0)this.loadInfoDiv.style.display="none";else{for(this.loadInfoDiv.style.display=
"";this.loadInfoDiv.firstChild;)this.loadInfoDiv.removeChild(this.loadInfoDiv.firstChild);this.loadInfoDiv.appendChild(document.createTextNode(c+" images to load"))}};this.copyrightdiv=null;this._copyright=function(){if(this.copyrightdiv==null)this.copyrightdiv=document.createElement("div"),this.mapParent.appendChild(this.copyrightdiv);for(;this.copyrightdiv.firstChild;)this.copyrightdiv.removeChild(this.copyrightdiv.firstChild);var a=document.createElement("img"),c=document.createElement("a");c.setAttribute("href",
"http://maplib.khtml.org");c.setAttribute("target","_blank");a.setAttribute("src","http://maplib.khtml.org/favicon.png");a.style.zIndex=10;a.style.border="0px solid black";a.style.position="absolute";var d=this.size.height+this.size.deltaTop-24,e=this.size.deltaLeft+0;a.style.top=d+"px";a.style.left=e+"px";a.style.width="24px";a.style.height="24px";c.appendChild(a);this.copyrightdiv.appendChild(c);a=document.createElement("a");a.appendChild(document.createTextNode("openstreetmap"));a.style.position=
"absolute";a.style.top=d+2+"px";a.style.left=e+25+"px";a.style.textDecoration="none";a.style.color="gray";a.setAttribute("href","http://www.openstreetmap.org/copyright");this.copyrightdiv.appendChild(a)};this.internetExplorer=!1;if(navigator.userAgent.indexOf("MSIE")!=-1)this.internetExplorer=!0;if(navigator.userAgent.indexOf("Android")!=-1){var f=this;setInterval(function(){f.layerTimer.reset()},300)}this.position={};this.tiles({maxzoom:18,minzoom:1,src:function(a,c,d){switch((a+c)%3){case 0:var e=
"a";break;case 1:e="b";break;case 2:e="c";break;default:e="f"}return"http://"+e+".tile.openstreetmap.org/"+d+"/"+a+"/"+c+".png"},copyright:"osm"});this.wheelSpeedConfig=[];this.wheelSpeedConfig.acceleration=2;this.wheelSpeedConfig.maxSpeed=2;this.wheelSpeedConfig.animate=!1;navigator.userAgent.indexOf("AppleWebKit")!=-1&&(this.wheelSpeedConfig.animate=!0);navigator.userAgent.indexOf("Opera")!=-1&&(this.wheelSpeedConfig.animate=!1);this.wheelSpeedConfig.animate=!1;this.wheelSpeedConfig.digizoom=!0;
this.wheelSpeedConfig.zoomAnimationSlowdown=0.02;this.wheelSpeedConfig.animationFPS=50;this.wheelSpeedConfig.moveAnimateDesktop=!0;this.wheelSpeedConfig.rectShiftAnimate=!1;this.wheelSpeedConfig.rectShiftAnimationTime=500;this.wheelSpeedConfig.animateMinSpeed=0.4;this.wheelSpeedConfig.animateMaxSpeed=200;this.wheelSpeedConfig.moveAnimationSlowdown=0.4;this.framesCounter=this.wheelEventCounter=0;this.mapParent=a;khtml.maplib.base.helpers.setCursor(this.mapParent,"grab");this.clone=a.cloneNode(!0);
this.clone=document.createElement("div");this.clone.removeAttribute("id");a.firstChild?a.insertBefore(this.clone,a.firstChild):a.appendChild(this.clone);this.map=document.createElement("div");this.map.style.position="absolute";this.clone.appendChild(this.map);this._setMapPosition();this.overlayDiv=document.createElement("div");this.overlayDiv.style.position="absolute";this.clone.appendChild(this.overlayDiv);this.overlays=[];if(khtml.maplib.overlay.FeatureCollection)this.backend="svg",this.featureCollection=
new khtml.maplib.overlay.FeatureCollection,this.featureCollection.realLayer=!0,this.featureCollection.map=this,this.addOverlay(this.featureCollection);this.distanceMeasuring="no";this.measureLine=this.moveMarker=null;this.moveAnimationMobile=!0;this.moveAnimationBlocked=this.moveAnimationDesktop=!1;this.lastMouseX=this.width/2;this.lastMouseY=this.height/2;this.layers=[];this.intZoom=this.oldVisibleZoom=this.visibleZoom=null;this.lastMoveTime=this.lastMoveY=this.lastMoveX=this.moveY=this.moveX=0;
this.zoomDeltaOld=1;this.startMoveY=this.startMoveX=0;this.sc=1;this.blocked=!1;this.tileH=this.tileW=256;this.position.zoom=1;this.movestarted=!1;this.mousedownTime=null;this.doubleclickTime=400;this.mousedownTime2=null;this.doubleclickTime2=500;this.zoomOutTime=1E3;this.zoomOutSpeed=0.01;this.zoomOutInterval=null;this.zoomOutStarted=!1;this.zoomSpeedTimer=null;this.zoomAcceleration=1;this.css3d=!1;if(navigator.userAgent.indexOf("iPhone OS")!=-1)this.css3d=!0;if(navigator.userAgent.indexOf("iPad")!=
-1)this.css3d=!1;if(navigator.userAgent.indexOf("Safari")!=-1)this.css3d=navigator.userAgent.indexOf("Mac")!=-1?!1:!0;if(navigator.userAgent.indexOf("iPhone OS")!=-1)this.css3d=!0;if(navigator.userAgent.indexOf("Android")!=-1)this.css3d=!1;if(this.internetExplorer){var h=a;navigator.userAgent.indexOf("Windows Phone OS")!=-1&&khtml.maplib.base.helpers.eventAttach(h,"mouseup",this._mouseupIE,this,!1)}else h=window;khtml.maplib.base.helpers.eventAttach(window,"resize",this._setMapPosition,this,!1);navigator.userAgent.indexOf("Konqueror")!=
-1&&(h=a);khtml.maplib.base.helpers.eventAttach(a,"touchstart",this._start,this,!1);khtml.maplib.base.helpers.eventAttach(a,"touchmove",this._move,this,!1);khtml.maplib.base.helpers.eventAttach(a,"touchend",this._end,this,!1);khtml.maplib.base.helpers.eventAttach(h,"mousemove",this._mousemove,this,!1);khtml.maplib.base.helpers.eventAttach(a,"mousedown",this._mousedown,this,!1);khtml.maplib.base.helpers.eventAttach(h,"mouseup",this._mouseup,this,!1);khtml.maplib.base.helpers.eventAttach(h,"orientationchange",
this.reSize,this,!1);khtml.maplib.base.helpers.eventAttach(a,"DOMMouseScroll",this._mousewheel,this,!1);khtml.maplib.base.helpers.eventAttach(a,"dblclick",this._doubleclick,this,!1);khtml.maplib.base.helpers.eventAttach(h,"keydown",this._shiftkeydown,this,!1);khtml.maplib.base.helpers.eventAttach(h,"keyup",this._shiftkeyup,this,!1);khtml.maplib.base.helpers.eventAttach(a,"contextmenu",function(a){a.preventDefault()},this,!1)};khtml.maplib.geometry.Bounds=function(a,c){this.enlarge=function(a){a.lng()>this.southwest.lng()&&a.lng()>this.northeast.lng()&&this.northeast.lng(a.lng());a.lng()<this.southwest.lng()&&a.lng()<this.northeast.lng()&&this.southwest.lng(a.lng());a.lat()>this.southwest.lat()&&a.lat()>this.northeast.lat()&&this.northeast.lat(a.lat());a.lat()<this.southwest.lat()&&a.lat()<this.northeast.lat()&&this.southwest.lat(a.lat())};this.sw=function(){return this.southwest};this.se=function(){return new khtml.maplib.LatLng(this.southwest.lat(),
this.northeast.lng())};this.ne=function(){return this.northeast};this.nw=function(){return new khtml.maplib.LatLng(this.northeast.lat(),this.southwest.lng())};this.getCenter=function(){return this.center};this.getOpticalCenter=function(a){var c=a.latlngToXY(this.southwest),d=a.latlngToXY(this.northeast);return a.XYTolatlng(Math.abs(c.x+d.x)/2,Math.abs(c.y+d.y)/2)};this.getZoomLevel=function(a){origZoom=a.getZoom();var c=a.latlngToXY(this.southwest),d=a.latlngToXY(this.northeast),b=a.width/Math.abs(c.x-
d.x);a=a.height/Math.abs(c.y-d.y);if(b>a)var k=a;b<=a&&(k=b);return origZoom+Math.log(k)/Math.log(2)};this.getDistance=function(){return this.distance(this.southwest.lat(),this.southwest.lng(),this.northeast.lat(),this.northeast.lng())};this.getInnerRadius=function(){var a=this.distance(this.center.lat(),this.southwest.lng(),this.center.lat(),this.northeast.lng()),c=this.distance(this.southwest.lat(),this.center.lng(),this.northeast.lat(),this.center.lng());return a>c?c/2:a/2};this.distance=function(a,
c,d,b){a=a*Math.PI/180;d=d*Math.PI/180;return Math.acos(Math.sin(a)*Math.sin(d)+Math.cos(a)*Math.cos(d)*Math.cos(b*Math.PI/180-c*Math.PI/180))*180/Math.PI/360*4E7};this.intersects=function(a){if(!(a instanceof khtml.maplib.geometry.Bounds))return khtml.maplib.base.Log.warn('Bounds.intersects(): Illegal argument. Has to be "khtml.maplib.geometry.Bounds"!'),!1;var c=Math.min(this.sw().lat(),this.ne().lat()),d=Math.max(this.sw().lat(),this.ne().lat()),b=Math.min(this.sw().lng(),this.ne().lng()),k=Math.max(this.sw().lng(),
this.ne().lng()),g=[];g.push(a.ne());g.push(a.se());g.push(a.sw());g.push(a.nw());for(a=0;a<g.length;a++){var B=g[a],F=B.lat()>=c&&B.lat()<=d;B=B.lng()>=b&&B.lng()<=k;if(F&&B)return!0}return!1};this.createBoundsFrom2Points=function(a,c){var d=new khtml.maplib.LatLng(Math.min(a.lat(),c.lat()),Math.min(a.lng(),c.lng())),b=new khtml.maplib.LatLng(Math.max(a.lat(),c.lat()),Math.max(a.lng(),c.lng()));return{sw:d,ne:b}};var d=this.createBoundsFrom2Points(a,c);this.southwest=d.sw;this.northeast=d.ne;this.center=
new khtml.maplib.LatLng((this.southwest.lat()+this.northeast.lat())/2,(this.southwest.lng()+this.northeast.lng())/2)};khtml.maplib.geometry.LatLng=function(a,c){this.callbackFunctions=[];this.addCallbackFunction=function(a){typeof a=="function"&&this.callbackFunctions.push(a)};this._executeCallbackFunctions=function(){for(var a=0;a<this.callbackFunctions.length;a++)this.callbackFunctions[a].call(this)};this.lat=function(a){if(typeof a=="number")this.latitude=a,this._executeCallbackFunctions();if(typeof a=="string")this.latitude=parseFloat(a),this._executeCallbackFunctions();return this.latitude};this.lng=function(a){if(typeof a==
"number")this.longitude=a,this._executeCallbackFunctions();if(typeof a=="string")this.longitude=parseFloat(a),this._executeCallbackFunctions();return this.longitude};this.equals=function(a){if(null==a)return!1;if(!(a instanceof khtml.maplib.LatLng))return khtml.maplib.base.Log.warn("Point.equals(): Error - illegal argument!",a),!1;return a.lat()===this.lat()&&a.lng()===this.lng()};a instanceof khtml.maplib.geometry.LatLng?(this.lat(a.lat()),this.lng(a.lng())):typeof a=="object"?(a.lat&&this.lat(a.lat),
a.lng&&this.lng(a.lng)):(this.lat(a),this.lng(c))};khtml.maplib.ui.KeyBoard=function(){this.zoomtime=400;this.init=function(a){this.map=a;khtml.maplib.base.helpers.eventAttach(a.mapParent,"keydown",this.keydown,this,!1)};this.keydown=function(a){switch(a.keyCode){case 37:this.moveit(30,0);break;case 38:this.moveit(0,30);break;case 39:this.moveit(-30,0);break;case 40:this.moveit(0,-30);break;case 35:this.moveit(this.map.size.width*0.4,0);break;case 36:this.moveit(-this.map.size.width*0.4,0);break;case 33:this.moveit(0,this.map.size.height*0.4);break;
case 34:this.moveit(0,-this.map.size.height*0.4);break;case 187:case 61:case 43:this.zoomin();break;case 189:case 190:case 109:case 45:this.zoomout();break;default:return}a.preventDefault?a.preventDefault():a.returnValue=!1};this.render=function(){};this.zoomingIn=!1;this.zoomin=function(){var a=Math.ceil(this.map.zoom()+0.1);this.zoomingIn&&a++;this.map.animatedGoto(this.map.center(),a,this.zoomtime);var c=this;setTimeout(function(){c.zoomingIn=!1},this.zoomtime);this.zoomingIn=!0};this.zoomout=
function(){var a=Math.floor(this.map.zoom()-0.1);this.zoomingOut&&a--;this.map.animatedGoto(this.map.center(),a,this.zoomtime);var c=this;setTimeout(function(){c.zoomingOut=!1},this.zoomtime);this.zoomingOut=!0};this.keyup=function(){};this.moveit=function(a,c){for(var d=a/20,e=c/20,f=0;f<20;f++){var h=Math.cos(3*(-10+f)/20)*5;this.moveitexec(d*h,e*h,f)}};this.moveitexec=function(a,c,d){setTimeout(function(){this.map.moveXY(a,c)},20*d)}};
