// --------------------------------------------------------------------------------------------
// khtml javascript library
// --------------------------------------------------------------------------------------------
// (C) Copyright 2010-2011 by Bernhard Zwischenbrugger, Florian Hengartner, Stefan Kemper
//
// Project Info:  http://www.khtml.org
//				  http://www.khtml.org/iphonemap/help.php
//
// This library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with this library.  If not, see <http://www.gnu.org/licenses/>.
// --------------------------------------------------------------------------------------------
var khtml={};khtml.maplib={};khtml.maplib.base={};khtml.maplib.geometry={};khtml.maplib.overlay={};khtml.maplib.overlay.renderer={};khtml.maplib.parser={};khtml.maplib.ui={};khtml.maplib.util={};khtml.maplib.overlay.renderer={};khtml.maplib.version=function(){return"khtmlib_hsr v0.02"};khtml.maplib.Map=function(a){return new khtml.maplib.base.Map(a)};khtml.maplib.LatLng=function(a,e){return new khtml.maplib.geometry.LatLng(a,e)};khtml.maplib.base.helpers={};khtml.maplib.base.helpers.parseXml=function(a){var e;window.ActiveXObject?(e=new ActiveXObject("Microsoft.XMLDOM"),e.async=!1,e.loadXML(a)):document.implementation&&document.implementation.createDocument&&(e=(new DOMParser).parseFromString(a,"text/xml"));return e};
khtml.maplib.base.helpers.contains=function(a,e){var d=[a.sw().lat(),a.ne().lat()],b=[a.sw().lng(),a.ne().lng()];return(khtml.maplib.base.helpers.between(d,e.sw().lat())||khtml.maplib.base.helpers.between(d,e.ne().lat()))&&(khtml.maplib.base.helpers.between(b,e.sw().lng())||khtml.maplib.base.helpers.between(b,e.ne().lng()))?!0:!1};khtml.maplib.base.helpers.overlaps=function(a,e){return a.sw().lng()<e.ne().lng()&&a.ne().lng()>e.sw().lng()&&a.se().lat()<e.ne().lat()&&a.ne().lat()>e.sw().lat()?!0:!1};
khtml.maplib.base.helpers.overlapsBuggy=function(a,e){var d=[a.sw().lat(),a.ne().lat()],b=[a.sw().lng(),a.ne().lng()],g=[e.sw().lat(),e.ne().lat()],f=[e.sw().lng(),e.ne().lng()];return(khtml.maplib.base.helpers.between(d,e.sw().lat())||khtml.maplib.base.helpers.between(d,e.ne().lat()))&&(khtml.maplib.base.helpers.between(b,e.sw().lng())||khtml.maplib.base.helpers.between(b,e.ne().lng()))||(khtml.maplib.base.helpers.between(g,a.sw().lat())||khtml.maplib.base.helpers.between(g,a.ne().lat()))&&(khtml.maplib.base.helpers.between(f,
a.sw().lng())||khtml.maplib.base.helpers.between(f,a.ne().lng()))?!0:!1};
khtml.maplib.base.helpers.extendBBox=function(a,e){if(!(a instanceof khtml.maplib.geometry.Bounds)){var d=new khtml.maplib.geometry.LatLng(-90,-180),b=new khtml.maplib.geometry.LatLng(90,180);a=new khtml.maplib.geometry.Bounds(b,d)}if(!e)return a;e instanceof khtml.maplib.geometry.LatLng?a=khtml.maplib.base.helpers.extendBBoxByPoint(a,e):(a=khtml.maplib.base.helpers.extendBBoxByPoint(a,e.sw()),a=khtml.maplib.base.helpers.extendBBoxByPoint(a,e.ne()));return a};
khtml.maplib.base.helpers.extendBBoxByPoint=function(a,e){var d=a.sw().lng(),b=a.ne().lat(),g=a.sw().lat(),f=a.ne().lng();e.lat()>b&&(b=e.lat());e.lat()<g&&(g=e.lat());e.lng()<d&&(d=e.lng());e.lng()>f&&(f=e.lng());d=new khtml.maplib.geometry.LatLng(g,d);b=new khtml.maplib.geometry.LatLng(b,f);return new khtml.maplib.geometry.Bounds(d,b)};khtml.maplib.base.helpers.between=function(a,e){return a[0]<=e&&e<=a[1]?!0:!1};
khtml.maplib.base.helpers.cloneObject=function(a){var e={},d;for(d in a)e[d]=typeof a[d]=="object"?cloneObject(a[d]):a[d];return e};khtml.maplib.base.helpers.convertObjectToArray=function(a){for(var e=[],d=0,b=a.length;d<b;d++)e.push(a[d]);return e};
khtml.maplib.base.helpers.eventAttach=function(a,e,d,b,g){var f=arguments.length>5?$a(arguments).slice(5,arguments.length):[],c=function(c){f.unshift(c||window.event);return d.apply(b?b:a,f)};a.addEventListener?(navigator.appName.indexOf("Netscape")==-1&&e=="DOMMouseScroll"&&(e="mousewheel"),navigator.userAgent.indexOf("Safari")!=-1?e=="DOMMouseScroll"?a.onmousewheel=c:a.addEventListener(e,c,g):a.addEventListener(e,c,g)):(e=e=="DOMMouseScroll"?"onmousewheel":"on"+e,a.attachEvent(e,c));return{o:a,
type:e,fn:c,c:g}};khtml.maplib.base.helpers.eventRemove=function(a){a.o.removeEventListener&&a.o.removeEventListener(a.type,a.fn,a.c)};khtml.maplib.base.helpers.mixin=function(a,e,d){if(d)if(d instanceof Array)for(var b=0;b<d.length;b++)a[d[b]]=e[d[b]];else e[d]&&(a[d]=e[d]);else for(b in e)a[b]=e[b]};
khtml.maplib.base.helpers.showOnMap=function(a,e){var d=[];a instanceof khtml.maplib.geometry.Bounds&&(khtml.maplib.base.Log.log("Bounds"),khtml.maplib.base.Log.log("Northwest / Topleft",a.nw()),khtml.maplib.base.Log.log("Northeast / Topright",a.ne()),khtml.maplib.base.Log.log("Southeast / Bottomright",a.se()),khtml.maplib.base.Log.log("Southwest / Bottomleft",a.sw()),d.push(a.nw()),d.push(a.ne()),d.push(a.se()),d.push(a.sw()));for(var b=0;b<d.length;b++){var g=document.createElement("div");g.style.width=
"1px";g.style.height="1px";g.style.color="red";g.style["font-size"]="2em";g.textContent="X";g=new khtml.maplib.overlay.Marker(d[b],g);e.addOverlay(g)}};khtml.maplib.base.helpers.cancelEvent=function(a){a.cancelBubble=!0;a.stopPropagation&&a.stopPropagation()};khtml.maplib.base.helpers.stopEventPropagation=function(a){a.preventDefault?a.preventDefault():a.returnValue=!1};khtml.maplib.base.helpers.isIE=function(){return navigator.userAgent.indexOf("MSIE")!=-1};
khtml.maplib.base.helpers.isParentNodeEmpty=function(a){if(khtml.maplib.base.helpers.isIE())return a.parentNode.nodeValue==null;return!a.parentNode};
khtml.maplib.base.helpers.parseLine=function(a){if(a){if(typeof a=="string")a=khtml.maplib.base.helpers.parseLineString;if(typeof a=="object"){for(var e in a){var d=a[e];if(!(d instanceof khtml.maplib.geometry.LatLng)){var b=d[1],g=d[0];a[e]=typeof b=="number"&&typeof g=="number"&&d.length==2?new khtml.maplib.LatLng(b,g):khtml.maplib.base.helpers.parseLine(a[e])}}typeof a[0]=="number"&&typeof a[0]=="number"&&a.length==2&&(a=new khtml.maplib.LatLng(a[0],a[1]));d=a}}else d=[];return d};
khtml.maplib.base.helpers.parseLineString=function(a){if(typeof a=="string"){points=[];a=a.split(" ");for(var e=0;e<a.length;e++){var d=a[e].split(",");d.length==2&&(d[0]=parseFloat(d[0]),d[1]=parseFloat(d[1]),points.push(new khtml.maplib.LatLng(d[0],d[1])))}}return points};
khtml.maplib.base.helpers.parseMultiLine=function(a){if(a&&typeof a=="object")for(var e in a){var d=a[e],b;for(b in d){var g=d[b];if(!(g instanceof khtml.maplib.geometry.LatLng)){var f=g[0];g=g[1];typeof f=="number"&&typeof g=="number"&&(d[b]=new khtml.maplib.LatLng(f,g))}}}else a=[];return a};var stop=0;
khtml.maplib.base.helpers.stringify=function(a,e,d){var b=!0;typeof a.push=="undefined"&&(b=!1);for(var g="",f=e?e+1:e===!1?!1:1,c=g="",k=0;k<f-1;k++)c+="   ";e!==!1&&(c="\n"+c,g=c+"   ");e="";for(var h in a)if(h!="owner"&&typeof a[h]!="function")if(a[h]instanceof khtml.maplib.geometry.Bounds)e+=g+'"bbox":',e+="["+a[h].sw().lng()+","+a[h].sw().lat()+",",e+=""+a[h].ne().lng()+","+a[h].ne().lat()+"]",e+=",";else if(a[h]instanceof khtml.maplib.geometry.LatLng)a.type!="Marker"&&(a.type=="Point"&&(e+=
'"coordinates":'),e+="["+a[h].lng()+","+a[h].lat()+"],");else if(typeof a[h]=="string"){if((h=="type"||d)&&h!="animVal")a[h]!="Marker"&&(e+=g+'"'+h+'":"'+a[h]+'",')}else if(b||h=="type"||h=="features"||a[h]&&a[h].type=="Feature"||h=="geometry"||h=="coordinates"||h=="properties"||h=="bbox"||h=="className")e+=b?g+khtml.maplib.base.helpers.stringify(a[h],f)+",":h=="properties"?g+'"'+h+'":'+khtml.maplib.base.helpers.stringify(a[h],f)+",":g+'"'+h+'":'+khtml.maplib.base.helpers.stringify(a[h],f,!0)+",";
e=e.substring(0,e.length-1);return b?"["+e+"]":"{"+e+c+"}"};khtml.maplib.base.helpers.rotate=function(a,e){var d="rotate("+e+"deg)";a.style.webkitTransform=d;a.style.MozTransform=d;a.style.OTransform=d;if(document.all)rad=e*(Math.PI*2/360),costheta=Math.cos(rad),sintheta=Math.sin(rad),a.filters.item(0).M11=costheta,a.filters.item(0).M12=-sintheta,a.filters.item(0).M21=sintheta,a.filters.item(0).M22=costheta};
khtml.maplib.base.helpers.Boundingbox=function(a){this.map=a;this.div=document.createElement("div");this.div.style.border="1px solid black";this.div.style.position="absolute";this.div.style.strokeDasharray="4,4";this.div.style.zIndex=1;a.mapParent.appendChild(this.div);this.show=function(a){this.div.style.display="";var d=this.map.latlngToXY(a.sw());a=this.map.latlngToXY(a.ne());this.div.style.top=a.y-parseInt(this.div.style.borderWidth)+"px";this.div.style.left=d.x-parseInt(this.div.style.borderWidth)+
"px";this.div.style.width=a.x-d.x+"px";this.div.style.height=-a.y+d.y+"px";this.div.zIndex=10};this.hide=function(){this.div.style.display="none"}};khtml.maplib.base.Map=function(a){typeof a=="string"&&(a=document.getElementById(a));(typeof a!="object"||null==a)&&console.log("Error: map is null or not an object. (map: "+a+")");this.addOverlay=function(c){if(null==c||c instanceof Array)return khtml.maplib.base.Log.warn('Map.addOverlay(): Illegal argument (was "null" or "Array")'),!1;this.overlays.push(c);typeof c.init=="function"&&c.init(this);this.renderOverlay(c)};this.addOverlays=function(c){if(c instanceof Array)for(var b=0;b<c.length;b++)this.addOverlay(c[b]);
else this.addOverlay(c)};this.renderOverlay=function(c){try{c.render()}catch(b){}};this.renderOverlays=function(){for(obj in this.overlays)this.overlays[obj].render()};this.hideOverlays=function(){for(obj in this.overlays)try{this.overlays[obj].clear(g)}catch(c){}};this.removeOverlays=function(){for(;this.overlays.length>0;)this.overlays.pop().clear()};this.stopRenderOverlays=function(){for(obj in this.overlays)typeof this.overlays[obj].cancel=="function"&&this.overlays[obj].cancel()};this.removeOverlay=
function(c){for(var b=0;b<this.overlays.length;b++)if(c==this.overlays[b]){c.clear();this.overlays.splice(b,1);break}};this.callbackFunctions=[];this.addCallbackFunction=function(c){typeof c=="function"&&this.callbackFunctions.push(c)};this._executeCallbackFunctions=function(){for(var c=0;c<this.callbackFunctions.length;c++)this.callbackFunctions[c].call(this)};this.myTimer=function(c){this.reset=function(){this._isRunning=!1};this.isTimeRunning=function(){if(!1==this._isRunning)return!1;if(this.time+
this.myInterval>(new Date).getTime())return!1;this._isRunning=!1;return!0};this.start=function(){this._isRunning=!0;this.time=(new Date).getTime()};this.interval=function(c){if(typeof c!="undefined")this.myInterval=parseInt(c);return this.myInterval};this.reset();this.interval(c);return this};this.oldMoveY=this.oldMoveX=0;this.start=function(c){c.preventDefault?c.preventDefault():c.returnValue=!1;this.moveAnimationBlocked=!0;if(c.touches.length==1){this.startMoveX=this.moveX-c.touches[0].pageX/this.faktor/
this.sc;this.startMoveY=this.moveY-c.touches[0].pageY/this.faktor/this.sc;if(this.mousedownTime!=null&&(new Date).getTime()-this.mousedownTime<this.doubleclickTime){var b=Math.ceil(0.01+this.getZoom()-this.intZoom);this._autoZoomIn(c.touches[0].pageX,c.touches[0].pageY,b)}this.mousedownTime=(new Date).getTime();clearTimeout(this.zoomOutInterval);this.zoomOutInterval=window.setInterval(function(){},20)}if(c.touches.length==2){window.clearInterval(this.zoomOutInterval);this.moveok=!1;b=c.touches[0].pageX;
var d=c.touches[0].pageY,a=c.touches[1].pageX;c=c.touches[1].pageY;this.startDistance=Math.sqrt(Math.pow(a-b,2)+Math.pow(c-d,2));this.startZZ=this.position.zoom;c=(d+c)/2/this.faktor/this.sc;this.startMoveX=this.moveX-(b+a)/2/this.faktor/this.sc;this.startMoveY=this.moveY-c}this.oldMoveX=this.moveX;this.oldMoveY=this.moveY};this.moveok=!0;this.move=function(c){c.preventDefault?c.preventDefault():c.returnValue=!1;if(c.touches.length==1&&this.moveok){this.lastMoveX=this.moveX;this.lastMoveY=this.moveY;
this.lastMoveTime=new Date(c.timeStamp);this.moveX=c.touches[0].pageX/this.faktor/this.sc+this.startMoveX;this.moveY=c.touches[0].pageY/this.faktor/this.sc+this.startMoveY;if(!this.zoomOutStarted){if(Math.abs(this.moveX-this.oldMoveX)>5||Math.abs(this.moveY-this.oldMoveY)>5)window.clearInterval(this.zoomOutInterval),this.zoomOutSpeed=0.01,this.mousedownTime=null;var b=new khtml.maplib.LatLng(this.lat,this.lng);this.setCenter2(b,this.position.zoom);this.moveAnimationBlocked=!1}if(Math.abs(this.moveX-
this.oldMoveX)>5||Math.abs(this.moveY-this.oldMoveY)>5)this.mousedownTime=null}if(c.touches.length==2){this.mousedownTime=null;var d=c.touches[0].pageX,a=c.touches[0].pageY,e=c.touches[1].pageX,g=c.touches[1].pageY;b=Math.sqrt(Math.pow(e-d,2)+Math.pow(g-a,2))/this.startDistance;c=this.startZZ+b-1;c<1&&(c=1);if(c>this.tileSource.maxzoom)c=this.tileSource.maxzoom,b=1;d=(d+e)/2;a=(a+g)/2;faktor=Math.pow(2,c);e=d/faktor-this.width/2;g=a/faktor-this.height/2;b=Math.pow(2,b-1);this.moveX=(d+(e-e*b))/faktor+
this.startMoveX;this.moveY=(a+(g-g*b))/faktor+this.startMoveY;b=new khtml.maplib.LatLng(this.lat,this.lng);this.setCenter2(b,c)}};this.end=function(c){c.preventDefault?c.preventDefault():c.returnValue=!1;window.clearInterval(this.zoomOutInterval);this.zoomOutStarted=!1;this.zoomOutSpeed=0.01;if(c.touches.length==0&&(this.moveok=!0,this.moveAnimationMobile&&this.moveAnimationBlocked==!1)){var b=new Date(c.timeStamp)-this.lastMoveTime;c=(this.lastMoveX-this.moveX)/b*4;b=(this.lastMoveY-this.moveY)/
b*4;var d=this.wheelSpeedConfig.animateMaxSpeed;c>d&&(c=d);b>d&&(b=d);c<-d&&(c=-d);b<-d&&(b=-d);d=Math.pow(2,this.zoom());(Math.abs(c)>this.wheelSpeedConfig.animateMinSpeed/d||Math.abs(b)>this.wheelSpeedConfig.animateMinSpeed/d)&&this._animateMove(c,b,d)}};this.pageX=function(c){try{return(c.pageX===void 0?c.clientX+document.body.scrollLeft:c.pageX)-this.mapLeft}catch(b){return this.lastMouseX}};this.pageY=function(c){try{return(c.pageY===void 0?c.clientY+document.body.scrollTop:c.pageY)-this.mapTop}catch(b){return this.lastMouseY}};
this.doubleclickBlocked=!1;this.doubleclick=function(c){this.discretZoom(1,this.pageX(c),this.pageY(c))};this.mousedown=function(c){this.mapParent.focus();c.preventDefault?c.preventDefault():window.event.returnValue=!1;this.lastMouseX=this.pageX(c);this.lastMouseY=this.pageY(c);this.moveAnimationBlocked=!0;if(this.mousedownTime2!=null&&(new Date).getTime()-this.mousedownTime2<this.doubleclickTime2)this.doubleclick(c);else{this.mousedownTime2=(new Date).getTime();if(c.shiftKey){this.selectRectLeft=
this.pageX(c);this.selectRectTop=this.pageY(c);this.selectRect=document.createElement("div");this.selectRect.style.left=this.selectRectLeft+"px";this.selectRect.style.top=this.selectRectTop+"px";this.selectRect.style.border="1px solid gray";if(!this.internetExplorer)this.selectRect.style.opacity=0.5,this.selectRect.style.backgroundColor="white";this.selectRect.style.position="absolute";this.map.parentNode.appendChild(this.selectRect)}else this.startMoveX=this.moveX-this.pageX(c)/this.faktor/this.sc,
this.startMoveY=this.moveY-this.pageY(c)/this.faktor/this.sc,this.movestarted=!0;return!1}};this.mousemove=function(c){c.preventDefault?c.preventDefault():window.event.returnValue=!1;this.lastMouseX=this.pageX(c);this.lastMouseY=this.pageY(c);if(c.shiftKey){if(this.selectRect){this.selectRect.style.width=Math.abs(this.pageX(c)-this.selectRectLeft)+"px";this.selectRect.style.height=Math.abs(this.pageY(c)-this.selectRectTop)+"px";if(this.pageX(c)<this.selectRectLeft)this.selectRect.style.left=this.pageX(c);
if(this.pageY(c)<this.selectRectTop)this.selectRect.style.top=this.pageY(c)}}else if(this.movestarted)this.lastMoveX=this.moveX,this.lastMoveY=this.moveY,this.lastMoveTime=new Date(c.timeStamp),this.moveX=this.pageX(c)/this.faktor/this.sc+this.startMoveX,this.moveY=this.pageY(c)/this.faktor/this.sc+this.startMoveY,this.setCenter2(new khtml.maplib.LatLng(this.lat,this.lng),this.position.zoom),this.moveAnimationBlocked=!1;return!1};this.mouseup=function(c){c.preventDefault?c.preventDefault():c.returnValue=
!1;this.lastMouseX=this.pageX(c);this.lastMouseY=this.pageY(c);if(this.moveMarker)this.moveMarker=null;if(this.selectRect){var b=this.XYTolatlng(this.selectRect.offsetLeft,this.selectRect.offsetTop+this.selectRect.offsetHeight),d=this.XYTolatlng(this.selectRect.offsetLeft+this.selectRect.offsetWidth,this.selectRect.offsetTop);this._setBounds(new khtml.maplib.geometry.Bounds(b,d));this.selectRect.parentNode.removeChild(this.selectRect);this.selectRect=null}b=new Date(c.timeStamp)-this.lastMoveTime;
if(this.wheelSpeedConfig.moveAnimateDesktop&&b!=0&&this.movestarted&&this.moveAnimationBlocked==!1)c=(this.lastMoveX-this.moveX)/b,b=(this.lastMoveY-this.moveY)/b,d=this.wheelSpeedConfig.animateMaxSpeed,c>d&&(c=d),b>d&&(b=d),c<-d&&(c=-d),b<-d&&(b=-d),d=Math.pow(2,this.zoom()),(Math.abs(c)>this.wheelSpeedConfig.animateMinSpeed/d||Math.abs(b)>this.wheelSpeedConfig.animateMinSpeed/d)&&this._animateMove(c,b,d);var a=this;setTimeout(function(){a.movestarted=!1},1)};this.mouseupIE=function(c){c.preventDefault?
c.preventDefault():c.returnValue=!1;this.lastMouseX=this.pageX(c);this.lastMouseY=this.pageY(c);this.setCenter2(this.XYTolatlng(this.lastMouseX,this.lastMouseY),this.zoom())};this.startZoomTime=null;this.mousewheel=function(c){c.preventDefault?c.preventDefault():c.returnValue=!1;this.mapParent.focus();if(!c)c=window.event;if(c.wheelDelta)var b=c.wheelDelta/60;else if(c.detail)b=-c.detail/3,this.lastWheelDelta*b<0&&(this.wheelSpeedConfig.digizoom||(b=0)),this.lastWheelDelta=-c.detail/3;b=b<0?-1:1;
if(this.wheelSpeedConfig.digizoom)this.discretZoom(b,this.pageX(c),this.pageY(c));else{if(!this.startZoomTime)this.startZoomTime=new Date,this.startZoomTime2=new Date,this.oldZoom=this.zoom(),this.speed=1;var d=new Date-this.startZoomTime,a=new Date-this.startZoomTime2;this.startZoomTime=new Date;if(d>300)this.startZoomTime2=new Date,this.oldZoom=this.zoom(),this.speed=1,a=0.1;this.speed*=2;if(this.speed>5)this.speed=5;b=this.oldZoom+a/3E3*this.speed*b;if(b>this.position.maxZoom)b=this.position.maxZoom;
if(b<this.position.minZoom)b=this.position.minZoom;this.centerAndZoomXY(this.center(),b,this.pageX(c),this.pageY(c))}};this.zoomTimeouts=[];this.discretZoomBlocked=!1;this.discretZoom=function(c,b,d){if(!this.discretZoomBlocked){var a=this;this.discretZoomBlockedTimeout=setTimeout(function(){a.discretZoomBlocked=!1},200);this.discretZoomBlocked=!0;for(var e=1;e<=20;e++)this.zoomTimeouts[e]&&clearTimeout(this.zoomTimeouts[e]);e=this.zoom();var g=c==1?Math.ceil(this.zoom()+0.9):Math.floor(this.zoom()-
0.9);g=Math.abs(e-g);var f=0;for(e=1;e<=20;e++){var o=c*Math.sin(e/20*Math.PI/2)*g;this.zoomTimeouts[e]=this._discretZoomExec(b,d,o-f,e,20);f=o}}};this._discretZoomExec=function(c,b,d,a,e){var g=this;return setTimeout(function(){var f=g.zoom()+d;a==e&&(f=Math.round(f));g.centerAndZoomXY(g.center(),f,c,b)},a*20)};this.digizoomblocked=!1;this.digizoomblockedTimeout=null;this.digizoom=function(c,b,d){this.digizoomblockedTimeout&&clearTimeout(this.digizoomblockedTimeout);var a=this;if(!this.digizoomblocked)this.digizoomblockedTimeout=
setTimeout(function(){a.digizoomblocked=!1},2E3),this.digizoomblocked=!0,d=d>0?Math.ceil(0.01+this.getZoom()-this.getIntZoom()):Math.ceil(this.getZoom()-this.getIntZoom())-0.98,this._autoZoomIn(c,b,d)};this.wheelZoomTimeout=null;this._animateMove=function(c,b,d){clearTimeout(this.animateMoveTimeout);if(!(Math.abs(c)<this.wheelSpeedConfig.animateMinSpeed/d&&Math.abs(b)<this.wheelSpeedConfig.animateMinSpeed/d)){this.moveX+=-c;this.moveY+=-b;var a=this,e=Math.sqrt(Math.pow(c,2)+Math.pow(b,2)),g=c/e,
f=b/e;this.animateMoveTimeout=window.setTimeout(function(){a._animateMove(c-g*a.wheelSpeedConfig.moveAnimationSlowdown/d,b-f*a.wheelSpeedConfig.moveAnimationSlowdown/d,d)},20);this.setCenter2(this.position.center,this.position.zoom)}};this.autoZoomStartTime=this.autoZoomInTimeout=null;this._autoZoomIn=function(c,b,d){this.autoZoomInTimeout&&window.clearTimeout(this.autoZoomInTimeout);var a=0.2;d<0&&(a=-a);zoomGap=!1;Math.abs(d)<=Math.abs(a)&&(zoomGap=!0);var e=this.position.zoom+a;e=Math.round(e*
1E3)/1E3;zoomGap&&(e=d<0?Math.floor(e):Math.ceil(e-0.2),a=e-this.position.zoom);faktor=Math.pow(2,e);var g=c-this.width/2,f=b-this.height/2,o=Math.pow(2,a);g-=g*o;f-=f*o;var y=this;o=(new Date).getMilliseconds();var v=this.autoZoomStartTime?o-this.autoZoomStartTime:0;this.autoZoomStartTime=o;if(v<100||zoomGap){e>=this.tileSource.minzoom&&e<=this.tileSource.maxzoom&&(this.moveX+=g/faktor,this.moveY+=f/faktor);var t=new khtml.maplib.LatLng(this.lat,this.lng);if(e>this.tileSource.maxzoom)e=this.tileSource.maxzoom;
if(e<this.tileSource.minzoom)e=this.tileSource.minzoom;setTimeout(function(){y.setCenter2(t,e)},1)}var w=d-a;zoomGap?this.digizoomblocked=!1:this.autoZoomInTimeout=window.setTimeout(function(){y._autoZoomIn(c,b,w)},40)};this.centerAndZoomXY=function(c,b,d,a){faktor=Math.pow(2,b);c=d-this.mapsize.width/2;a-=this.mapsize.height/2;d=b-this.zoom();d=Math.pow(2,d);c-=c*d;a-=a*d;b>=this.tileSource.minzoom&&b<=this.tileSource.maxzoom&&(this.moveX+=c/faktor,this.moveY+=a/faktor);c=new khtml.maplib.LatLng(this.lat,
this.lng);if(b>this.tileSource.maxzoom)b=this.tileSource.maxzoom;if(b<this.tileSource.minzoom)b=this.tileSource.minzoom;this.setCenter2(c,b)};this.centerAndZoom=function(c,b){this.moveY=this.moveX=0;if(b>this.tileSource.maxzoom)b=this.tileSource.maxzoom;if(b<this.tileSource.minzoom)b=this.tileSource.minzoom;this.record();this.setCenterNoLog(c,b)};this.setCenter3=function(c,b){this.moveY=this.moveX=0;this.setCenterNoLog(c,b)};this.setCenter2=function(c,b){this.record();this.setCenterNoLog(c,b)};this.setCenterNoLogCount=
0;this.setCenterNoLog=function(c,b){this.position.center=c;this.lat=c.lat();this.lng=c.lng();b=parseFloat(b);if(b>this.tileSource.maxzoom)b=this.tileSource.maxzoom;if(b<this.tileSource.minzoom)b=this.tileSource.minzoom;this.position.center=c;this.position.zoom=b;this.layer(this.map,this.lat,this.lng,this.moveX,this.moveY,b);this._executeCallbackFunctions();this._getBounds()};this.center=function(c){typeof c!="undefined"&&this.centerAndZoom(c,this.getZoom());if(this.moveX!=0||this.moveY!=0)return c=
new khtml.maplib.LatLng(this.movedLat,this.movedLng);return this.position.center};this.zoom=function(c){typeof c!="undefined"&&this.centerAndZoom(this.position.center,c);return this.position.zoom};this.moveXY=function(c,b){this.moveX=parseFloat(c)/this.faktor/this.sc+this.moveDelayedX;this.moveY=parseFloat(b)/this.faktor/this.sc+this.moveDelayedY;this.setCenter2(this.center(),this.zoom())};this.tiles=function(c){this.clearMap();this.tileSource=c};this.tileOverlays=[];this.addTilesOverlay=function(c){this.tileOverlays.push(c);
c=this.tileOverlays[this.tileOverlays.length-1];this.clearMap();return c};this.removeTilesOverlay=function(c){for(var b=0;b<this.tileOverlays.length;b++)if(c==this.tileOverlays[b]){this.tileOverlays.splice(b,1);break}this.clearMap()};this._getCenter=function(){if(this.moveX!=0||this.moveY!=0)var c=new khtml.maplib.LatLng(this.movedLat,this.movedLng);else if(this.position.center)c=this.position.center;return c};this.bounds=function(c){if(typeof c!="undefined")this._setBounds(c);else return this.mapBounds};
this.mapBounds=null;this._getBounds=function(){var c=this.XYTolatlng(0,this.height),b=this.XYTolatlng(this.width,0);this.mapBounds=new khtml.maplib.geometry.Bounds(c,b)};this._setBounds=function(c){if(typeof khtml.maplib.geometry.Bounds=="undefined"||!(c instanceof khtml.maplib.geometry.Bounds))return!1;var a=c.sw();c=c.ne();var e=a.lat(),g=c.lat();a=a.lng();c=c.lng();e=d(e);var f=d(g);g=(a+c)/2;var m=b((e+f)/2);g=new khtml.maplib.LatLng(m,g);e=Math.abs(f-e);a=Math.abs(c-a);a/this.width>e/this.height?
c=this.width:(a=e,c=this.height);a=Math.log(360/a/(512/c))/Math.log(2)+1;if(a>this.tileSource.maxzoom)a=this.tileSource.maxzoom;if(a<this.tileSource.minzoom)a=this.tileSource.minzoom;this.position.center?this.wheelSpeedConfig.rectShiftAnimate?this.animatedGoto(g,a,this.wheelSpeedConfig.rectShiftAnimationTime):this.centerAndZoom(g,a):this.centerAndZoom(g,a)};this.animatedGotoStep=null;this.animatedGotoTimeout=[];this.animatedGoto=function(c,b,d){d/=10;var a=this._getCenter(),e=c.lat();c=c.lng();var g=
a.lat(),f=a.lng(),o=this.getZoom(),y=(e-g)/d,v=(c-f)/d,t=(b-o)/d,w=this.moveX/d,C=this.moveY/d,I=this.moveX,x=this.moveY;this.animatedGotoStep=0;for(var A=this;timeout=this.animatedGotoTimeout.pop();)clearTimeout(timeout);for(b=0;b<d;b++)this.animatedGotoTimeout[b]=window.setTimeout(function(){A._animatedGotoExec(g,f,o,y,v,t,I,x,w,C)},10*b)};this._animatedGotoExec=function(c,b,d,a,e,g,f,o,y,v){this.moveX=-y;this.moveY=-v;c+=a*this.animatedGotoStep;b+=e*this.animatedGotoStep;d+=g*this.animatedGotoStep;
this.animatedGotoStep++;this.centerAndZoom(new khtml.maplib.LatLng(c,b),d)};this.getZoom=function(){return this.position.zoom};this.getIntZoom=function(){return this.intZoom};this.latlngToXY=function(c){var b=c.lat(),d=c.lng();b>90&&(b-=180);b<-90&&(b+=180);c=this.getIntZoom();tileTest=e(b,d,c);b=this._getCenter();c=e(b.lat(),b.lng(),c);b=(c[0]-tileTest[0])*this.tileW*this.sc-this.width/2;d=(c[1]-tileTest[1])*this.tileW*this.sc-this.height/2;c=[];c.x=-b;c.y=-d;return c};this.XYTolatlng=function(c,
d){var a=this._getCenter();if(a){var g=Math.pow(2,this.intZoom),f=a.lat();a=a.lng();a=e(f,a,this.intZoom);f=(a[0]+(c-this.width/2)/this.tileW/this.sc)/g*360-180;g=-b((a[1]+(d-this.height/2)/this.tileH/this.sc)/g*360-180)+0;return new khtml.maplib.LatLng(g,f)}};this.mouseToLatLng=function(c){var b=this.pageX(c);c=this.pageY(c);return this.XYTolatlng(b,c)};this.reSize=function(){var c=this;window.setTimeout(function(){c._getSize(c)},1050)};this._getSize=function(){this.width=this.map.parentNode.offsetWidth;
this.height=this.map.parentNode.offsetHeight;var c=this.map,b=0,d=0;do b+=c.offsetLeft,d+=c.offsetTop,c=c.offsetParent;while(c.offsetParent);this.mapTop=d;this.mapLeft=b};this.recordArray=[];this.record=function(){var c=this._getCenter();if(c){var b=c.lat();c=c.lng();var d=this.getZoom();this.recordArray.push([b,c,d])}};this.play=function(c){if(!(c<1)&&!(c>this.recordArray.length-1)){c=this.recordArray[c];var b=new khtml.maplib.LatLng(c[0],c[1]);this.moveY=this.moveX=0;this.setCenter3(b,c[2])}};this.layerDrawLastFrame=
null;this.doTheOverlayes=!0;this.finalDraw=!1;this.moveDelayedY=this.moveDelayedX=this.layerOldZoom=0;this.layerTimer=new this.myTimer(300);this.layer=function(c,b,d,a,e,g){this.stopRenderOverlays();g||(g=this.getZoom());if(this.layerDrawLastFrame)window.clearTimeout(this.layerDrawLastFrame),this.layerDrawLastFrame=null;if(this.layerTimer.isTimeRunning()||this.finalDraw==!1){var f=this,o=function(){f.finalDraw=!0;f.layer(c,b,d,a,e,g)};if(!f.finalDraw)this.layerDrawLastFrame=window.setTimeout(o,100);
if(this.layerTimer.isTimeRunning()){this.moveDelayedX=a;this.moveDelayedY=e;return}}this.layerTimer.start();for(o=this.moveDelayedY=this.moveDelayedX=0;o<22;o++)if(this.layers[o])this.layers[o].layerDiv.style.visibility="hidden";o=this.wheelSpeedConfig.digizoom?Math.floor(g):Math.round(g);if(this.layerOldZoom>g&&!this.finalDraw&&this.layers[o]&&!this.layers[o].loadComplete)this.visibleZoom=o+1;this.intZoom=o;if(o>this.tileSource.maxzoom)o=this.tileSource.maxzoom;if(!this.visibleZoom)this.oldIntZoom=
this.visibleZoom=o;this.faktor=Math.pow(2,o);this.sc=Math.pow(2,g-o);this.loadingZoomLevel=o;if(this.visibleZoom<o&&Math.abs(this.visibleZoom-o)<4)this.loadingZoomLevel=parseInt(this.visibleZoom)+1;this.draw(this.map,b,d,a,e,this.loadingZoomLevel,g,this.tileSource.src);this.layers[this.loadingZoomLevel].layerDiv.style.visibility="";if(o!=this.visibleZoom)this.visibleZoom<o+2?(this.draw(this.map,b,d,a,e,this.visibleZoom,g,this.tileSource.src),this.layers[this.visibleZoom].layerDiv.style.visibility=
""):this.layers[this.visibleZoom].layerDiv.style.visibility="hidden";if(o==this.visibleZoom)this.draw(this.map,b,d,a,e,this.visibleZoom-1,g,this.tileSource.src),this.layers[this.visibleZoom-1].layerDiv.style.visibility="hidden";if(this.layers[this.loadingZoomLevel].loadComplete&&this.visibleLayer!=o)this.layers[this.loadingZoomLevel].loadComplete=!1,this.hideLayer(this.visibleZoom),this.visibleZoom=this.loadingZoomLevel;this.quadtreeTimeout&&clearTimeout(this.quadtreeTimeout);if(this.loadingZoomLevel!=
o)f=this,this.quadtreeTimeout=window.setTimeout(function(){f.layer(c,b,d,a,e)},200);this.oldIntZoom!=this.intZoom&&this.oldIntZoom!=this.visibleZoom&&this.hideLayer(this.oldIntZoom);this.oldIntZoom=o;this.delayedOverlay&&window.clearTimeout(this.delayedOverlay);this.doTheOverlayes||this.finalDraw||this.layerOldZoom==this.zoom()?(o=new Date,this.lastDX=this.moveX,this.lastDY=this.moveY,this.renderOverlays(),this.layerOldZoom=this.zoom(),this.doTheOverlayes=new Date-o>10?!1:!0):this.hideOverlays();
f=this;this.layerBlockTimeout&&clearTimeout(this.layerBlockTimeout);this.layerBlockTimeout=window.setTimeout(function(){f.layerTimer.reset()},20);this.finalDraw=!1};this.draw=function(c,a,g,f,p,m,q,o){this.framesCounter++;var y=this;window.setTimeout(function(){y.framesCounter--},1E3);var v=Math.pow(2,m);if(this.layers[m])t=this.layers[m].layerDiv,w=d(a)-this.layers[m].startLat,g-=this.layers[m].startLng;else{w=e(a,g,m);this.layers[m]=[];this.layers[m].startTileX=w[0];this.layers[m].startTileY=w[1];
this.layers[m].startLat=d(a);this.layers[m].startLng=g;this.layers[m].images={};var t=document.createElement("div");t.setAttribute("zoomlevel",m);t.style.position="absolute";w=c.childNodes;c=!1;for(g=w.length-1;g>=0;g--)a=w.item(g),a.getAttribute("zoomlevel")<m&&(this.map.insertBefore(t,a),c=!0);c||this.map.appendChild(t);this.layers[m].layerDiv=t;var w=0;g=0}t.style.visibility="hidden";t.style.opacity=1;t.style.filter="alpha(opacity=100)";this.movedLng=(this.layers[m].startTileX/v-f/this.tileW)*
360-180+g;this.movedLat=-b((this.layers[m].startTileY/v-p/this.tileH)*360-180-w);w=e(this.movedLat,this.movedLng,m);f=w[0];g=w[1];p=Math.floor(f);c=Math.floor(g);a=this.layers[m].startTileX;var C=this.layers[m].startTileY;f=f-a-(-a+Math.floor(a));var I=g-C-(-C+Math.floor(C)),x;for(x in this.layers[m].images)this.layers[m].images[x].visibility=!1;g=this.width;var A=this.height;D=Math.pow(2,q-m);minX=Math.floor(-g/2/D/this.tileW+f);maxX=Math.ceil(g/2/D/this.tileW+f);minY=Math.floor(-A/2/D/this.tileH+
I);maxY=Math.ceil(A/2/D/this.tileH+I);for(g=minX;g<maxX;g++)for(A=minY;A<maxY;A++){var z=Math.floor(a+g),u=Math.floor(C+A),E=z%v,B=u;E<0&&(E+=v);if(!(B<0)&&!(B>=v)){var G=o(E,B,m);z=G+"-"+z+"-"+u;minsc=this.wheelSpeedConfig.digizoom?1:0.5;if(this.layers[m].images[z]==null&&D>=minsc){u=document.createElement("img");u.style.visibility="hidden";u.style.position="absolute";u.style.left=g*this.tileW+"px";u.style.top=A*this.tileH+"px";u.style.width=this.tileW+"px";u.style.height=this.tileH+"px";if(this.tileSource.opacity)u.style.opacity=
this.tileSource.opacity;t.childNodes.length>0?t.insertBefore(u,t.childNodes.item(0)):t.appendChild(u);this.layers[m].images[z]={};this.layers[m].images[z].img=u;this.layers[m].images[z].array=[];this.layers[m].images[z].array.push(u);this.layers[m].loadComplete=!1;for(ov in this.tileOverlays){var H=this.tileOverlays[ov],F=u.cloneNode(!0);H=H.src(E,B,m);F.setAttribute("overlay",ov);khtml.maplib.base.helpers.eventAttach(F,"load",this.imgLoaded,this,!1);t.appendChild(F);F.setAttribute("src",H);this.layers[m].images[z].array.push(F)}khtml.maplib.base.helpers.eventAttach(u,
"load",this.imgLoaded,this,!1);khtml.maplib.base.helpers.eventAttach(u,"error",this.imgError,this,!1);u.setAttribute("src",G)}if(!this.css3d&&this.layers[m].images[z]){E=this.layers[m].images[z].array;for(B=0;B<E.length;B++){var J=w[0]-p+Math.floor(f);F=w[1]-c+Math.floor(I);var K=Math.round(this.tileW*D);H=Math.round(this.tileH*D);G=Math.floor(-J*K+g*K);u=Math.floor(-F*H+A*H);J=Math.floor(-J*K+(g+1)*K);F=Math.floor(-F*H+(A+1)*H);E[B].style.left=G+"px";E[B].style.top=u+"px";E[B].style.height=J-G+"px";
E[B].style.width=F-u+"px"}}this.layers[m].images[z]&&(this.layers[m].images[z].visibility=!0)}}for(x in this.layers[m].images)if(this.layers[m].images[x].visibility){if(this.layers[m].images[x].array[0].getAttribute("loaded")=="yes"){o=this.layers[m].images[x].array;for(v=0;v<o.length;v++)if(o[v].getAttribute("loaded")=="yes")o[v].style.visibility=""}}else{o=this.layers[m].images[x].array;for(v=0;v<o.length;v++)this.layers[m].images[x].array[v].style.visibility="hidden",this.layers[m].images[x].array[v].getAttribute("loaded")!=
"yes"&&t.removeChild(this.layers[m].images[x].array[v]);delete this.layers[m].images[x].img;delete this.layers[m].images[x]}var D=Math.pow(2,q-m);G=-f*this.tileW;u=-I*this.tileH;if(this.css3d)t.style["-webkit-transform-origin"]=-1*G+"px "+-1*u+"px",t.style.webkitTransform="translate3d("+G+"px,"+u+"px,0px)  "+(" scale3d("+D+","+D+",1) ");t.style.visibility="";t=q=0;for(x in this.layers[this.loadingZoomLevel].images)t++,u=this.layers[this.loadingZoomLevel].images[x].array[0],u.getAttribute("loaded")!=
"yes"&&q++;this.notLoadedImages=q;q<1&&(this.layers[this.loadingZoomLevel].loadComplete=!0);this.loadingZoomLevel==m&&this.imgLoadInfo(t,q)};this.fadeOutTimeout=null;this.fadeOut=function(b,d){this.fadeOutTimeout&&clearTimeout(this.fadeOutTimeout);if(d>0){b.style.opacity=d;b.style.filter="alpha( opacity="+d*100+" )";var a=this;this.fadeOutTimeout=setTimeout(function(){a.fadeOut(b,d-0.2)},40)}else b.style.visibility="hidden"};this.hideLayer=function(b){if(this.intZoom!=b&&this.layers[b])this.layers[b].layerDiv.style.opacity=
1,this.layers[b].layerDiv.style.filter="alpha(opacity=100)",this.fadeOut(this.layers[b].layerDiv,1);if(this.layers[b])for(var d in this.layers[b].images)if(this.layers[b].images[d]&&this.layers[b].images[d].img&&this.layers[b].images[d].img.getAttribute("loaded")!="yes"&&b!=this.intZoom){for(var a=this.layers[b].images[d].array,e=0;e<a.length;e++)this.layers[b].layerDiv.removeChild(this.layers[b].images[d].array[e]);delete this.layers[b].images[d].img;delete this.layers[b].images[d]}};this.ovImgLoaded=
function(b){(b.target?b.target:b.srcElement).style.visibility=""};this.imgLoaded=function(b){b=b.target?b.target:b.srcElement;var d=!0;b.style.visibility="";b.setAttribute("loaded","yes");if(b.parentNode){for(var a=0,e=0,g=b.parentNode.getAttribute("zoomlevel"),f=0;f<b.parentNode.getElementsByTagName("img").length;f++){var q=b.parentNode.getElementsByTagName("img").item(f);q.getAttribute("overlay")||(e++,q.getAttribute("loaded")!="yes"&&(a++,d=!1))}this.notLoadedImages=a;this.loadingZoomLevel==g&&
this.imgLoadInfo(e,a);if((this.layers[g].loadComplete=d)&&this.loadingZoomLevel==g)this.hideLayer(this.visibleZoom),this.hideLayer(this.visibleZoom+1),this.visibleZoom=g}};this.imgError=function(b){var d=b.target?b.target:b.srcElement;d.parentNode&&(d.src!="http://khtml.org/notfound.png"&&d.setAttribute("src","http://khtml.org/notfound.png"),this.imgLoaded(b))};var e=function(b,d,a){return[(d+180)/360*(1<<a),(1-Math.log(Math.tan(b*Math.PI/180)+1/Math.cos(b*Math.PI/180))/Math.PI)/2*(1<<a)]};this._calculateMapSize=
function(){var b=this.mapParent;if(b.currentStyle)var d=b.currentStyle;else window.getComputedStyle&&(d=document.defaultView.getComputedStyle(b,null));var a=parseInt(d.borderTopWidth);isNaN(a)&&(a=0);var e=parseInt(d.borderLeftWidth);isNaN(e)&&(e=0);var g=parseInt(d.borderRightWidth);isNaN(g)&&(g=0);var f=parseInt(d.borderBottomWidth);isNaN(f)&&(f=0);var q=parseInt(d.paddingTop),o=parseInt(d.paddingBottom),y=parseInt(d.paddingLeft),v=parseInt(d.paddingRight),t=q,w=y;g=b.offsetWidth-e-g-y-v;f=b.offsetHeight-
a-f-o-q;q=a+q;y=e+y;for(var C=!0;b&&!isNaN(b.offsetLeft)&&!isNaN(b.offsetTop);)y+=b.offsetLeft-b.scrollLeft,q+=b.offsetTop-b.scrollTop,b.currentStyle?d=b.currentStyle:window.getComputedStyle&&(d=document.defaultView.getComputedStyle(b,null)),C&&(d&&d.position=="absolute"&&(C=!1),C&&(w+=b.offsetLeft+b.scrollLeft,t+=b.offsetTop+b.scrollTop),w+=e/2,t+=a/2),b=b.offsetParent;return{top:q,left:y,width:g,height:f,deltaTop:t,deltaLeft:w,deltaBottom:o,deltaRight:v}};this.redraw=function(){this.setMapPosition()};
this.setMapPosition=function(){this.mapsize=this._calculateMapSize();var b=this.mapParent;b.currentStyle||window.getComputedStyle&&document.defaultView.getComputedStyle(b,null);this.mapTop=this.mapsize.top;this.mapLeft=this.mapsize.left;this.width=this.mapsize.width;this.height=this.mapsize.height;relativetop=this.mapsize.deltaTop;relativeleft=this.mapsize.deltaLeft;this.clone.style.top=relativetop+"px";this.clone.style.left=relativeleft+"px";this.clone.style.width=this.mapsize.width+"px";this.clone.style.height=
this.mapsize.height+"px";this.clone.style.position="absolute";this.clone.style.overflow="hidden";this.map.style.left=this.mapsize.width/2+"px";this.map.style.top=this.mapsize.height/2+"px";this._getCenter()&&this.getZoom()&&this.centerAndZoom(this._getCenter(),this.getZoom())};this.clearMap=function(){if(this.map){for(;this.map.firstChild;)this.map.removeChild(this.map.firstChild);for(;this.layers.length>0;)this.layers.pop();this.redraw()}};var d=function(b){return 180/Math.PI*Math.log(Math.tan(Math.PI/
4+b*(Math.PI/180)/2))},b=function(b){return 180/Math.PI*(2*Math.atan(Math.exp(b*Math.PI/180))-Math.PI/2)};this.imgLoadInfo=function(b,d){if(!this.loadInfoDiv)this.loadInfoDiv=document.createElement("div"),this.loadInfoDiv.style.position="absolute",this.loadInfoDiv.style.top="0px",this.loadInfoDiv.style.right="0px",this.loadInfoDiv.style.backgroundColor="white",this.loadInfoDiv.style.border="1px solid gray",this.loadInfoDiv.style.fontSize="10px",this.map.parentNode.appendChild(this.loadInfoDiv);if(d==
0)this.loadInfoDiv.style.display="none";else{for(this.loadInfoDiv.style.display="";this.loadInfoDiv.firstChild;)this.loadInfoDiv.removeChild(this.loadInfoDiv.firstChild);this.loadInfoDiv.appendChild(document.createTextNode(d+" images to load"))}};this.copyright=function(){var b=document.createElement("img"),d=document.createElement("a");d.setAttribute("href","http://khtml.org");b.setAttribute("src","http://khtml.org/favicon.png");b.style.zIndex=10;b.style.position="absolute";b.style.left="2px";b.style.bottom=
"2px";b.style.width="24px";b.style.height="24px";d.appendChild(b);this.mapParent.appendChild(d)};this.internetExplorer=!1;if(navigator.userAgent.indexOf("MSIE")!=-1)this.internetExplorer=!0;if(navigator.userAgent.indexOf("Android")!=-1){var g=this;setInterval(function(){g.layerTimer.reset()},300)}this.position={};this.tiles({maxzoom:18,minzoom:1,src:function(b,d,a){switch((b+d)%3){case 0:var e="a";break;case 1:e="b";break;case 2:e="c";break;default:e="f"}return"http://"+e+".tile.openstreetmap.org/"+
a+"/"+b+"/"+d+".png"},copyright:"osm"});this.wheelSpeedConfig=[];this.wheelSpeedConfig.acceleration=2;this.wheelSpeedConfig.maxSpeed=2;this.wheelSpeedConfig.animate=!1;navigator.userAgent.indexOf("AppleWebKit")!=-1&&(this.wheelSpeedConfig.animate=!0);navigator.userAgent.indexOf("Opera")!=-1&&(this.wheelSpeedConfig.animate=!1);this.wheelSpeedConfig.animate=!1;this.wheelSpeedConfig.digizoom=!0;this.wheelSpeedConfig.zoomAnimationSlowdown=0.02;this.wheelSpeedConfig.animationFPS=50;this.wheelSpeedConfig.moveAnimateDesktop=
!0;this.wheelSpeedConfig.rectShiftAnimate=!1;this.wheelSpeedConfig.rectShiftAnimationTime=500;this.wheelSpeedConfig.animateMinSpeed=0.4;this.wheelSpeedConfig.animateMaxSpeed=200;this.wheelSpeedConfig.moveAnimationSlowdown=0.4;this.framesCounter=this.wheelEventCounter=0;this.mapParent=a;this.copyright();this.clone=a.cloneNode(!0);this.clone=document.createElement("div");this.clone.removeAttribute("id");a.firstChild?a.insertBefore(this.clone,a.firstChild):a.appendChild(this.clone);this.map=document.createElement("div");
this.map.style.position="absolute";this.clone.appendChild(this.map);this.setMapPosition();this.overlayDiv=document.createElement("div");this.overlayDiv.style.position="absolute";this.clone.appendChild(this.overlayDiv);this.overlays=[];if(khtml.maplib.overlay.FeatureCollection)this.featureCollection=new khtml.maplib.overlay.FeatureCollection,this.featureCollection.map=this,this.addOverlay(this.featureCollection);this.distanceMeasuring="no";this.measureLine=this.moveMarker=null;this.moveAnimationMobile=
!0;this.moveAnimationBlocked=this.moveAnimationDesktop=!1;this.lastMouseX=this.width/2;this.lastMouseY=this.height/2;this.layers=[];this.intZoom=this.oldVisibleZoom=this.visibleZoom=null;this.startMoveY=this.startMoveX=this.lastMoveTime=this.lastMoveY=this.lastMoveX=this.moveY=this.moveX=0;this.sc=1;this.blocked=!1;this.tileH=this.tileW=256;this.position.zoom=1;this.movestarted=!1;this.mousedownTime=null;this.doubleclickTime=400;this.mousedownTime2=null;this.doubleclickTime2=500;this.zoomOutTime=
1E3;this.zoomOutSpeed=0.01;this.zoomOutInterval=null;this.zoomOutStarted=!1;this.zoomSpeedTimer=null;this.zoomAcceleration=1;this.css3d=!1;if(navigator.userAgent.indexOf("iPhone OS")!=-1)this.css3d=!0;if(navigator.userAgent.indexOf("iPad")!=-1)this.css3d=!1;if(navigator.userAgent.indexOf("Safari")!=-1)this.css3d=navigator.userAgent.indexOf("Mac")!=-1?!1:!0;if(navigator.userAgent.indexOf("iPhone OS")!=-1)this.css3d=!0;if(navigator.userAgent.indexOf("Android")!=-1)this.css3d=!1;if(this.internetExplorer){var f=
a;navigator.userAgent.indexOf("Windows Phone OS")!=-1&&khtml.maplib.base.helpers.eventAttach(f,"mouseup",this.mouseupIE,this,!1)}else f=window;khtml.maplib.base.helpers.eventAttach(window,"resize",this.setMapPosition,this,!1);navigator.userAgent.indexOf("Konqueror")!=-1&&(f=a);khtml.maplib.base.helpers.eventAttach(a,"touchstart",this.start,this,!1);khtml.maplib.base.helpers.eventAttach(a,"touchmove",this.move,this,!1);khtml.maplib.base.helpers.eventAttach(a,"touchend",this.end,this,!1);khtml.maplib.base.helpers.eventAttach(f,
"mousemove",this.mousemove,this,!1);khtml.maplib.base.helpers.eventAttach(a,"mousedown",this.mousedown,this,!1);khtml.maplib.base.helpers.eventAttach(f,"mouseup",this.mouseup,this,!1);khtml.maplib.base.helpers.eventAttach(f,"orientationchange",this.reSize,this,!1);khtml.maplib.base.helpers.eventAttach(a,"DOMMouseScroll",this.mousewheel,this,!1);khtml.maplib.base.helpers.eventAttach(a,"dblclick",this.doubleclick,this,!1);typeof this.keyup=="function"&&khtml.maplib.base.helpers.eventAttach(f,"keyup",
this.keyup,this,!1);typeof this.keypress=="function"&&khtml.maplib.base.helpers.eventAttach(f,"keypress",this.keypress,this,!1)};khtml.maplib.geometry.Bounds=function(a,e){this.enlarge=function(b){b.lng()>this.southwest.lng()&&b.lng()>this.northeast.lng()&&this.northeast.lng(b.lng());b.lng()<this.southwest.lng()&&b.lng()<this.northeast.lng()&&this.southwest.lng(b.lng());b.lat()>this.southwest.lat()&&b.lat()>this.northeast.lat()&&this.northeast.lat(b.lat());b.lat()<this.southwest.lat()&&b.lat()<this.northeast.lat()&&this.southwest.lat(b.lat())};this.sw=function(){return this.southwest};this.se=function(){return new khtml.maplib.LatLng(this.southwest.lat(),
this.northeast.lng())};this.ne=function(){return this.northeast};this.nw=function(){return new khtml.maplib.LatLng(this.northeast.lat(),this.southwest.lng())};this.getCenter=function(){return this.center};this.getOpticalCenter=function(b){var d=b.latlngToXY(this.southwest),a=b.latlngToXY(this.northeast);return b.XYTolatlng(Math.abs(d.x+a.x)/2,Math.abs(d.y+a.y)/2)};this.getZoomLevel=function(b){origZoom=b.getZoom();var d=b.latlngToXY(this.southwest),a=b.latlngToXY(this.northeast),c=b.width/Math.abs(d.x-
a.x);b=b.height/Math.abs(d.y-a.y);if(c>b)var e=b;c<=b&&(e=c);return origZoom+Math.log(e)/Math.log(2)};this.getDistance=function(){return this.distance(this.southwest.lat(),this.southwest.lng(),this.northeast.lat(),this.northeast.lng())};this.getInnerRadius=function(){var b=this.distance(this.center.lat(),this.southwest.lng(),this.center.lat(),this.northeast.lng()),d=this.distance(this.southwest.lat(),this.center.lng(),this.northeast.lat(),this.center.lng());return b>d?d/2:b/2};this.distance=function(b,
d,a,c){b=b*Math.PI/180;a=a*Math.PI/180;return Math.acos(Math.sin(b)*Math.sin(a)+Math.cos(b)*Math.cos(a)*Math.cos(c*Math.PI/180-d*Math.PI/180))*180/Math.PI/360*4E7};this.intersects=function(b){if(!(b instanceof khtml.maplib.geometry.Bounds))return khtml.maplib.base.Log.warn('Bounds.intersects(): Illegal argument. Has to be "khtml.maplib.geometry.Bounds"!'),!1;var d=Math.min(this.sw().lat(),this.ne().lat()),a=Math.max(this.sw().lat(),this.ne().lat()),c=Math.min(this.sw().lng(),this.ne().lng()),e=Math.max(this.sw().lng(),
this.ne().lng()),h=[];h.push(b.ne());h.push(b.se());h.push(b.sw());h.push(b.nw());for(b=0;b<h.length;b++){var l=h[b],p=l.lat()>=d&&l.lat()<=a;l=l.lng()>=c&&l.lng()<=e;if(p&&l)return!0}return!1};this.createBoundsFrom2Points=function(b,d){var a=new khtml.maplib.LatLng(Math.min(b.lat(),d.lat()),Math.min(b.lng(),d.lng())),c=new khtml.maplib.LatLng(Math.max(b.lat(),d.lat()),Math.max(b.lng(),d.lng()));return{sw:a,ne:c}};var d=this.createBoundsFrom2Points(a,e);this.southwest=d.sw;this.northeast=d.ne;this.center=
new khtml.maplib.LatLng((this.southwest.lat()+this.northeast.lat())/2,(this.southwest.lng()+this.northeast.lng())/2)};khtml.maplib.geometry.LatLng=function(a,e){this.callbackFunctions=[];this.addCallbackFunction=function(d){typeof d=="function"&&this.callbackFunctions.push(d)};this.executeCallbackFunctions=function(){for(var d=0;d<this.callbackFunctions.length;d++)this.callbackFunctions[d].call(this)};this.lat=function(d){if(typeof d=="number")this.latitude=d,this.executeCallbackFunctions();if(typeof d=="string")this.latitude=parseFloat(d),this.executeCallbackFunctions();return this.latitude};this.lng=function(d){if(typeof d==
"number")this.longitude=d,this.executeCallbackFunctions();if(typeof d=="string")this.longitude=parseFloat(d),this.executeCallbackFunctions();return this.longitude};this.equals=function(d){if(null==d)return!1;if(!(d instanceof khtml.maplib.LatLng))return khtml.maplib.base.Log.warn("Point.equals(): Error - illegal argument!",d),!1;return d.lat()===this.lat()&&d.lng()===this.lng()};a instanceof khtml.maplib.LatLng?(this.lat(a.lat()),this.lng(a.lng())):typeof a=="object"?(a.lat&&this.lat(a.lat),a.lng&&
this.lng(a.lng)):(this.lat(a),this.lng(e))};khtml.maplib.overlay.Vector=function(){function a(){var a=-1;navigator.appName=="Microsoft Internet Explorer"&&/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)!=null&&(a=parseFloat(RegExp.$1));return a}this.vectorPointsPerIteration=2E3;this.lineArray=[];this.stopit=!1;this.backend="svg";if(navigator.userAgent.indexOf("Android")!=-1)this.backend="canvas";this.svgStyleInterface=!1;if(navigator.userAgent.indexOf("MSIE")!=-1&&a()<9)this.backend="vml";this.canvasClassStyles=[];this.boundsSouth=90;
this.boundsNorth=-90;this.boundsWest=180;this.boundsEast=-180;this.renderbackend=function(a){if(a){this.backend=a;if(this.vectorEl&&this.vectorEl.parentNode){var d=this.vectorEl.parentNode;d.removeChild(this.vectorEl)}this.createVectorElement(this.themap);d.appendChild(this.vectorEl);this.render()}return this.backend};this.createVectorElement=function(a){switch(this.backend){case "canvas":vectorEl=document.createElement("canvas");this.ctx=vectorEl.getContext("2d");break;case "svg":vectorEl=document.createElementNS("http://www.w3.org/2000/svg",
"svg");break;case "vml":if(document.namespaces&&document.namespaces.v==null){document.namespaces.add("v","urn:schemas-microsoft-com:vml");var d=document.createStyleSheet();d.addRule("v\\:group","behavior: url(#default#VML);");d.addRule("v\\:polyline","behavior: url(#default#VML);");d.addRule("v\\:stroke","behavior: url(#default#VML);");d.addRule("v\\:fill","behavior: url(#default#VML);")}vectorEl=document.createElement("div");break;default:alert("error: unknown vector backend")}vectorEl.style.width=
a.mapsize.width+"px";vectorEl.style.height=a.mapsize.height+"px";vectorEl.setAttribute("height",a.mapsize.height+"px");vectorEl.setAttribute("width",a.mapsize.width+"px");vectorEl.style.position="absolute";vectorEl.style.top="0";vectorEl.style.left="0";return vectorEl};this.init=function(a){this.owner=a;a instanceof khtml.maplib.base.Map?(this.themap=a,this.vectorEl=this.createVectorElement(this.themap),this.themap.overlayDiv.appendChild(this.vectorEl)):(this.themap=a.map,this.vectorEl=this.createVectorElement(this.themap),
this.owner.overlayDiv.appendChild(this.vectorEl))};this.createPolyline=function(a){a.tags=[];if(!a.close)a.close=!1;a.id=null;if(!a.geometry.coordinates)a.geometry.coordinates=[];a.calculateCenter=function(){for(var b=0,d=0,f=0;f<a.points.length;f++)b+=a.points[f].lat(),d+=a.points[f].lng();return new khtml.maplib.LatLng(b/a.points.length,d/a.points.length)};var d=this;a.render=function(){d.render(a)};this.lineArray.unshift(a);a.bbox=this.makeBounds(a.geometry.coordinates);return a};this.cancel=function(){this.stopit=
!0};this.renderCount=0;this.render=function(a){if(this.vectorEl){this.vectorEl.setAttribute("class","z"+Math.floor(this.themap.zoom()));if(this.stopit&&(this.stopit=!1,a!=null)){if(this.oldVectorEl&&this.oldVectorEl.parentNode)try{this.oldVectorEl.parentNode.removeChild(this.oldVectorEl),this.vectorEl=this.createVectorElement(this.themap),this.themap.overlayDiv.appendChild(this.vectorEl)}catch(d){alert(this.oldVectorEl.tagName),alert(this.oldVectorEl.parentNode.tagName)}return}if(a==null){this.backend==
"canvas"&&this.ctx.beginPath();if(this.oldZoom==this.themap.zoom()&&(this.themap.moveX!=this.lastMoveX||this.themap.moveY!=this.lastMoveY)){var b=Math.round((this.themap.moveX-this.lastMoveX)*this.themap.faktor*this.themap.sc),g=Math.round((this.themap.moveY-this.lastMoveY)*this.themap.faktor*this.themap.sc);if(this.vectorEl.style)try{this.vectorEl.style.top=g+"px",this.vectorEl.style.left=b+"px"}catch(f){console.log("move not passible")}if(!this.themap.finalDraw)return;this.oldVectorEl=this.vectorEl;
this.vectorEl=this.createVectorElement(this.themap)}else this.clear(),this.oldtimestamp=(new Date).getTime(),this.starttimestamp=(new Date).getTime(),this.renderCount=this.totalLinesCounter=this.totalPointsCounter=0;this.oldZoom=this.themap.zoom();a=this.lineArray.length-1;this.lastMoveX=this.themap.moveX;this.lastMoveY=this.themap.moveY}if(a<0){if(this.backend=="canvas"&&(this.ctx.stroke(),this.ctx.fill()),this.timestamp=(new Date).getTime(),this.renderIterationTime=this.timestamp-this.starttimestamp,
this.totalPoints=this.totalPointsCounter,this.totalLines=this.totalLinesCounter,this.oldVectorEl&&this.oldVectorEl.parentNode)this.oldVectorEl.parentNode.replaceChild(this.vectorEl,this.oldVectorEl),this.vectorEl.style.display=""}else{b=typeof a=="number"?this.lineArray[a]:a;if(khtml.maplib.base.helpers.overlaps(this.themap.bounds(),b.bbox)){stroke="black";strokeWidth=4;fill="red";switch(this.backend){case "svg":if(b.path)c=b.path;else{var c=khtml.maplib.overlay.renderer.SVG._renderInitPolyline(b);
b.geometry.type=="Polygon"||b.geometry.type=="MultiPolygon"||b.geometry.type=="Polyline"&&b.close?b.close="true":b.style.fill="none";b.close="false";b.path=c;c.owner=b}break;case "vml":c=document.createElement("v:polyline");var k=document.createElement("v:fill");c.appendChild(k);var h=document.createElement("v:stroke");c.appendChild(h);c.setAttribute("fillcolor",fill);c.setAttribute("strokecolor",stroke);c.setAttribute("strokeweight",strokeWidth+"px")}switch(this.backend){case "svg":var l=khtml.maplib.overlay.renderer.SVG._calculatePath(b.geometry.coordinates,
b.geometry.type,this.themap);c.setAttribute("d",l.d);for(var p in b.properties)c.setAttribute("mapcss_"+p,b.properties[p]);c.style.fillRule="evenodd";this.vectorEl.appendChild(c);break;case "canvas":l=khtml.maplib.overlay.renderer.Canvas._renderPath(b.geometry.coordinates,b,this.ctx,this.themap);break;case "vml":l=khtml.maplib.overlay.renderer.VML._calculatePath(b.geometry.coordinates,b.geometry.type,this.themap);if(!this.styler)this.styler=new khtml.maplib.overlay.renderer.Styler;p={};p.fillRGB=
"rgb(0,0,0)";p.opacity=0;b.className&&(p=this.styler.makeCanvasStyle(b));c.setAttribute("fillcolor",p.fillRGB);c.setAttribute("strokecolor",p.strokeRGB);k.setAttribute("opacity",p.fillOpacity);h.setAttribute("opacity",p.strokeOpacity);c.setAttribute("strokeweight",p.lineWidth+"px");c.setAttribute("points",l.d);b.geometry.type=="Polygon"||b.geometry.type=="MultiPolygon"?c.setAttribute("filled",!0):c.setAttribute("filled",!1);this.vectorEl.appendChild(c);break;default:console.log("error: unknow backend")}this.renderCount+=
l.points;this.totalPointsCounter+=l.points;this.totalLinesCounter+=l.lines}if(typeof a!="number"){if(this.backend=="canvas"){this.canvasRenderTimeout&&clearTimeout(this.canvasRenderTimeout);var m=this;this.canvasRenderTimeout=setTimeout(function(){m.ctx.stroke();m.ctx.fill()},1)}}else if(this.renderCount>this.vectorPointsPerIteration){this.timestamp=(new Date).getTime();this.iterationTime=this.timestamp-this.oldtimestamp;this.vectorPointsPerIteration=Math.ceil(this.vectorPointsPerIteration*100/this.iterationTime);
if(this.vectorPointsPerIteration<2E3)this.vectorPointsPerIteration=2E3;this.oldtimestamp=this.timestamp;this.renderCount=0;m=this;setTimeout(function(){m.render(a-1)},0);this.backend=="canvas"&&(this.ctx.stroke(),this.ctx.fill(),this.ctx.beginPath())}else this.render(a-1)}}};this.makeBounds=function(a){for(var d=90,b=-90,g=180,f=-180,c=0;c<a.length;c++)if(a[c]instanceof khtml.maplib.geometry.LatLng){var k=a[c].lng(),h=a[c].lat();h>b&&(b=h);h<d&&(d=h);k>f&&(f=k);k<g&&(g=k)}else k=this.makeBounds(a[c]),
k.sw().lat()<d&&(d=k.sw().lat()),k.sw().lng()<g&&(g=k.sw().lng()),k.ne().lat()>b&&(b=k.ne().lat()),k.ne().lng()>f&&(f=k.ne().lng());a=new khtml.maplib.LatLng(d,g);b=new khtml.maplib.LatLng(b,f);return new khtml.maplib.geometry.Bounds(a,b)};this.bounds=function(){var a=new khtml.maplib.LatLng(this.boundsSouth,this.boundsWest),d=new khtml.maplib.LatLng(this.boundsNorth,this.boundsEast);return new khtml.maplib.geometry.Bounds(a,d)};this.clear=function(){this.ctx&&this.ctx.clearRect(0,0,this.themap.mapsize.width,
this.themap.mapsize.height);if(this.backend=="svg"||this.backend=="vml")for(;this.vectorEl.firstChild;)this.vectorEl.removeChild(this.vectorEl.firstChild)}};khtml.maplib.overlay.Marker=function(a,e,d){this.nodeName=this.nodeType="Marker";this.geometry={};this.geometry.coordinates=a;this.geometry.type="Point";this.type="Marker";var b=document.createElement("div");b.appendChild(e);b.style.position="absolute";d?(d.dy?b.style.top=typeof d.dy=="number"?d.dy+"px":d.dy:b.style.left=typeof d.dx=="number"?d.dx+"px":d.dx,b.style.left=d.dx?d.dx:"0px"):(b.style.top="0px",b.style.left="0px");var g=document.createElement("div");g.style.position="absolute";g.appendChild(b);
this.marker=g;this.point=a;this.options=d;this.el=e;this.init=function(b){this.style=this.marker.style;this.marker.owner=this;this.mapObj=b instanceof khtml.maplib.base.Map?b:b.map;b.overlayDiv.appendChild(this.marker)};this.render=function(){if(this.mapObj&&this.marker&&this.point&&!isNaN(this.point.lat())&&!isNaN(this.point.lng())){var b=this.mapObj.latlngToXY(this.geometry.coordinates);b.x<0||b.y<0?this.marker.style.display="none":(this.marker.style.display="",this.marker.style.left=b.x+"px",this.marker.style.top=
b.y+"px");this.marker.parentNode||this.owner.overlayDiv.appendChild(this.marker)}};this.position=function(b){if(b)this.point=b,this.render();return this.point};this.clear=function(){if(this.marker&&this.marker.parentNode)try{this.owner.overlayDiv.removeChild(this.marker)}catch(b){}};this.moveable=function(b){(this.enabled=b)?(this.downevent=khtml.maplib.base.helpers.eventAttach(this.marker,"mousedown",this.down,this,!1),this.moveevent=khtml.maplib.base.helpers.eventAttach(window,"mousemove",this.move,
this,!0),this.upevent=khtml.maplib.base.helpers.eventAttach(window,"mouseup",this.up,this,!0)):(khtml.maplib.base.helpers.eventRemove(this.downevent),khtml.maplib.base.helpers.eventRemove(this.moveevent),khtml.maplib.base.helpers.eventRemove(this.upevent))};this.moving=!1;this.dy=this.dx=0;this.down=function(b){this.moving=!0;this.dx=this.marker.offsetLeft-this.mapObj.pageX(b);this.dy=this.marker.offsetTop-this.mapObj.pageY(b)};this.move=function(b){if(this.moving){var a=this.mapObj.pageX(b)+this.dx,
d=this.mapObj.pageY(b)+this.dy;this.point.lat(this.mapObj.XYTolatlng(a,d).lat());this.point.lng(this.mapObj.XYTolatlng(a,d).lng());this.render();b.stopPropagation()}};this.up=function(){this.moving=!1}};var lastStrokeStyle=null,lastFillStyle=null,lastGlobalCompositeOperation="source-over";
khtml.maplib.overlay.renderer.Canvas={_renderPath:function(a,e,d,b,g,f){if(!this.styler)this.styler=new khtml.maplib.overlay.renderer.Styler;var c=this.styler.makeCanvasStyle(e),k=e.geometry.type,h=0,l=0,p=!1;c.globalCompositeOperation=k=="Polygon"&&f>1&&g>0?"destination-out":"source-over";c.globalCompositeOperation=="source-over"&&lastGlobalCompositeOperation=="source-over"&&c.strokeStyle==lastStrokeStyle&&c.fillStyle==lastFillStyle||(d.fill(),d.stroke(),d.beginPath());lastStrokeStyle=c.strokeStyle;
lastFillStyle=c.fillStyle;lastGlobalCompositeOperation=c.globalCompositeOperation;d.strokeStyle=c.strokeStyle;d.fillStyle=c.fillStyle;d.lineWidth=c.lineWidth;d.globalCompositeOperation=c.globalCompositeOperation;for(g=0;g<a.length;g++)a[g]instanceof khtml.maplib.LatLng?(p=!0,l++,c=b.latlngToXY(a[g]),g==0?d.moveTo(c.x,c.y):d.lineTo(c.x,c.y)):(f?f++:f=1,c=this._renderPath(a[g],e,d,b,g,f),h+=c.lines,l+=c.points);(k=="Polygon"||k=="MultiPolygon")&&d.closePath();p&&h++;return{points:l,lines:h}}};khtml.maplib.overlay.renderer.SVG={_renderSetStyles:function(){},_renderInitPolyline:function(a){var e=document.createElementNS("http://www.w3.org/2000/svg","path");e.polyline=a;if(a.className!=null&&a.className.baseVal)navigator.userAgent.indexOf("Konqueror")==-1?e.className.baseVal=a.className.baseVal:e.className=a.className.baseVal,e.polyline=a;a.className=e.className;a.id!=null&&e.setAttribute("id",a.id);for(var d in a.events)khtml.maplib.base.helpers.eventAttach(e,d,a.events[d],this,!1);for(var b in a.style)e.style[b]=
a.style[b];a.style=e.style;return e},_calculatePath:function(a,e,d){for(var b="",g=0,f=0,c=0;c<a.length;c++)if(a[c]instanceof khtml.maplib.geometry.LatLng){f++;var k=d.latlngToXY(a[c]);b+=c==0?"M"+k.x+","+k.y:" L"+k.x+","+k.y}else k=this._calculatePath(a[c],e,d),g+=k.lines,f+=k.points,b+=" "+k.d;g++;if(e=="Polygon"||e=="MultiPolygon")b+=" z";return{d:b,points:f,lines:g}}};khtml.maplib.overlay.renderer.VML={_renderSetStyles:function(){},_renderInitPolyline:function(){this._path=document.createElement("v:polyline");this._path.setAttribute("fillcolor",this._fill);this._path.setAttribute("strokecolor",this._stroke);this._path.setAttribute("strokeweight",this._strokeWidth+"px")},_calculatePath:function(a,e,d){for(var b="",g=0,f=0,c=0;c<a.length;c++)if(a[c]instanceof khtml.maplib.LatLng){f++;var k=d.latlngToXY(a[c]);if(c==0){var h=k;b+="m"+k.x+","+k.y}else b+=" l"+k.x+","+
k.y}else k=this._calculatePath(a[c],e,d),g+=k.lines,f+=k.points,b+=" "+k.d;g++;if(e=="Polygon"||e=="MultiPolygon")console.log("dasa",a[0].x),b+=" l"+h.x+","+h.y;return{d:b,points:f,lines:g}}};khtml.maplib.overlay.renderer.Styler=function(){function a(b,a){if(b.search(/^rgb\(/)!=-1){khtml.maplib.base.Log.log("test1");var f;f=b.replace("rgb(","rgba(");return f=f.replace(")",","+a+")")}b[0]!="#"&&(b=="none"?(b="000000",a=0):b="#"+e[b]);f="rgba(";b.charAt(0)=="#"&&(b=b.substr(1));b.length==3&&(b=b.charAt(0)+b.charAt(0)+b.charAt(1)+b.charAt(1)+b.charAt(2)+b.charAt(2));b=b.toUpperCase();var c=0;for(i=0;i<b.length;i++){var k;for(j=0;j<d.length;j++)if(b.charAt(i)==d[j]){k=j;break}i%2==0?c=k*16:
(c+=k,f+=i==b.length-1?c+","+a+")":c+", ")}return f}this.getCssStyles=function(b){for(var a={},d=0;d<document.styleSheets.length;d++){var c=document.styleSheets[d];c=c.cssRules?c.cssRules:c.rules;for(r=0;r<c.length;r++){var e=c[r].style.cssText;selectorText=c[r].selectorText;if(selectorText=="."+b){e=e.split(";");for(var h=0;h<e.length;h++){var l=e[h].split(":");if(l.length>1){var p=l[0].replace(/^\s/,"");l=l[1].replace(/^\s/,"");if(p=="stroke")a.stroke=l;if(p=="fill")a.fill=l;if(p=="stroke-width")a.strokeWidth=
parseFloat(l);if(p=="opacity")a.opacity=parseFloat(l);if(p=="fill-opacity")a.fillOpacity=parseFloat(l);if(p=="stroke-opacity")a.strokeOpacity=parseFloat(l)}}}}}return a};var e={aliceblue:"f0f8ff",antiquewhite:"faebd7",aqua:"00ffff",aquamarine:"7fffd4",azure:"f0ffff",beige:"f5f5dc",bisque:"ffe4c4",black:"000000",blanchedalmond:"ffebcd",blue:"0000ff",blueviolet:"8a2be2",brown:"a52a2a",burlywood:"deb887",cadetblue:"5f9ea0",chartreuse:"7fff00",chocolate:"d2691e",coral:"ff7f50",cornflowerblue:"6495ed",
cornsilk:"fff8dc",crimson:"dc143c",cyan:"00ffff",darkblue:"00008b",darkcyan:"008b8b",darkgoldenrod:"b8860b",darkgray:"a9a9a9",darkgreen:"006400",darkkhaki:"bdb76b",darkmagenta:"8b008b",darkolivegreen:"556b2f",darkorange:"ff8c00",darkorchid:"9932cc",darkred:"8b0000",darksalmon:"e9967a",darkseagreen:"8fbc8f",darkslateblue:"483d8b",darkslategray:"2f4f4f",darkturquoise:"00ced1",darkviolet:"9400d3",deeppink:"ff1493",deepskyblue:"00bfff",dimgray:"696969",dodgerblue:"1e90ff",feldspar:"d19275",firebrick:"b22222",
floralwhite:"fffaf0",forestgreen:"228b22",fuchsia:"ff00ff",gainsboro:"dcdcdc",ghostwhite:"f8f8ff",gold:"ffd700",goldenrod:"daa520",gray:"808080",green:"008000",greenyellow:"adff2f",honeydew:"f0fff0",hotpink:"ff69b4",indianred:"cd5c5c",indigo:"4b0082",ivory:"fffff0",khaki:"f0e68c",lavender:"e6e6fa",lavenderblush:"fff0f5",lawngreen:"7cfc00",lemonchiffon:"fffacd",lightblue:"add8e6",lightcoral:"f08080",lightcyan:"e0ffff",lightgoldenrodyellow:"fafad2",lightgrey:"d3d3d3",lightgreen:"90ee90",lightpink:"ffb6c1",
lightsalmon:"ffa07a",lightseagreen:"20b2aa",lightskyblue:"87cefa",lightslateblue:"8470ff",lightslategray:"778899",lightsteelblue:"b0c4de",lightyellow:"ffffe0",lime:"00ff00",limegreen:"32cd32",linen:"faf0e6",magenta:"ff00ff",maroon:"800000",mediumaquamarine:"66cdaa",mediumblue:"0000cd",mediumorchid:"ba55d3",mediumpurple:"9370d8",mediumseagreen:"3cb371",mediumslateblue:"7b68ee",mediumspringgreen:"00fa9a",mediumturquoise:"48d1cc",mediumvioletred:"c71585",midnightblue:"191970",mintcream:"f5fffa",mistyrose:"ffe4e1",
moccasin:"ffe4b5",navajowhite:"ffdead",navy:"000080",oldlace:"fdf5e6",olive:"808000",olivedrab:"6b8e23",orange:"ffa500",orangered:"ff4500",orchid:"da70d6",palegoldenrod:"eee8aa",palegreen:"98fb98",paleturquoise:"afeeee",palevioletred:"d87093",papayawhip:"ffefd5",peachpuff:"ffdab9",peru:"cd853f",pink:"ffc0cb",plum:"dda0dd",powderblue:"b0e0e6",purple:"800080",red:"ff0000",rosybrown:"bc8f8f",royalblue:"4169e1",saddlebrown:"8b4513",salmon:"fa8072",sandybrown:"f4a460",seagreen:"2e8b57",seashell:"fff5ee",
sienna:"a0522d",silver:"c0c0c0",skyblue:"87ceeb",slateblue:"6a5acd",slategray:"708090",snow:"fffafa",springgreen:"00ff7f",steelblue:"4682b4",tan:"d2b48c",teal:"008080",thistle:"d8bfd8",tomato:"ff6347",turquoise:"40e0d0",violet:"ee82ee",violetred:"d02090",wheat:"f5deb3",white:"ffffff",whitesmoke:"f5f5f5",yellow:"ffff00",yellowgreen:"9acd32"},d=["0","1","2","3","4","5","6","7","8","9","A","B","C","D","E","F"];this.classes=[];console.log("new",this.classes);this.makeCanvasStyle=function(b){var d=[],
e=b.style,c=1,k=1,h=1,l="none",p="black",m=1;if(b.className){this.classes[b.className.baseVal]||(console.log("dring"),this.classes[b.className.baseVal]=this.getCssStyles(b.className.baseVal));var q=this.classes[b.className.baseVal];if(q.fill)l=q.fill;if(q.stroke)p=q.stroke;if(q.strokeWidth)m=q.strokeWidth;if(q.opacity)c=q.opacity;if(q.strokeOpacity)k=q.strokeOpacity;if(q.fillOpacity)h=q.fillOpacity}b.geometry.type!="Polygon"&&b.geometry.type!="MultiPolygon"&&(h=0);if(e.opacity)c=e.opacity;if(e.fillOpacity)h=
e.fillOpacity;if(e.strokeOpacity)k=e.strokeOpacity;if(e.stroke)p=e.stroke;if(e.fill)l=e.fill;if(e.strokeWidth)m=e.strokeWidth;p&&(b=c*k,d[p+"_"+b]||(d[p+"_"+b]=a(p,b)),strokeRGB=p,k=b,p=d[p+"_"+b]);l&&(b=c*h,d[l+"_"+b]||(d[l+"_"+b]=a(l,b)),fillRGB=l,h=b,l=d[l+"_"+b]);return{strokeStyle:p,fillStyle:l,lineWidth:m,fillRGB:fillRGB,strokeRGB:strokeRGB,fillOpacity:h,strokeOpacity:k}}};khtml.maplib.overlay.FeatureCollection=function(){this.type="Feature";this.className="";this.realLayer=!1;this.properties={};this.geometry={};this.geometry.type="FeatureCollection";this.features=[];this.overlayDiv=document.createElement("div");this.overlayDiv.setAttribute("kazalabas","eluag");this.style=this.overlayDiv.style;this.className=this.overlayDiv.className;this.init=function(a){this.owner=a;if(a instanceof khtml.maplib.base.Map)this.map=a,this.map.overlayDiv.appendChild(this.overlayDiv);
else if(a.map)this.map=a.map,this.owner.overlayDiv.appendChild(this.overlayDiv);else return;this.makeVectorLayer();for(var e in this.features){if(!this.features[e].map){var d=this.features[e];d.type=="Marker"?d.init(this):d.geometry.type=="FeatureCollection"||d.geometry.type=="GroundOverlay"?d.init(this):(this.vectorLayer.createPolyline(d),this.vectorLayer.render(d))}this.extendBBox(d)}this.owner&&this.owner.extendBBox&&this.owner.extendBBox(this)};this.makeVectorLayer=function(){if(!this.vectorLayer&&
this.owner)this.owner.vectorLayer&&!this.realLayer?this.vectorLayer=this.owner.vectorLayer:(this.vectorLayer=new khtml.maplib.overlay.Vector,this.map&&this.vectorLayer.init(this))};this.oldStyleDisplay=null;this.render=function(){this.overlayDiv.parentNode||this.owner.overlayDiv.appendChild(this.overlayDiv);for(var a=0;a<this.features.length;a++)this.features[a]&&(this.features[a].geometry.type=="Point"&&this.features[a].render(),this.features[a].geometry.type=="FeatureCollection"&&this.features[a].render(),
this.features[a].geometry.type=="GroundOverlay"&&this.features[a].render());this.vectorLayer&&this.vectorLayer.render();if(this.oldStyleDisplay!=null)this.style.display=this.oldStyleDisplay;this.oldStyleDisplay=null};this.clear=function(){this.owner.overlayDiv.removeChild(this.overlayDiv);if(this.oldStyleDisplay==null)this.oldStyleDisplay=this.style.display,this.style.display="none";for(var a=0;a<this.features.length;a++)this.features[a].type=="Marker"&&this.features[a].clear(),this.features[a].geometry.type==
"FeatureCollection"&&!this.realLayer&&this.features[a].clear()};this.removeChild=function(a){for(var e in this.features)this.features[e]==a&&this.features.splice(e,1);this.render()};this.appendChild=function(a){this.features.push(a);if(a.geometry)a.geometry.type!=="Point"&&a.geometry.type!=="FeatureCollection"&&a.geometry.type!=="GroundOverlay"?this.vectorLayer&&(this.vectorLayer.createPolyline(a),this.vectorLayer.render(a)):(a.owner=this,a.owner.map&&(a.init(this),a.render())),this.extendBBox(a),
this.owner&&this.owner.extendBBox&&this.owner.extendBBox(a)};this.extendBBox=function(a){if(a=a.point?a.point:a.bbox)this.bbox=khtml.maplib.base.helpers.extendBBox(this.bbox,a)}};khtml.maplib.geometry.Feature=function(a){this.type="Feature";this.geometry={};this.geometry.coordinates=[];this.properties={};this.events={};this.style={};this.className={};this.className.baseVal="khtml_vector_line";if(typeof a=="object"&&a.type)if(a.type=="Feature"){this.geometry.type=a.geometry.type;this.geometry.coordinates=khtml.maplib.base.helpers.parseLine(a.geometry.coordinates);if(a.className)this.className.baseVal=a.className.baseVal;if(a.geometry.type=="FeatureCollection"){for(var e=new khtml.maplib.overlay.FeatureCollection,
d=0;d<a.features.length;d++)e.appendChild(new khtml.maplib.geometry.Feature(a.features[d]));return e}}else if(this.geometry.type=a.type,a.coordinates)this.geometry.coordinates=khtml.maplib.base.helpers.parseLine(a.coordinates);if(typeof a=="string")this.geometry.type=a;this.setPoints=function(b){this.geometry.coordinates=khtml.maplib.base.helpers.parseLine(b)};this.geojson=function(){return khtml.maplib.base.helpers.stringify(this)}};khtml.maplib.parser.MapCSS=function(){function a(a){return a.replace(/^\s+/,"").replace(/\s+$/,"")}this.size="width:16px;height:16px;";this.mapcss=document.styleSheets[0]?document.styleSheets[0]:document.createStyleSheet("dyn css","projection,tv,screen");this.parse=function(e){var d=0,b="";e=("__"+e+"__").split("");var g={singleQuote:!1,doubleQuote:!1,regex:!1,blockComment:!1,lineComment:!1,condComp:!1},f=0;for(b=e.length;f<b;f++)if(g.regex){if(e[f]==="/"&&e[f-1]!=="\\")g.regex=!1}else if(g.singleQuote){if(e[f]===
"'"&&e[f-1]!=="\\")g.singleQuote=!1}else if(g.doubleQuote){if(e[f]==='"'&&e[f-1]!=="\\")g.doubleQuote=!1}else if(g.blockComment){if(e[f]==="*"&&e[f+1]==="/")e[f+1]="",g.blockComment=!1;e[f]=""}else if(g.lineComment){if(e[f+1]==="\n"||e[f+1]==="\r")g.lineComment=!1;e[f]=""}else if(g.condComp){if(e[f-2]==="@"&&e[f-1]==="*"&&e[f]==="/")g.condComp=!1}else if(g.doubleQuote=e[f]==='"',g.singleQuote=e[f]==="'",e[f]==="/")e[f+1]==="*"&&e[f+2]==="@"?g.condComp=!0:e[f+1]==="*"?(e[f]="",g.blockComment=!0):e[f+
1]==="/"?(e[f]="",g.lineComment=!0):g.regex=!0;e=e.join("").slice(2,-2);var c=e.split(/\r\n|\r|\n/);e=[];for(g=0;g<c.length;g++)f=!1,b=a(c[g]).split(/{/),b[1]&&(f=b[1].split(/}/)[0],b="",f&&(e[d]=b+c[g],d++));for(g=0;g<e.length;g++)if(b=e[g].split(/{/),b[1]){f=a(b[1].split(/}/)[0]);d=b[0];selectors=d.split(",");newstring="";for(b=0;b<selectors.length;b++){c=newstring;var k=selectors[b],h=k.split("["),l=h[0].split("|");l[1]&&(l=l[1],l=l.substring(1,l.length),l.split("-"),l.split("-")[1]&&l.split("-"));
l=h[0].substring(0,4)=="node"?"div.osm_marker":"path";for(var p=1;p<h.length;p++){var m=h[p],q=m.split("]")[0];q=q.split("|")[0];m=m.split("]")[1].split(":");q=q.replace(":","_");m=/[0-9a-zA-Z=_]*/;m=/^[0-9a-zA-Z=_]*$/;m.test(q)&&(l+="[mapcss_"+q+"]")}if((m=k.split(":"))&&m[1])m[1]=a(m[1]),m[1]=="hover"&&(l+=" :"+m[1],console.log(l));newstring=c+(l+",")}b=newstring=newstring.substring(0,newstring.length-1);f=f.split(";");c="";for(k=0;k<f.length;k++)if(h="",l=f[k])p=l.split(":"),p[1]&&(l=a(p[0]),p=
a(p[1]),l=="fill-color"&&(l="fill"),l=="color"&&(l="stroke"),l=="width"&&(l="stroke-width"),l=="icon-image"&&(l="background-image",p="url("+p+")",h="width:16px;height:16px;"),c+=l+":"+p+";"+h);f=c;c=1;k=18;d=d.split("[")[0];if(d.split("|").length>0&&(d=d.split("|")[1]))d=d.substring(1,d.length),d=d.split("-")[0],c=d[0],d[1]&&(k=d[1]);for(d=c;d<=k;d++)if(b!="path"&&b!="div"){h=".z"+d+" "+b+" {"+f+"}";if(c!=1||k!=18)h=".z"+d+" "+b+" {"+f+"}";else{h=b+" {"+f+"}";this.mapcss.insertRule(h,0);break}this.mapcss.insertRule(h,
0)}}}};khtml.maplib.parser.Osm=function(){this.featureCollection=new khtml.maplib.overlay.FeatureCollection;this.nodes=[];this.ways=[];this.data=function(){return this.featureCollection};this.add=function(a){for(var e=a.getElementsByTagName("node"),d=0;d<e.length;d++){var b=e[d],g=b.getAttribute("id");if(!this.nodes[g]){var f=b.getElementsByTagName("tag");b=new khtml.maplib.LatLng(b.getAttribute("lat"),b.getAttribute("lon"));this.nodes[g]=b;g=document.createElement("div");if(f.length>0){var c=new khtml.maplib.overlay.Marker(b,
g);c.properties={};for(b=0;b<f.length;b++){var k=f[b],h=k.getAttribute("k");k=k.getAttribute("v");g.setAttribute("mapcss_"+h,k);c.properties[h]=k}g.className="osm_marker";this.featureCollection.appendChild(c)}}}a=a.getElementsByTagName("way");for(e=0;e<a.length;e++)if(f=a[e],g=f.getAttribute("id"),!this.ways[g]){d=new khtml.maplib.geometry.Feature("Polyline");d.close=!0;d.id=g;b=f.getElementsByTagName("nd");for(h=0;h<b.length;h++)k=b[h].getAttribute("ref"),d.geometry.coordinates.push(this.nodes[k]);
f=f.getElementsByTagName("tag");for(b=0;b<f.length;b++)k=f[b],h=k.getAttribute("k"),k=k.getAttribute("v"),d.properties[h]=k;this.featureCollection.appendChild(d);this.ways[g]=d}}};khtml.maplib.overlay.WMS=function(a){console.log(a);this.type="Feature";this.geometry={};this.geometry.type="WMS";this.options=a;this.delayTimeout=null;this.init=function(a){this.owner=a;this.map=this.owner.map instanceof khtml.maplib.Map?this.owner.map:a;console.log(this.map);this.img=document.createElement("img");this.div=document.createElement("div");this.div.style.opacity=0.6;a=this.map.bounds().getCenter();console.log(a);console.log({dx:-this.map.mapsize.width/2,dy:-this.map.mapsize.height/2});
var b=-this.map.mapsize.width/2,e=-this.map.mapsize.height/2;console.log(b,e);this.div.appendChild(this.img);this.img.style.position="absolute";this.img.style.top=e+"px";this.img.style.left=b+"px";this.marker=new khtml.maplib.overlay.Marker(a,this.div);this.map.featureCollection.appendChild(this.marker)};this.oldZoom=0;this.clear=function(){e.marker.style.display="none";console.log("was ist das",e.map.featureCollection);e.map.featureCollection.removeChild(e.marker)};this.render=function(){if(map.finalDraw){this.marker.geometry.coordinates=
this.map.bounds().getCenter();var a=this.map.bounds().sw().lat(),b=this.map.bounds().ne().lat(),e=this.map.bounds().sw().lng(),f=this.map.bounds().ne().lng(),c=this.map.mapsize.width,k=this.map.mapsize.height,h="",l;for(l in this.options.layers)h+=this.options.layers[l]+",";h=h.substring(0,h.length-1);this.img.setAttribute("src",this.options.url+"?SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.0&FORMAT="+(this.options.parameters.FORMAT?this.options.parameters.FORMAT:"image/png")+"&SRS=EPSG%3A4326&TILED=false&LAYERS="+
h+"&BBOX="+e+","+a+","+f+","+b+"&WIDTH="+c+"&HEIGHT="+k);this.img.style.display="none";khtml.maplib.base.helpers.eventAttach(this.img,"load",this._imgLoaded,this.marker,!1)}else{if(this.oldZoom!=this.map.zoom())this.marker.style.display="none";this.oldZoom=this.map.zoom()}};var e=this;this._imgLoaded=function(){console.log("loaded");this.render();this.marker.style.display="";e.img.style.display=""}};khtml.maplib.overlay.GroundOverlay=function(a,e,d){this.geometry={};this.geometry.type="GroundOverlay";this.type="Feature";this._createRenderElement=function(){var b=document.createElement("div");b.appendChild(this.el);b.style.position="absolute";b.style.top="0px";b.style.left="0px";if(this.options){if(this.options.dy)b.style.top=this.options.dy;if(this.options.dx)b.style.left=this.options.dx}return b};this._calcImageSize=function(){var b=this.map.latlngToXY(this.bbox.sw()),a=this.map.latlngToXY(this.bbox.ne()),
d=this.map.latlngToXY(this.bbox.nw());dx=a.x-b.x;dy=b.y-a.y;this.renderElement.style.width=dx;this.renderElement.style.height=dy;this.renderElement.style.left=d.x+"px";this.renderElement.style.top=d.y+"px";if((b=this.renderElement.getElementsByTagName("img")[0])&&b.tagName=="IMG")b.width=dx,b.height=dy};this.init=function(b){this.owner=b;this.map=b instanceof khtml.maplib.base.Map?b:b.map;khtml.maplib.base.helpers.rotate(this.renderElement,this.rotation*-1)};this.render=function(){this.renderElement&&
this.point&&!isNaN(this.point.lat())&&!isNaN(this.point.lng())&&this.map&&(null==this.renderElement.parentNode&&this.owner.overlayDiv.appendChild(this.renderElement),this._calcImageSize())};this.bounds=function(){if(this.rotation){khtml.maplib.base.Log.log("lng: "+this.bbox.sw().lng()+"; lat:"+this.bbox.sw().lat());var b=this._transformPoint(this.bbox.sw());khtml.maplib.base.Log.log("lng: "+b.lng()+"; lat:"+b.lat());var a=this._transformPoint(this.bbox.se()),d=this._transformPoint(this.bbox.ne()),
c=this._transformPoint(this.bbox.nw()),e=Math.min(b.lng(),a.lng(),d.lng(),c.lng()),h=Math.min(b.lat(),a.lat(),d.lat(),c.lat()),l=Math.max(b.lng(),a.lng(),d.lng(),c.lng());b=Math.max(b.lat(),a.lat(),d.lat(),c.lat());khtml.maplib.base.Log.log("in bounds");return new khtml.maplib.geometry.Bounds(new khtml.maplib.LatLng(h,e),new khtml.maplib.geometry.Point(b,l))}else return this.bbox};this._transformPoint=function(b){var a=this.bbox.getCenter(),d=a.lng();a=a.lat();var c=this.rotation*Math.PI/180;khtml.maplib.base.Log.log("theta: "+
c);khtml.maplib.base.Log.log("rotation: "+this.rotation);var e=b.lng();b=b.lat();b=new khtml.maplib.LatLng(a-(e-d)*Math.sin(c)+(b-a)*Math.cos(c),d+(e-d)*Math.cos(c)+(b-a)*Math.sin(c));d=new khtml.maplib.overlays.Marker(b,"http://www.din-5008-richtlinien.de/bilder/punkt.gif",{dx:-1,dy:-1});map.addOverlay(d);return b};this.position=function(b){if(b)this.point=b;return this.point};this.clear=function(){};this.makeMoveable=function(){khtml.maplib.base.helpers.eventAttach(this.renderElement,"mousedown",
this.down,this,!1);khtml.maplib.base.helpers.eventAttach(window,"mousemove",this.move,this,!0);khtml.maplib.base.helpers.eventAttach(window,"mouseup",this.up,this,!0)};this.moving=!1;this.dy=this.dx=0;this.down=function(b){this.moving=!0;this.dx=this.renderElement.offsetLeft-this._map.pageX(b);this.dy=this.renderElement.offsetTop-this._map.pageY(b)};this.move=function(b){if(this.moving){var a=this._map.pageX(b)+this.dx,d=this._map.pageY(b)+this.dy;this.point=this._map.XYTolatlng(a,d);this.render();
b.stopPropagation()}};this.up=function(){this.moving=!1};this.options=d;this.el=e;this.bbox=a;this.point=this.bbox.nw();if(d!=void 0&&d.rotation!=void 0)this.rotation=d.rotation;this.renderElement=this._createRenderElement()};khtml.maplib.parser.Gpx=function(a,e){this.parse=function(){for(var a=new khtml.maplib.overlay.Vector,b=this.dom.getElementsByTagName("trkseg"),g=0;g<b.length;g++){for(var f=[],c=b.item(g).getElementsByTagName("trkpt"),k=0;k<c.length;k++){var h=c.item(k),l=parseFloat(h.getAttribute("lat"));h=parseFloat(h.getAttribute("lon"));f.push(new khtml.maplib.LatLng(l,h))}f=a.createPolyline(f);this.classname?f.className=e:(f.style.fill="none",f.style.stroke="blue",f.style.strokeWidth="2")}return a};this.setDom=
function(a){this.dom=typeof a=="string"?khtml.maplib.base.helpers.parseXml(a):a};this.setClassname=function(a){this.classname=a};this.classname=e?e:"";this.setDom(a)};khtml.maplib.parser.Kml=function(a){function e(a){var b=parseInt(a.substring(0,2),16)/256,e=parseInt(a.substring(2,4),16),f=parseInt(a.substring(4,6),16);a=parseInt(a.substring(6,8),16);return"rgba("+e+","+f+","+a+","+b+")"}this.parsed=null;this.styles=[];this.parse=function(a){if(a||null==this.parsed){if(!this.dom)return!1;if(this.dom.hasChildNodes)this.parsed=this.parseNode(this.dom.documentElement)}return this.parsed};this.parseNode=function(a){if(!a)return!1;var b=null,e=null;switch(a.nodeName){case "xml":case "#document":if(khtml.maplib.base.helpers.isIE()&&
a.childNodes.length>1)return this.parseNode(a.childNodes[1]);return this.parseNode(a.childNodes[0]);case "kml":return this.parseNode(a.getElementsByTagName("*").item(0));case "Document":b=this.parseDocument(a);break;case "Folder":"Folder"==a.nodeName&&(e=this.parseFolder(a));null==b?b=e:b.appendChild(e);break;case "Placemark":b.appendChild(this.parsePlacemark(a));break;case "GroundOverlay":null==b&&(b=new khtml.maplib.overlay.FeatureCollection),b.appendChild(this.parseGroundOverlay(a))}return b};
this.parseFolder=function(a){for(var b=new khtml.maplib.overlay.FeatureCollection,e=0;e<a.childNodes.length;e++)switch(a.childNodes[e].nodeName){case "name":b.properties.name=a.childNodes[e].childNodes[0].nodeValue;break;case "visibility":b.visible(parseInt(a.childNodes[e].childNodes[0].nodeValue)==1);break;case "description":b.properties.description=a.childNodes[e].childNodes[0].nodeValue;break;case "Folder":b.appendChild(this.parseFolder(a.childNodes[e]));break;case "Placemark":b.appendChild(this.parsePlacemark(a.childNodes[e]));
break;case "GroundOverlay":b.appendChild(this.parseGroundOverlay(a.childNodes[e]))}return b};this.parseDocument=function(a){for(var b=new khtml.maplib.overlay.FeatureCollection,e=0;e<a.childNodes.length;e++)if(a.childNodes[e].nodeType==1)switch(a.childNodes[e].nodeName){case "name":b.name=a.childNodes[e].childNodes[0].nodeValue;break;case "open":b.attribute("open",a.childNodes[e].childNodes[0].nodeValue);break;case "visibility":b.visible(parseInt(a.childNodes[e].childNodes[0].nodeValue)==1);break;
case "description":b.properties.description=a.childNodes[e].childNodes[0].nodeValue;break;case "Style":this.parseStyle(a.childNodes[e]);break;case "Folder":b.appendChild(this.parseFolder(a.childNodes[e]));break;case "GroundOverlay":b.addContent(this.parseGroundOverlay(a.childNodes[e]),!0);break;case "Placemark":var f=this.parsePlacemark(a.childNodes[e]);(f.type=="Feature"||f.type=="Marker")&&b.appendChild(f)}return b};this.parseStyle=function(a){if(!a)return!1;var b=a.getAttribute("id");this.styles[b]||
(this.styles[b]=[]);for(var g=0;g<a.childNodes.length;g++){var f=a.childNodes[g];if(f.nodeType==1){var c={};c.fill="none";c.stroke="rgba(255,0,0,0.48828125)";c.strokeWidth=3;this.styles[b][c.tagName]=c;for(var k=0;k<f.childNodes.length;k++)if(f.childNodes[k].nodeType==1){var h=f.childNodes[k].tagName;if(f.childNodes[k].firstChild)switch(h){case "color":if(f.nodeName=="LineStyle")c.stroke=e(f.childNodes[k].firstChild.nodeValue);if(f.nodeName=="PolyStyle")c.fill=e(f.childNodes[k].firstChild.nodeValue);
break;case "width":if(f.nodeName=="LineStyle")c.strokeWidth=f.childNodes[k].firstChild.nodeValue;if(f.nodeName=="PolyStyle")c.strokeWidth=f.childNodes[k].firstChild.nodeValue;break;default:console.log("not implemented",h,f[k])}}this.styles[b][f.tagName]=c}}return!1};this.parseGroundOverlay=function(a){if(!a)return!1;if(!a.nodeName=="GroundOverlay")return!1;var b=this.parseIcon(a),e=a.getElementsByTagName("LatLonBox")[0],f=e.getElementsByTagName("north")[0].childNodes[0].nodeValue,c=e.getElementsByTagName("east")[0].childNodes[0].nodeValue,
k=e.getElementsByTagName("south")[0].childNodes[0].nodeValue,h=e.getElementsByTagName("west")[0].childNodes[0].nodeValue;a={};if(e.getElementsByTagName("rotation")[0]!=void 0)e=e.getElementsByTagName("rotation")[0].childNodes[0].nodeValue,a.rotation=parseFloat(e);f=new khtml.maplib.geometry.Bounds(new khtml.maplib.LatLng(k,h),new khtml.maplib.LatLng(f,c));return new khtml.maplib.overlay.GroundOverlay(f,b,a)};this.parsePlacemark=function(a){if(!a)return!1;var b={};b.visibility=!0;for(var e=0;e<a.childNodes.length;e++){switch(a.childNodes[e].nodeName){case "name":if(a.childNodes[e].childNodes.length>
0&&typeof a.childNodes[e].childNodes[0].nodeValue!="undefined")b.name=a.childNodes[e].childNodes[0].nodeValue;break;case "description":if(a.childNodes[e].childNodes.length>0&&typeof a.childNodes[e].childNodes[0].nodeValue!="undefined")b.description=a.childNodes[e].childNodes[0].nodeValue;break;case "Point":b=this.parsePoint(a.childNodes[e]);break;case "LineString":b=this.parseLineString(a.childNodes[e]);break;case "Polygon":b=this.parsePolygon(a.childNodes[e]);break;case "gx:drawOrder":b.gxdraworder=
a.childNodes[e];break;case "visibility":b.visibility=parseInt(a.childNodes[e].childNodes[0].nodeValue)==1}var f=a.getElementsByTagName("styleUrl");if(f.length>0&&f[0].firstChild)f=f[0].firstChild.nodeValue,f.substring(1,f.length)}try{var c=a.getElementsByTagName("name").item(0).firstChild.nodeValue;b.properties.name=c}catch(k){}try{var h=a.getElementsByTagName("description").item(0).firstChild.nodeValue;b.properties.description=h}catch(l){}return b};this.parseLineString=function(a){try{var b=a.parentNode.getElementsByTagName("styleUrl").item(0).firstChild.nodeValue;
b=b.substring(1,b.length)}catch(e){}if(!a)return!1;a=this.parseCoordinates(a);a=new khtml.maplib.geometry.Feature({type:"LineString",coordinates:a[0]});a.className.baseVal="kml_linestring";this.styles[b]?a.style=this.styles[b].LineStyle.style:(a.style.stroke="blue",a.style.strokeWidth=4);return a};this.parsePolygon=function(a){if(!a)return!1;try{var b=a.parentNode.getElementsByTagName("styleUrl").item(0).firstChild.nodeValue;b=b.substring(1,b.length)}catch(e){}for(var f=new khtml.maplib.geometry.Feature({type:"Polygon"}),
c=0;c<a.childNodes.length;c++)switch(a.childNodes[c].nodeName){case "outerBoundaryIs":var k=this.parseCoordinates(a.childNodes[c]);f.geometry.coordinates=k[0];break;case "innerBoundaryIs":this.parseCoordinates(a.childNodes[c])}f.className+=" kml_polygon";if(this.styles[b])f.style=this.styles[b].PolyStyle;return f};this.parseCoordinates=function(a){a=a.getElementsByTagName("coordinates");var b=[];a.length==0&&(b[0]=[],b[0][0]=null);for(var e=0;e<a.length;e++){b[e]=[];for(var f="",c=0;c<a[e].childNodes.length;c++){var k=
a[e].childNodes[c].nodeValue;k!=null&&k.length>0&&(f+=k.trim())}f=f.split(/\s/);for(k=c=0;k<f.length;k++){var h=f[k].trim();h.length>0&&(h=h.split(","),b[e][c]=new khtml.maplib.LatLng(h[1],h[0]),c++)}}return b};this.parsePoint=function(a){var b=document.createElement("img");b.setAttribute("src","http://maps.google.com/mapfiles/kml/shapes/placemark_circle_highlight.png");a=(new this.parseCoordinates(a))[0][0];return new khtml.maplib.overlay.Marker(a,b)};this.parseIcon=function(a){var b=this._imgBasePath+
a.getElementsByTagName("href")[0].childNodes[0].nodeValue,e=null,f=document.createElement("img");f.setAttribute("src",b);if(a.getElementsByTagName("gx:x").length!=0||a.getElementsByTagName("gx:y").length!=0||a.getElementsByTagName("gx:w").length!=0||a.getElementsByTagName("gx:h").length!=0){e=document.createElement("div");b=a.getElementsByTagName("gx:w")[0].childNodes[0].nodeValue;var c=a.getElementsByTagName("gx:h")[0].childNodes[0].nodeValue;e.setAttribute("style","overflow: hidden; position: absolute; width: "+
b+"px; height: "+c+"px;");e.naturalWidth=b;e.naturalHeight=c;b=a.getElementsByTagName("gx:x")[0].childNodes[0].nodeValue;a=a.getElementsByTagName("gx:y")[0].childNodes[0].nodeValue;f.setAttribute("style","position: absolute; left: -"+b+"px; bottom: -"+a+"px;");f.naturalLeft=b*-1;f.naturalBottom=a*-1;e.appendChild(f)}else e=f;return e};this.generateFeature=function(){return!1};this.getMarkerForFeature=function(){return new khtml.maplib.displayable.ImageMarker(this.imageMarkerUrl())};this.setDom=function(a){this.dom=
typeof a=="string"?khtml.maplib.base.helpers.parseXml(a):a};this.imgBasePath=function(a){if(typeof a!="undefined")this._imgBasePath=a;return this._imgBasePath};this.imageMarkerUrl=function(a){if(typeof a!="undefined")this._imageMarkerUrl=a;return this._imageMarkerUrl};this.layers=[];this.folders=[];this._imgBasePath="";this.imageMarkerUrl("http://thydzik.com/thydzikGoogleMap/markerlink.php?color=5680FC");this.setDom(a)};khtml.maplib.base.Map.prototype.keypress=function(a){var e=!0;switch(a.keyCode){case 37:this.moveit(30,0);break;case 38:this.moveit(0,30);break;case 39:this.moveit(-30,0);break;case 40:this.moveit(0,-30);break;default:e=!1}if(e)return!0;e=typeof a.which!="undefined"?a.which:a.charCode;if(this.internetExplorer)e=a.keyCode;switch(e){case 43:a=Math.ceil(this.getZoom()+0.01)-this.getZoom();this.autoZoomIn(this.mapsize.width/2,this.mapsize.height/2,a);break;case 45:a=Math.floor(this.getZoom()-0.01)-this.getZoom(),
this.autoZoomIn(this.mapsize.width/2,this.mapsize.height/2,a)}return!0};khtml.maplib.base.Map.prototype.keyup=function(){};khtml.maplib.base.Map.prototype.moveit=function(a,e){for(var d=a/20,b=e/20,g=0;g<20;g++){var f=Math.cos(3*(-10+g)/20)*5;this.moveitexec(d*f,b*f,g)}};khtml.maplib.base.Map.prototype.moveitexec=function(a,e,d){var b=this;setTimeout(function(){b.moveXY(a,e)},20*d)};khtml.maplib.ui.Zoombar=function(){this._cancelEvent=function(a){a.cancelBubble=!0;a.stopPropagation&&a.stopPropagation()};this._stopEventPropagation=function(a){a.preventDefault?a.preventDefault():a.returnValue=!1};this._calcZFromY=function(a){return 22-a/10};this._zoom=function(a){this.themap.zoom(this._calcZFromY(this.themap.pageY(a)))};this.init=function(a){this.themap=a;a=a.mapParent.getElementsByTagName("*");for(var e=0;e<a.length;e++){var d=a.item(e);if(d.className=="scrollhandle")this.scrollhandle=
d;if(d.className=="zoombar")this.zoombar=d}khtml.maplib.base.helpers.eventAttach(this.zoombar,"mousedown",this.down,this,!1);khtml.maplib.base.helpers.eventAttach(this.zoombar,"mousemove",this.move,this,!1);khtml.maplib.base.helpers.eventAttach(this.zoombar,"mouseup",this.up,this,!1)};this.render=function(){this.scrollhandle.style.marginTop=(22-this.themap.zoom())*10+"px"};this.down=function(a){this._cancelEvent(a);this.moving=!0;this._zoom(a);this._stopEventPropagation(a)};this.move=function(a){this._cancelEvent(a);
this.moving&&(this._zoom(a),this._stopEventPropagation(a))};this.up=function(a){this._cancelEvent(a);this.moving=!1;this._stopEventPropagation(a)}};khtml.maplib.util.Http=function(){this._get=function(a,e,d,b){try{return jQuery.get(a,e,d,b)}catch(g){khtml.maplib.base.Log.warn("Exception occured! Did you include the jQuery library?"),khtml.maplib.base.Log.exception(g)}};this.get=function(a,e,d,b){return this._get(a,e,d,b).error(function(a){khtml.maplib.base.Log.error("khtml.maplib.util.Http.get(): request failed!",a)})}};
