// --------------------------------------------------------------------------------------------
// khtml javascript library
// --------------------------------------------------------------------------------------------
// (C) Copyright 2010-2011 by Bernhard Zwischenbrugger, Florian Hengartner, Stefan Kemper
//
// Project Info:  http://www.khtml.org
//				  http://www.khtml.org/iphonemap/help.php
//
// This library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with this library.  If not, see <http://www.gnu.org/licenses/>.
// --------------------------------------------------------------------------------------------
var khtml={};khtml.maplib={};khtml.maplib.base={};khtml.maplib.geometry={};khtml.maplib.overlay={};khtml.maplib.overlay.renderer={};khtml.maplib.parser={};khtml.maplib.ui={};khtml.maplib.util={};khtml.maplib.overlay.renderer={};khtml.maplib.version=function(){return"khtmlib_hsr v0.02"};khtml.maplib.Map=function(a){return new khtml.maplib.base.Map(a)};khtml.maplib.LatLng=function(a,b){return new khtml.maplib.geometry.LatLng(a,b)};khtml.maplib.standardimagepath="http://maplib.khtml.org/img/";khtml.maplib.base.helpers={};khtml.maplib.base.helpers.parseXml=function(a){var b;window.ActiveXObject?(b=new ActiveXObject("Microsoft.XMLDOM"),b.async=!1,b.loadXML(a)):document.implementation&&document.implementation.createDocument&&(b=(new DOMParser).parseFromString(a,"text/xml"));return b};
khtml.maplib.base.helpers.contains=function(a,b){var d=[a.sw().lat(),a.ne().lat()],e=[a.sw().lng(),a.ne().lng()];return(khtml.maplib.base.helpers.between(d,b.sw().lat())||khtml.maplib.base.helpers.between(d,b.ne().lat()))&&(khtml.maplib.base.helpers.between(e,b.sw().lng())||khtml.maplib.base.helpers.between(e,b.ne().lng()))?!0:!1};khtml.maplib.base.helpers.overlaps=function(a,b){return a.sw().lng()>b.ne().lng()||a.ne().lng()<b.sw().lng()||a.sw().lat()>b.ne().lat()||a.ne().lat()<b.sw().lat()?!1:!0};
khtml.maplib.base.helpers.overlapsBuggy=function(a,b){var d=[a.sw().lat(),a.ne().lat()],e=[a.sw().lng(),a.ne().lng()],g=[b.sw().lat(),b.ne().lat()],h=[b.sw().lng(),b.ne().lng()];return(khtml.maplib.base.helpers.between(d,b.sw().lat())||khtml.maplib.base.helpers.between(d,b.ne().lat()))&&(khtml.maplib.base.helpers.between(e,b.sw().lng())||khtml.maplib.base.helpers.between(e,b.ne().lng()))||(khtml.maplib.base.helpers.between(g,a.sw().lat())||khtml.maplib.base.helpers.between(g,a.ne().lat()))&&(khtml.maplib.base.helpers.between(h,
a.sw().lng())||khtml.maplib.base.helpers.between(h,a.ne().lng()))?!0:!1};
khtml.maplib.base.helpers.extendBBox=function(a,b){if(!(a instanceof khtml.maplib.geometry.Bounds)){var d=new khtml.maplib.geometry.LatLng(-80,-170),e=new khtml.maplib.geometry.LatLng(90,180);a=new khtml.maplib.geometry.Bounds(e,d);a.sw(e);a.ne(d)}if(!b)return a;b instanceof khtml.maplib.geometry.LatLng?a=khtml.maplib.base.helpers.extendBBoxByPoint(a,b):(a=khtml.maplib.base.helpers.extendBBoxByPoint(a,b.sw()),a=khtml.maplib.base.helpers.extendBBoxByPoint(a,b.ne()));return a};
khtml.maplib.base.helpers.extendBBoxByPoint=function(a,b){var d=a.sw().lng(),e=a.ne().lat(),g=a.sw().lat(),h=a.ne().lng();b.lat()>e&&(e=b.lat());b.lat()<g&&(g=b.lat());b.lng()<d&&(d=b.lng());b.lng()>h&&(h=b.lng());d=new khtml.maplib.geometry.LatLng(g,d);e=new khtml.maplib.geometry.LatLng(e,h);return new khtml.maplib.geometry.Bounds(d,e)};khtml.maplib.base.helpers.between=function(a,b){return a[0]<=b&&b<=a[1]?!0:!1};
khtml.maplib.base.helpers.cloneObject=function(a){var b={},d;for(d in a)b[d]=typeof a[d]=="object"?khtml.maplib.base.helpers.cloneObject(a[d]):a[d];return b};khtml.maplib.base.helpers.convertObjectToArray=function(a){for(var b=[],d=0,e=a.length;d<e;d++)b.push(a[d]);return b};
khtml.maplib.base.helpers.eventAttach=function(a,b,d,e,g){var h=arguments.length>5?$a(arguments).slice(5,arguments.length):[],c=function(c){h.unshift(c||window.event);return d.apply(e?e:a,h)};a.addEventListener?(navigator.appName.indexOf("Netscape")==-1&&b=="DOMMouseScroll"&&(b="mousewheel"),navigator.userAgent.indexOf("Safari")!=-1?b=="DOMMouseScroll"?a.onmousewheel=c:a.addEventListener(b,c,g):a.addEventListener(b,c,g)):(b=b=="DOMMouseScroll"?"onmousewheel":"on"+b,a.attachEvent(b,c));return{o:a,
type:b,fn:c,c:g}};khtml.maplib.base.helpers.eventRemove=function(a){a.o.removeEventListener&&a.o.removeEventListener(a.type,a.fn,a.c)};khtml.maplib.base.helpers.mixin=function(a,b,d){if(d)if(d instanceof Array)for(var e=0;e<d.length;e++)a[d[e]]=b[d[e]];else b[d]&&(a[d]=b[d]);else for(e in b)a[e]=b[e]};
khtml.maplib.base.helpers.showOnMap=function(a,b){var d=[];a instanceof khtml.maplib.geometry.Bounds&&(khtml.maplib.base.Log.log("Bounds"),khtml.maplib.base.Log.log("Northwest / Topleft",a.nw()),khtml.maplib.base.Log.log("Northeast / Topright",a.ne()),khtml.maplib.base.Log.log("Southeast / Bottomright",a.se()),khtml.maplib.base.Log.log("Southwest / Bottomleft",a.sw()),d.push(a.nw()),d.push(a.ne()),d.push(a.se()),d.push(a.sw()));for(var e=0;e<d.length;e++){var g=document.createElement("div");g.style.width=
"1px";g.style.height="1px";g.style.color="red";g.style["font-size"]="2em";g.textContent="X";g=new khtml.maplib.overlay.Marker(d[e],g);b.addOverlay(g)}};khtml.maplib.base.helpers.cancelEvent=function(a){a.cancelBubble=!0;a.stopPropagation&&a.stopPropagation()};khtml.maplib.base.helpers.stopEventPropagation=function(a){a.preventDefault?a.preventDefault():a.returnValue=!1};khtml.maplib.base.helpers.isIE=function(){return navigator.userAgent.indexOf("MSIE")!=-1};
khtml.maplib.base.helpers.isParentNodeEmpty=function(a){if(khtml.maplib.base.helpers.isIE())return a.parentNode.nodeValue==null;return!a.parentNode};
khtml.maplib.base.helpers.parseLine=function(a){if(a instanceof khtml.maplib.geometry.LatLng)return a;if(a){if(typeof a=="string")a=khtml.maplib.base.helpers.parseLineString;if(typeof a=="object"){if(typeof a[0]=="string"&&typeof a[1]=="string"&&!isNaN(parseFloat(a[0]))&&!isNaN(parseFloat(a[1]))&&a.length==2){var b=parseFloat(a[1]),d=parseFloat(a[0]),e=khtml.maplib.LatLng(b,d);return e}if(typeof a[0]=="number"&&typeof a[0]=="number"&&a.length==2)a=new khtml.maplib.LatLng(a[0],a[1]);else for(e in a){var g=
a[e];g instanceof khtml.maplib.geometry.LatLng||(b=g[1],d=g[0],a[e]=typeof b=="number"&&typeof d=="number"&&g.length==2?new khtml.maplib.LatLng(b,d):khtml.maplib.base.helpers.parseLine(a[e]))}b=a}}else b=[];return b};khtml.maplib.base.helpers.parseLineString=function(a){if(typeof a=="string"){points=[];a=a.split(" ");for(var b=0;b<a.length;b++){var d=a[b].split(",");d.length==2&&(d[0]=parseFloat(d[0]),d[1]=parseFloat(d[1]),points.push(new khtml.maplib.LatLng(d[0],d[1])))}}return points};
khtml.maplib.base.helpers.parseMultiLine=function(a){if(a&&typeof a=="object")for(var b in a){var d=a[b],e;for(e in d){var g=d[e];if(!(g instanceof khtml.maplib.geometry.LatLng)){var h=g[0];g=g[1];typeof h=="number"&&typeof g=="number"&&(d[e]=new khtml.maplib.LatLng(h,g))}}}else a=[];return a};var stop=0;
khtml.maplib.base.helpers.stringify=function(a,b,d){var e=!0;typeof a.push=="undefined"&&(e=!1);for(var g="",h=b?b+1:b===!1?!1:1,c=g="",n=0;n<h-1;n++)c+="   ";b!==!1&&(c="\n"+c,g=c+"   ");n="";for(var f in a)if(f!="owner"&&typeof a[f]!="function")if(a[f]instanceof khtml.maplib.geometry.Bounds)n+=g+'"bbox":',n+="["+a[f].sw().lng()+","+a[f].sw().lat()+",",n+=""+a[f].ne().lng()+","+a[f].ne().lat()+"]",n+=",";else if(a[f]instanceof khtml.maplib.geometry.LatLng)a.type!="Marker"&&(a.type=="Point"&&(n+=
'"coordinates":'),n+="["+a[f].lng()+","+a[f].lat()+"],");else if(typeof a[f]=="string"){if((f=="type"||d)&&f!="animVal")a[f]!="Marker"&&(n+=g+'"'+f+'":"'+a[f]+'",')}else if(console.log(f,b),e||f=="type"||f=="features"||a[f]&&a[f].type=="Feature"||f=="geometry"||f=="coordinates"||f=="properties"||f=="bbox"||f=="className")console.log(f,b),n+=e?g+khtml.maplib.base.helpers.stringify(a[f],h)+",":f=="properties"?g+'"'+f+'":'+khtml.maplib.base.helpers.stringify(a[f],h)+",":g+'"'+f+'":'+khtml.maplib.base.helpers.stringify(a[f],
h,!0)+",";n=n.substring(0,n.length-1);return e?"["+n+"]":"{"+n+c+"}"};khtml.maplib.base.helpers.rotate=function(a,b){var d="rotate("+b+"deg)";a.style.webkitTransform=d;a.style.MozTransform=d;a.style.OTransform=d;if(document.all)rad=b*(Math.PI*2/360),costheta=Math.cos(rad),sintheta=Math.sin(rad),a.filters.item(0).M11=costheta,a.filters.item(0).M12=-sintheta,a.filters.item(0).M21=sintheta,a.filters.item(0).M22=costheta};
khtml.maplib.base.helpers.Boundingbox=function(a){this.map=a;this.div=document.createElement("div");this.div.style.border="1px dotted blue";this.div.style.position="absolute";this.div.style.strokeDasharray="4,4";this.div.style.zIndex=1;this.div.style.pointerEvents="none";a.mapParent.appendChild(this.div);this.show=function(a){this.div.style.display="";var b=this.map.latlngToXY(a.sw());a=this.map.latlngToXY(a.ne());this.div.style.top=a.y-parseInt(this.div.style.borderWidth)+"px";this.div.style.left=
b.x-parseInt(this.div.style.borderWidth)+"px";this.div.style.width=a.x-b.x+"px";this.div.style.height=-a.y+b.y+"px";this.div.zIndex=10};this.hide=function(){b.div.style.display="none"};var b=this;this.map.addCallbackFunction(b.hide)};khtml.maplib.base.helpers.ajaxload="data:image/gif;base64,R0lGODlhEAAQAPIAAP///wAAAMLCwkJCQgAAAGJiYoKCgpKSkiH/C05FVFNDQVBFMi4wAwEAAAAh/hpDcmVhdGVkIHdpdGggYWpheGxvYWQuaW5mbwAh+QQJCgAAACwAAAAAEAAQAAADMwi63P4wyklrE2MIOggZnAdOmGYJRbExwroUmcG2LmDEwnHQLVsYOd2mBzkYDAdKa+dIAAAh+QQJCgAAACwAAAAAEAAQAAADNAi63P5OjCEgG4QMu7DmikRxQlFUYDEZIGBMRVsaqHwctXXf7WEYB4Ag1xjihkMZsiUkKhIAIfkECQoAAAAsAAAAABAAEAAAAzYIujIjK8pByJDMlFYvBoVjHA70GU7xSUJhmKtwHPAKzLO9HMaoKwJZ7Rf8AYPDDzKpZBqfvwQAIfkECQoAAAAsAAAAABAAEAAAAzMIumIlK8oyhpHsnFZfhYumCYUhDAQxRIdhHBGqRoKw0R8DYlJd8z0fMDgsGo/IpHI5TAAAIfkECQoAAAAsAAAAABAAEAAAAzIIunInK0rnZBTwGPNMgQwmdsNgXGJUlIWEuR5oWUIpz8pAEAMe6TwfwyYsGo/IpFKSAAAh+QQJCgAAACwAAAAAEAAQAAADMwi6IMKQORfjdOe82p4wGccc4CEuQradylesojEMBgsUc2G7sDX3lQGBMLAJibufbSlKAAAh+QQJCgAAACwAAAAAEAAQAAADMgi63P7wCRHZnFVdmgHu2nFwlWCI3WGc3TSWhUFGxTAUkGCbtgENBMJAEJsxgMLWzpEAACH5BAkKAAAALAAAAAAQABAAAAMyCLrc/jDKSatlQtScKdceCAjDII7HcQ4EMTCpyrCuUBjCYRgHVtqlAiB1YhiCnlsRkAAAOwAAAAAAAAAAAA%3D%3D";
khtml.maplib.base.helpers.close="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAABGdBTUEAALGOfPtRkwAAACBjSFJNAAB6JQAAgIMAAPn/AACA6QAAdTAAAOpgAAA6mAAAF2+SX8VGAAAA5ElEQVR42tRTQYoEIQwsl/2Bl3gQoY9eBKEf5kvyG8G7h4Z+S38gIu5lp5lZ2R7YPm1BDhZJSFWiGmPgDj5wE7cbfD4/mBkAHprUj9yTTyn9OsGIMSLG+Fxwxc8SiAi9d4QQHskjhIDeO4jorQcq5wwiQmsN3nt479FaAxEh5zxJmyZIKalSClprL1FKQUpJXZr4DBH52xqZeRhjICKw1sJaCxGBMQbMPN41GFpriAicc6i1otYK5xxEBFrraQuThGVZAADbtp2amXms6woAOI7j0gO17/t5MN+HNfEvBf//M30NAKe7aRqUOIlfAAAAAElFTkSuQmCC";
khtml.maplib.base.helpers.imageNotSelectable=function(a){a.style.MozUserSelect="none";a.style.webkitUserSelect="none";a.style.webkitUserDrag="none";a.style.KhtmlUserSelect="none";a.style.OUserSelect="none";a.style.userSelect="none"};
khtml.maplib.base.helpers.setCursor=function(a,b){if(navigator.userAgent.indexOf("MSIE")!=-1)a.style.cursor=b=="grab"?"url('"+khtml.maplib.standardimagepath+"hand.cur'), default":b=="grabbing"?"url('"+khtml.maplib.standardimagepath+"fist.cur'), move":"pointer";else if(a.style.cursor="-moz-"+b,a.style.cursor!="-moz-"+b&&(a.style.cursor="-webkit-"+b,a.style.cursor!="-webkit-"+b&&(a.style.cursor="-ms-"+b,a.style.cursor!="-ms-"+b&&(a.style.cursor="-khtml-"+b,a.style.cursor!="-khtml-"+b&&(a.style.cursor=
b,a.style.cursor!=b)))))a.style.cursor="pointer"};
khtml.maplib.base.helpers.reduceToJSON=function(a,b){console.log(a);var d=["type","features","coordinates","style","className","baseVal","geometry","fill","stroke","strokeWidth","opacity","fillOpacity","strokeOpacity","dashArray","marker","icon","shadow","url","draggable","size","origin","anchor","width","height","x","y"];if(a instanceof khtml.maplib.geometry.LatLng)return[a.lng(),a.lat()];b||(b=0);if(!(b>15)){var e={};if(typeof a=="string"||typeof a=="number")return a;if(a instanceof Array){d=[];
for(var g=0;g<a.length;g++)d[g]=khtml.maplib.base.helpers.reduceToJSON(a[g],b+1);return d}if(a instanceof CSSStyleDeclaration){d={};for(g=0;g<a.length;g++)d[a[g]]=a[a[g]];return d}for(var h in a){var c=!0;for(g=0;g<d.length;g++)if(d[g]==h){c=!1;break}c||(e[h]=typeof a[h]=="string"?a[h]:khtml.maplib.base.helpers.reduceToJSON(a[h],b+1))}return e}};khtml.maplib.base.Map=function(a){typeof a=="string"&&(a=document.getElementById(a));(typeof a!="object"||null==a)&&console.log("Error: map is null or not an object. (map: "+a+")");this.addOverlay=function(c){if(null==c||c instanceof Array)return console.log('Map.addOverlay(): Illegal argument (was "null" or "Array")'),!1;this.overlays.push(c);typeof c.init=="function"&&c.init(this);this.renderOverlay(c)};this.addOverlays=function(c){if(c instanceof Array)for(var a=0;a<c.length;a++)this.addOverlay(c[a]);
else this.addOverlay(c)};this.renderOverlay=function(c){try{c.render()}catch(a){}};this.renderOverlays=function(){this.overlayDiv.style.display="";for(obj in this.overlays)this.overlays[obj].render()};this._hideOverlays=function(){this.overlayDiv.style.display="none";for(obj in this.overlays)this.overlays[obj].hide&&this.overlays[obj].hide(g)};this.removeOverlays=function(){for(;this.overlays.length>0;)this.overlays.pop().clear()};this.stopRenderOverlays=function(){for(obj in this.overlays)typeof this.overlays[obj].cancel==
"function"&&this.overlays[obj].cancel()};this.removeOverlay=function(c){for(var a=0;a<this.overlays.length;a++)if(c==this.overlays[a]){c.clear();this.overlays.splice(a,1);break}};this.callbackFunctions=[];this.addCallbackFunction=function(c){typeof c=="function"&&this.callbackFunctions.push(c)};this._executeCallbackFunctions=function(){for(var c=0;c<this.callbackFunctions.length;c++)this.callbackFunctions[c].call(this)};this.myTimer=function(c){this.reset=function(){this._isRunning=!1};this.isTimeRunning=
function(){if(!1==this._isRunning)return!1;if(this.time+this.myInterval>(new Date).getTime())return!1;this._isRunning=!1;return!0};this.start=function(){this._isRunning=!0;this.time=(new Date).getTime()};this.interval=function(c){if(typeof c!="undefined")this.myInterval=parseInt(c);return this.myInterval};this.reset();this.interval(c);return this};this.oldMoveY=this.oldMoveX=0;this.moving=!1;this._start=function(c){c.preventDefault?c.preventDefault():c.returnValue=!1;this.moving=this.center();this.downEvent=
c;this.moveAnimationBlocked=!0;if(c.touches.length==1){this.startMoveX=this.moveX-this.pageX(c.touches[0])/this.faktor/this.sc;this.startMoveY=this.moveY-this.pageY(c.touches[0])/this.faktor/this.sc;if(this.mousedownTime!=null&&(new Date).getTime()-this.mousedownTime<this._doubleclickTime){var a=Math.ceil(0.01+this._getZoom()-this.intZoom);this._autoZoomIn(this.pageX(c.touches[0]),this.pageY(c.touches[0]),a)}this.mousedownTime=(new Date).getTime();clearTimeout(this.zoomOutInterval);this.zoomOutInterval=
window.setInterval(function(){},20)}if(c.touches.length==2){window.clearInterval(this.zoomOutInterval);this.moveok=!1;a=this.pageX(c.touches[0]);var f=this.pageY(c.touches[0]),b=this.pageX(c.touches[1]);c=this.pageY(c.touches[1]);this.startDistance=Math.sqrt(Math.pow(b-a,2)+Math.pow(c-f,2));this.startZZ=this.position.zoom;c=(f+c)/2/this.faktor/this.sc;this.startMoveX=this.moveX-(a+b)/2/this.faktor/this.sc;this.startMoveY=this.moveY-c}this.oldMoveX=this.moveX;this.oldMoveY=this.moveY};this.moveok=
!0;this._move=function(c){c.preventDefault?c.preventDefault():c.returnValue=!1;this.moveEvent=c;if(c.touches.length==1&&this.moveok){this.lastMoveX=this.moveX;this.lastMoveY=this.moveY;this.lastMoveTime=new Date(c.timeStamp);this.moveX=this.pageX(c.touches[0])/this.faktor/this.sc+this.startMoveX;this.moveY=this.pageY(c.touches[0])/this.faktor/this.sc+this.startMoveY;if(!this.zoomOutStarted){if(Math.abs(this.moveX-this.oldMoveX)>5||Math.abs(this.moveY-this.oldMoveY)>5)window.clearInterval(this.zoomOutInterval),
this.zoomOutSpeed=0.01,this.mousedownTime=null;var a=new khtml.maplib.LatLng(this.lat,this.lng);this.setCenter2(a,this.position.zoom);this.moveAnimationBlocked=!1}if(Math.abs(this.moveX-this.oldMoveX)>5||Math.abs(this.moveY-this.oldMoveY)>5)this.mousedownTime=null}if(c.touches.length==2){this.mousedownTime=null;var f=this.pageX(c.touches[0]),b=this.pageY(c.touches[0]),e=this.pageX(c.touches[1]),d=this.pageY(c.touches[1]);a=Math.sqrt(Math.pow(e-f,2)+Math.pow(d-b,2))/this.startDistance;c=this.startZZ+
a-1;c>this.tileSource.maxzoom?(c=this.tileSource.maxzoom,a=this.zoomDeltaOld):this.zoomDeltaOld=a;f=(f+e)/2;b=(b+d)/2;faktor=Math.pow(2,c);e=f/faktor-this.width/2;d=b/faktor-this.height/2;a=Math.pow(2,a-1);this.moveX=(f+(e-e*a))/faktor+this.startMoveX;this.moveY=(b+(d-d*a))/faktor+this.startMoveY;a=new khtml.maplib.LatLng(this.lat,this.lng);this.setCenter2(a,c)}};this._end=function(c){c.preventDefault?c.preventDefault():c.returnValue=!1;window.clearInterval(this.zoomOutInterval);this.zoomOutStarted=
!1;this.zoomOutSpeed=0.01;if(c.touches.length==0&&(this.moveok=!0,this.moveAnimationMobile&&this.moveAnimationBlocked==!1)){var a=new Date(c.timeStamp)-this.lastMoveTime,f=(this.lastMoveX-this.moveX)/a*4;a=(this.lastMoveY-this.moveY)/a*4;var b=this.wheelSpeedConfig.animateMaxSpeed;f>b&&(f=b);a>b&&(a=b);f<-b&&(f=-b);a<-b&&(a=-b);b=Math.pow(2,this.zoom());this._animateMove(f,a,b)}if(c.touches.length==1)this.startMoveX=this.moveX-c.touches[0].pageX/this.faktor/this.sc,this.startMoveY=this.moveY-c.touches[0].pageY/
this.faktor/this.sc};this.pageX=function(c){try{return(c.pageX===void 0?c.clientX+document.documentElement.scrollLeft:c.pageX)-this.mapLeft}catch(a){return this.lastMouseX}};this.pageY=function(c){try{if(c.pageY===void 0){var a=c.clientY+document.documentElement.scrollTop;console.log(document.documentElement.scrollTop)}else a=c.pageY;return a-this.mapTop}catch(f){return this.lastMouseY}};this.doubleclickBlocked=!1;this._doubleclick=function(c){var a;if(!c)c=window.event;c.which?a=c.which==3:c.button&&
(a=c.button==2);a?this._discretZoom(-1,this.pageX(c),this.pageY(c)):this._discretZoom(1,this.pageX(c),this.pageY(c))};this._mousedown=function(c){this.mapParent.focus();c.preventDefault?c.preventDefault():window.event.returnValue=!1;this.downEvent=c;this.lastMouseX=this.pageX(c);this.lastMouseY=this.pageY(c);this.moveAnimationBlocked=!0;if(this.mousedownTime2!=null&&(new Date).getTime()-this.mousedownTime2<this._doubleclickTime2)this._doubleclick(c);else{this.mousedownTime2=(new Date).getTime();if(c.shiftKey){this.selectRectLeft=
this.pageX(c);this.selectRectTop=this.pageY(c);this.selectRect=document.createElement("div");this.selectRect.style.left=this.selectRectLeft+"px";this.selectRect.style.top=this.selectRectTop+"px";this.selectRect.style.border="1px solid gray";if(!this.internetExplorer)this.selectRect.style.opacity=0.5,this.selectRect.style.backgroundColor="white";this.selectRect.style.position="absolute";this.map.parentNode.appendChild(this.selectRect);khtml.maplib.base.helpers.setCursor(this.mapParent,"crosshair")}else this.moving=
this.center(),this.startMoveX=this.moveX-this.pageX(c)/this.faktor/this.sc,this.startMoveY=this.moveY-this.pageY(c)/this.faktor/this.sc,this.movestarted=!0,khtml.maplib.base.helpers.setCursor(this.mapParent,"grabbing");return!1}};this._mousemove=function(c){c.preventDefault?c.preventDefault():window.event.returnValue=!1;this.moveEvent=c;this.lastMouseX=this.pageX(c);this.lastMouseY=this.pageY(c);if(c.shiftKey){if(this.selectRect){this.selectRect.style.width=Math.abs(this.pageX(c)-this.selectRectLeft)+
"px";this.selectRect.style.height=Math.abs(this.pageY(c)-this.selectRectTop)+"px";if(this.pageX(c)<this.selectRectLeft)this.selectRect.style.left=this.pageX(c)+"px";if(this.pageY(c)<this.selectRectTop)this.selectRect.style.top=this.pageY(c)+"px"}}else if(this.movestarted)this.lastMoveX=this.moveX,this.lastMoveY=this.moveY,this.lastMoveTime=new Date(c.timeStamp),this.moveX=this.pageX(c)/this.faktor/this.sc+this.startMoveX,this.moveY=this.pageY(c)/this.faktor/this.sc+this.startMoveY,this.setCenter2(new khtml.maplib.LatLng(this.lat,
this.lng),this.position.zoom),this.moveAnimationBlocked=!1;return!1};this._mouseup=function(c){khtml.maplib.base.helpers.setCursor(this.mapParent,"grab");this.lastMouseX=this.pageX(c);this.lastMouseY=this.pageY(c);if(this.moveMarker)this.moveMarker=null;if(this.selectRect){var a=this.XYTolatlng(this.selectRect.offsetLeft,this.selectRect.offsetTop+this.selectRect.offsetHeight),f=this.XYTolatlng(this.selectRect.offsetLeft+this.selectRect.offsetWidth,this.selectRect.offsetTop);this._setBounds(new khtml.maplib.geometry.Bounds(a,
f));this.selectRect.parentNode.removeChild(this.selectRect);this.selectRect=null}a=new Date(c.timeStamp)-this.lastMoveTime;if(this.wheelSpeedConfig.moveAnimateDesktop&&a!=0&&this.movestarted&&this.moveAnimationBlocked==!1)c=(this.lastMoveX-this.moveX)/a,a=(this.lastMoveY-this.moveY)/a,f=this.wheelSpeedConfig.animateMaxSpeed,c>f&&(c=f),a>f&&(a=f),c<-f&&(c=-f),a<-f&&(a=-f),f=Math.pow(2,this.zoom()),this._animateMove(c,a,f);var b=this;setTimeout(function(){b.movestarted=!1},1)};this._mouseupIE=function(c){c.preventDefault?
c.preventDefault():c.returnValue=!1;this.lastMouseX=this.pageX(c);this.lastMouseY=this.pageY(c);this.setCenter2(this.XYTolatlng(this.lastMouseX,this.lastMouseY),this.zoom())};this.startZoomTime=null;this._mousewheel=function(c){c.preventDefault?c.preventDefault():c.returnValue=!1;this.mapParent.focus();if(!c)c=window.event;if(c.wheelDelta)var a=c.wheelDelta/60;else if(c.detail)a=-c.detail/3,this.lastWheelDelta*a<0&&(this.wheelSpeedConfig.digizoom||(a=0)),this.lastWheelDelta=-c.detail/3;a=a<0?-1:1;
if(this.wheelSpeedConfig.digizoom)this._discretZoom(a,this.pageX(c),this.pageY(c));else{if(!this.startZoomTime)this.startZoomTime=new Date,this.startZoomTime2=new Date,this.oldZoom=this.zoom(),this.speed=1;var f=new Date-this.startZoomTime,b=new Date-this.startZoomTime2;this.startZoomTime=new Date;if(f>300)this.startZoomTime2=new Date,this.oldZoom=this.zoom(),this.speed=1,b=0.1;this.speed*=2;if(this.speed>5)this.speed=5;a=this.oldZoom+b/3E3*this.speed*a*(c.shiftKey?0.1:1);if(a>this.position.maxZoom)a=
this.position.maxZoom;if(a<this.position.minZoom)a=this.position.minZoom;this.centerAndZoomXY(this.center(),a,this.pageX(c),this.pageY(c))}};this._shiftkeydown=function(c){c.shiftKey&&khtml.maplib.base.helpers.setCursor(this.mapParent,"crosshair")};this._shiftkeyup=function(){khtml.maplib.base.helpers.setCursor(this.mapParent,"grab")};this.zoomTimeouts=[];this.discretZoomBlocked=!1;this._discretZoom=function(c,a,f){if(!this.discretZoomBlocked){var b=this;this.discretZoomBlockedTimeout=setTimeout(function(){b.discretZoomBlocked=
!1},200);this.discretZoomBlocked=!0;for(var e=1;e<=20;e++)this.zoomTimeouts[e]&&clearTimeout(this.zoomTimeouts[e]);e=this.zoom();var d=c==1?Math.ceil(this.zoom()+0.9):Math.floor(this.zoom()-0.9);d=Math.abs(e-d);var g=0;for(e=1;e<=20;e++){var h=c*Math.sin(e/20*Math.PI/2)*d;this.zoomTimeouts[e]=this._discretZoomExec(a,f,h-g,e,20);g=h}}};this._discretZoomExec=function(c,a,f,b,e){var d=this;return setTimeout(function(){var g=d.zoom()+f;b==e&&(g=Math.round(g));d.centerAndZoomXY(d.center(),g,c,a)},b*20)};
this.digizoomblocked=!1;this.wheelZoomTimeout=this.digizoomblockedTimeout=null;this._animateMove=function(c,a,f){if(!this.internetExplorer){clearTimeout(this.animateMoveTimeout);if(Math.abs(c)<this.wheelSpeedConfig.animateMinSpeed/f&&Math.abs(a)<this.wheelSpeedConfig.animateMinSpeed/f)this.moving=!1;else{this.moveX+=-c;this.moveY+=-a;var b=this,e=Math.sqrt(Math.pow(c,2)+Math.pow(a,2)),d=c/e,g=a/e;this.animateMoveTimeout=window.setTimeout(function(){b._animateMove(c-d*b.wheelSpeedConfig.moveAnimationSlowdown/
f,a-g*b.wheelSpeedConfig.moveAnimationSlowdown/f,f)},20)}this.setCenter2(this.position.center,this.position.zoom)}};this.autoZoomStartTime=this.autoZoomInTimeout=null;this._autoZoomIn=function(c,a,f){this.autoZoomInTimeout&&window.clearTimeout(this.autoZoomInTimeout);var b=0.2;f<0&&(b=-b);zoomGap=!1;Math.abs(f)<=Math.abs(b)&&(zoomGap=!0);var e=this.position.zoom+b;e=Math.round(e*1E3)/1E3;zoomGap&&(e=f<0?Math.floor(e):Math.ceil(e-0.2),b=e-this.position.zoom);faktor=Math.pow(2,e);var d=c-this.mapLeft-
this.width/2,g=a-this.mapTop-this.height/2,h=Math.pow(2,b);d-=d*h;g-=g*h;var x=this;h=(new Date).getMilliseconds();var m=this.autoZoomStartTime?h-this.autoZoomStartTime:0;this.autoZoomStartTime=h;if(m<100||zoomGap){e>=this.tileSource.minzoom&&e<=this.tileSource.maxzoom&&(this.moveX+=d/faktor,this.moveY+=g/faktor);var l=new khtml.maplib.LatLng(this.lat,this.lng);if(e>this.tileSource.maxzoom)e=this.tileSource.maxzoom;if(e<this.tileSource.minzoom)e=this.tileSource.minzoom;setTimeout(function(){x.setCenter2(l,
e)},1)}var p=f-b;zoomGap?this.digizoomblocked=!1:this.autoZoomInTimeout=window.setTimeout(function(){x._autoZoomIn(c,a,p)},40)};this.centerAndZoomXY=function(c,a,b,e){faktor=Math.pow(2,a);c=b-this.size.width/2;e-=this.size.height/2;b=a-this.zoom();b=Math.pow(2,b);c-=c*b;e-=e*b;a>=this.tileSource.minzoom&&a<=this.tileSource.maxzoom&&(this.moveX+=c/faktor,this.moveY+=e/faktor);c=new khtml.maplib.LatLng(this.lat,this.lng);if(a>this.tileSource.maxzoom)a=this.tileSource.maxzoom;if(a<this.tileSource.minzoom)a=
this.tileSource.minzoom;this.setCenter2(c,a)};this.centerAndZoom=function(c,a){this.moveY=this.moveX=0;if(a>this.tileSource.maxzoom)a=this.tileSource.maxzoom;if(a<this.tileSource.minzoom)a=this.tileSource.minzoom;this.record();this.setCenterNoLog(c,a)};this.render=function(){this.center(this.center())};this._setCenter3=function(c,a){this.moveY=this.moveX=0;this.setCenterNoLog(c,a)};this.setCenter2=function(c,a){this.record();this.setCenterNoLog(c,a)};this.setCenterNoLog=function(c,a){this.position.center=
c;this.lat=c.lat();this.lng=c.lng();a=parseFloat(a);if(a>this.tileSource.maxzoom)a=this.tileSource.maxzoom;if(a<this.tileSource.minzoom)a=this.tileSource.minzoom;this.position.center=c;this.position.zoom=a;this.layer(this.map,this.lat,this.lng,this.moveX,this.moveY,a);this._executeCallbackFunctions();this._getBounds()};this.center=function(c){typeof c!="undefined"&&this.centerAndZoom(c,this._getZoom());if(this.moveX!=0||this.moveY!=0)return c=new khtml.maplib.LatLng(this.movedLat,this.movedLng);return this.position.center};
this.zoom=function(c){typeof c!="undefined"&&this.centerAndZoom(this.position.center,c);return this.position.zoom};this.moveXY=function(c,a){this.moveX=parseFloat(c)/this.faktor/this.sc+this.moveDelayedX;this.moveY=parseFloat(a)/this.faktor/this.sc+this.moveDelayedY;this.setCenter2(this.center(),this.zoom())};this.tiles=function(c){this.clearMap();this.tileSource=c};this.tileOverlays=[];this.addTilesOverlay=function(c){this.tileOverlays.push(c);c=this.tileOverlays[this.tileOverlays.length-1];this.clearMap();
return c};this.removeTilesOverlay=function(c){for(var a=0;a<this.tileOverlays.length;a++)if(c==this.tileOverlays[a]){this.tileOverlays.splice(a,1);break}this.clearMap()};this._getCenter=function(){if(this.moveX&&this.moveX!=0||this.moveY&&this.moveY!=0)var c=new khtml.maplib.LatLng(this.movedLat,this.movedLng);else if(this.position.center)c=this.position.center;return c};this.bounds=function(c){if(typeof c!="undefined")this._setBounds(c);else return this.mapBounds};this.mapBounds=null;this._getBounds=
function(){var c=this.XYTolatlng(0,this.height),a=this.XYTolatlng(this.width,0);this.mapBounds=new khtml.maplib.geometry.Bounds(c,a)};this._setBounds=function(c){if(typeof khtml.maplib.geometry.Bounds=="undefined"||!(c instanceof khtml.maplib.geometry.Bounds))return!1;var a=c.sw();c=c.ne();var b=a.lat(),g=c.lat();a=a.lng();c=c.lng();b=d(b);var h=d(g);g=(a+c)/2;var i=e((b+h)/2);g=new khtml.maplib.LatLng(i,g);b=Math.abs(h-b);a=Math.abs(c-a);a/this.width>b/this.height?c=this.width:(a=b,c=this.height);
a=Math.log(360/a/(512/c))/Math.log(2)+1;if(a>this.tileSource.maxzoom)a=this.tileSource.maxzoom;if(a<this.tileSource.minzoom)a=this.tileSource.minzoom;this.position.center?this.wheelSpeedConfig.rectShiftAnimate?this.animatedGoto(g,a,this.wheelSpeedConfig.rectShiftAnimationTime):this.centerAndZoom(g,a):this.centerAndZoom(g,a)};this.animatedGotoStep=null;this.animatedGotoTimeout=[];this.animatedGoto=function(c,a,b){b/=10;var e=this._getCenter(),d=c.lat();c=c.lng();var g=e.lat(),h=e.lng(),o=this._getZoom(),
x=(d-g)/b,m=(c-h)/b,l=(a-o)/b,p=this.moveX/b,B=this.moveY/b,C=this.moveX,q=this.moveY;this.animatedGotoStep=0;for(var s=this;timeout=this.animatedGotoTimeout.pop();)clearTimeout(timeout);for(a=0;a<=b;a++)this.animatedGotoTimeout[a]=window.setTimeout(function(){s._animatedGotoExec(g,h,o,x,m,l,C,q,p,B)},10*a)};this._animatedGotoExec=function(a,b,e,d,g,i,h,o,x,m){this.moveX=-x;this.moveY=-m;a+=d*this.animatedGotoStep;b+=g*this.animatedGotoStep;e+=i*this.animatedGotoStep;this.animatedGotoStep++;this.centerAndZoom(new khtml.maplib.LatLng(a,
b),e)};this._getZoom=function(){return this.position.zoom};this._getIntZoom=function(){return this.intZoom};this.latlngToXY=function(a){var e=a.lat();a=a.lng();e>90&&(e-=180);e<-90&&(e+=180);var f=this._getIntZoom();a=b(e,a,f);e=this._getCenter();e=b(e.lat(),e.lng(),f);f=(e[0]-a[0])*this.tileW*this.sc-this.width/2;e=(e[1]-a[1])*this.tileW*this.sc-this.height/2;a=[];a.x=-f;a.y=-e;return a};this.XYTolatlng=function(a,d){var f=this._getCenter();if(f){var g=Math.pow(2,this.intZoom),h=f.lat();f=f.lng();
f=b(h,f,this.intZoom);h=(f[0]+(a-this.width/2)/this.tileW/this.sc)/g*360-180;g=-e((f[1]+(d-this.height/2)/this.tileH/this.sc)/g*360-180)+0;return new khtml.maplib.LatLng(g,h)}};this.mouseToLatLng=function(a){var b=this.pageX(a);a=this.pageY(a);return this.XYTolatlng(b,a)};this.reSize=function(){var a=this;window.setTimeout(function(){a._getSize(a)},1050)};this._getSize=function(){this.width=this.map.parentNode.offsetWidth;this.height=this.map.parentNode.offsetHeight;var a=this.map,b=0,e=0;do b+=a.offsetLeft,
e+=a.offsetTop,a=a.offsetParent;while(a.offsetParent);this.mapTop=e;this.mapLeft=b};this.recordArray=[];this.record=function(){var a=this._getCenter();if(a){var b=a.lat();a=a.lng();var e=this._getZoom();this.recordArray.push([b,a,e])}};this.play=function(a){if(!(a<1)&&!(a>this.recordArray.length-1)){a=this.recordArray[a];var b=new khtml.maplib.LatLng(a[0],a[1]);this.moveY=this.moveX=0;this._setCenter3(b,a[2])}};this.layerDrawLastFrame=null;this.doTheOverlays=!0;this.finalDraw=!1;this.moveDelayedY=
this.moveDelayedX=this.layerOldZoom=0;this.layerTimer=new this.myTimer(300);this.layer=function(a,b,e,d,g,h){this.stopRenderOverlays();h||(h=this._getZoom());var j=this.wheelSpeedConfig.digizoom?Math.floor(h):Math.round(h);this.layerDrawLastFrame&&window.clearTimeout(this.layerDrawLastFrame);if(this.layerTimer.isTimeRunning()||this.finalDraw==!1){var o=this;j=function(){o.finalDraw=!0;o.layer(a,b,e,d,g,h)};this.visibleZoom=parseInt(this.visibleZoom);this.visibleZoom=parseInt(this.visibleZoom);if(!o.finalDraw)this.layerDrawLastFrame=
window.setTimeout(j,100);if(this.layerTimer.isTimeRunning()){this.moveDelayedX=d;this.moveDelayedY=g;return}}this.layerTimer.start();for(j=this.moveDelayedY=this.moveDelayedX=0;j<22;j++)if(this.layers[j])this.layers[j].layerDiv.style.visibility="hidden";j=this.wheelSpeedConfig.digizoom?Math.floor(h):Math.round(h);if(this.layerOldZoom>h&&!this.finalDraw&&this.layers[j]&&!this.layers[j].loadComplete)this.visibleZoom=j+1;this.intZoom=j;if(j>this.tileSource.maxzoom)j=this.tileSource.maxzoom;if(!this.visibleZoom)this.oldIntZoom=
this.visibleZoom=j;this.faktor=Math.pow(2,j);this.sc=Math.pow(2,h-j);this.loadingZoomLevel=j;if(this.visibleZoom<j&&Math.abs(this.visibleZoom-j)<40)this.loadingZoomLevel=parseInt(this.visibleZoom)+1;this.draw(this.map,b,e,d,g,this.loadingZoomLevel,h,this.tileSource.src);this.layers[this.loadingZoomLevel].layerDiv.style.visibility="";if(j!=this.visibleZoom)this.visibleZoom<j+2?(this.draw(this.map,b,e,d,g,this.visibleZoom,h,this.tileSource.src),this.layers[this.visibleZoom].layerDiv.style.visibility=
""):this.layers[this.visibleZoom].layerDiv.style.visibility="hidden";if(j==this.visibleZoom)this.draw(this.map,b,e,d,g,this.visibleZoom-1,h,this.tileSource.src),this.layers[this.visibleZoom-1].layerDiv.style.visibility="hidden";if(this.layers[this.loadingZoomLevel].loadComplete&&this.visibleLayer!=j)this.layers[this.loadingZoomLevel].loadComplete=!1,this._hideLayer(this.visibleZoom),this.visibleZoom=this.loadingZoomLevel;this.quadtreeTimeout&&clearTimeout(this.quadtreeTimeout);if(this.loadingZoomLevel!=
j)o=this,this.quadtreeTimeout=window.setTimeout(function(){o.layer(a,b,e,d,g)},200);this.oldIntZoom!=this.intZoom&&this.oldIntZoom!=this.visibleZoom&&this._hideLayer(this.oldIntZoom);this.oldIntZoom=j;this.delayedOverlay&&window.clearTimeout(this.delayedOverlay);this.doTheOverlays||this.finalDraw||this.layerOldZoom==this.zoom()?(j=new Date,this.lastDX=this.moveX,this.lastDY=this.moveY,this.renderOverlays(),this.layerOldZoom=this.zoom(),this.doTheOverlays=new Date-j>10&&!this.finalDraw?!1:!0):this._hideOverlays();
o=this;this.layerBlockTimeout&&clearTimeout(this.layerBlockTimeout);this.layerBlockTimeout=window.setTimeout(function(){o.layerTimer.reset()},20);this.finalDraw=!1};this.draw=function(a,g,f,h,D,i,j,o){this.framesCounter++;var x=this;window.setTimeout(function(){x.framesCounter--},1E3);var m=Math.pow(2,i);if(this.layers[i])l=this.layers[i].layerDiv,p=d(g)-this.layers[i].startLat,f-=this.layers[i].startLng;else{p=b(g,f,i);this.layers[i]=[];this.layers[i].startTileX=p[0];this.layers[i].startTileY=p[1];
this.layers[i].startLat=d(g);this.layers[i].startLng=f;this.layers[i].images={};var l=document.createElement("div");l.setAttribute("zoomlevel",i);l.style.position="absolute";p=a.childNodes;a=!1;for(f=p.length-1;f>=0;f--)g=p.item(f),g.getAttribute("zoomlevel")<i&&(this.map.insertBefore(l,g),a=!0);a||this.map.appendChild(l);this.layers[i].layerDiv=l;var p=0;f=0}l.style.visibility="hidden";l.style.opacity=1;l.style.filter="alpha(opacity=100)";this.movedLng=(this.layers[i].startTileX/m-h/this.tileW)*
360-180+f;this.movedLat=-e((this.layers[i].startTileY/m-D/this.tileH)*360-180-p);p=b(this.movedLat,this.movedLng,i);h=p[0];f=p[1];D=Math.floor(h);a=Math.floor(f);g=this.layers[i].startTileX;var B=this.layers[i].startTileY;h=h-g-(-g+Math.floor(g));var C=f-B-(-B+Math.floor(B)),q;for(q in this.layers[i].images)this.layers[i].images[q].visibility=!1;f=this.width;var s=this.height;u=Math.pow(2,j-i);minX=Math.floor(-f/2/u/this.tileW+h);maxX=Math.ceil(f/2/u/this.tileW+h);minY=Math.floor(-s/2/u/this.tileH+
C);maxY=Math.ceil(s/2/u/this.tileH+C);for(f=minX;f<maxX;f++)for(s=minY;s<maxY;s++){var r=Math.floor(g+f),k=Math.floor(B+s),v=r%m,t=k;v<0&&(v+=m);if(!(t<0)&&!(t>=m)){var y=o(v,t,i);r=y+"-"+r+"-"+k;minsc=this.wheelSpeedConfig.digizoom?1:0.5;if(this.layers[i].images[r]==null&&u>=minsc){k=document.createElement("img");k.style.visibility="hidden";k.style.position="absolute";k.style.padding="0px";k.style.margin="0px";k.style.borderWidth="0px";k.style.left=f*this.tileW+"px";k.style.top=s*this.tileH+"px";
k.style.width=this.tileW+"px";k.style.height=this.tileH+"px";if(this.tileSource.opacity)k.style.opacity=this.tileSource.opacity;l.childNodes.length>0?l.insertBefore(k,l.childNodes.item(0)):l.appendChild(k);this.layers[i].images[r]={};this.layers[i].images[r].img=k;this.layers[i].images[r].array=[];this.layers[i].images[r].array.push(k);this.layers[i].loadComplete=!1;for(ov in this.tileOverlays){var z=this.tileOverlays[ov],w=k.cloneNode(!0);z=z.src(v,t,i);w.setAttribute("overlay",ov);khtml.maplib.base.helpers.eventAttach(w,
"load",this._imgLoaded,this,!1);l.appendChild(w);w.setAttribute("src",z);this.layers[i].images[r].array.push(w)}khtml.maplib.base.helpers.eventAttach(k,"load",this._imgLoaded,this,!1);khtml.maplib.base.helpers.eventAttach(k,"error",this._imgError,this,!1);k.setAttribute("src",y)}if(!this.css3d&&this.layers[i].images[r]){v=this.layers[i].images[r].array;for(t=0;t<v.length;t++){var E=p[0]-D+Math.floor(h);w=p[1]-a+Math.floor(C);var F=Math.round(this.tileW*u);z=Math.round(this.tileH*u);y=Math.floor(-E*
F+f*F);k=Math.floor(-w*z+s*z);E=Math.floor(-E*F+(f+1)*F);w=Math.floor(-w*z+(s+1)*z);v[t].style.left=y+"px";v[t].style.top=k+"px";v[t].style.height=E-y+"px";v[t].style.width=w-k+"px"}}this.layers[i].images[r]&&(this.layers[i].images[r].visibility=!0)}}for(q in this.layers[i].images)if(this.layers[i].images[q].visibility){if(this.layers[i].images[q].array[0].getAttribute("loaded")=="yes"){o=this.layers[i].images[q].array;for(m=0;m<o.length;m++)if(o[m].getAttribute("loaded")=="yes")o[m].style.visibility=
""}}else{o=this.layers[i].images[q].array;for(m=0;m<o.length;m++)this.layers[i].images[q].array[m].style.visibility="hidden",this.layers[i].images[q].array[m].getAttribute("loaded")!="yes"&&l.removeChild(this.layers[i].images[q].array[m]);delete this.layers[i].images[q].img;delete this.layers[i].images[q]}var u=Math.pow(2,j-i);y=-h*this.tileW;k=-C*this.tileH;if(this.css3d)l.style["-webkit-transform-origin"]=-1*y+"px "+-1*k+"px",l.style.webkitTransform="translate3d("+y+"px,"+k+"px,0px)  "+(" scale3d("+
u+","+u+",1) ");l.style.visibility="";l.style.opacity=1;l.style.filter="";l=j=0;for(q in this.layers[this.loadingZoomLevel].images)l++,k=this.layers[this.loadingZoomLevel].images[q].array[0],k.getAttribute("loaded")!="yes"&&j++;this.notLoadedImages=j;j<1&&(this.layers[this.loadingZoomLevel].loadComplete=!0);this.loadingZoomLevel==i&&this._imgLoadInfo(l,j)};this.fadeOutTimeout=null;this._fadeOut=function(a,b){this.fadeOutTimeout&&clearTimeout(this.fadeOutTimeout);if(b>0){a.style.opacity=b;a.style.filter=
"alpha( opacity="+b*100+" )";var e=this;this.fadeOutTimeout=setTimeout(function(){e._fadeOut(a,b-0.2)},40)}else a.style.visibility="hidden"};this._hideLayer=function(a){if(this.intZoom!=a&&this.layers[a])this.layers[a].layerDiv.style.opacity=1,this.layers[a].layerDiv.style.filter="alpha(opacity=100)",this._fadeOut(this.layers[a].layerDiv,1);if(this.layers[a])for(var b in this.layers[a].images)if(this.layers[a].images[b]&&this.layers[a].images[b].img&&this.layers[a].images[b].img.getAttribute("loaded")!=
"yes"&&a!=this.intZoom){for(var e=this.layers[a].images[b].array,d=0;d<e.length;d++)this.layers[a].layerDiv.removeChild(this.layers[a].images[b].array[d]);delete this.layers[a].images[b].img;delete this.layers[a].images[b]}};this._imgLoaded=function(a){a=a.target?a.target:a.srcElement;var b=!0;a.style.visibility="";a.setAttribute("loaded","yes");if(a.parentNode){for(var e=0,d=0,g=a.parentNode.getAttribute("zoomlevel"),h=0;h<a.parentNode.getElementsByTagName("img").length;h++){var j=a.parentNode.getElementsByTagName("img").item(h);
j.getAttribute("overlay")||(d++,j.getAttribute("loaded")!="yes"&&(e++,b=!1))}this.notLoadedImages=e;this.loadingZoomLevel==g&&this._imgLoadInfo(d,e);if((this.layers[g].loadComplete=b)&&this.loadingZoomLevel==g)this._hideLayer(this.visibleZoom),this._hideLayer(this.visibleZoom+1),this.visibleZoom=g}};this._imgError=function(a){var b=a.target?a.target:a.srcElement;b.parentNode&&(b.src!="http://khtml.org/notfound.png"&&b.setAttribute("src","http://khtml.org/notfound.png"),this._imgLoaded(a))};var b=
function(a,b,e){return[(b+180)/360*(1<<e),(1-Math.log(Math.tan(a*Math.PI/180)+1/Math.cos(a*Math.PI/180))/Math.PI)/2*(1<<e)]};this._calculateMapSize=function(){var a=this.mapParent.getBoundingClientRect();return{top:a.top-document.body.scrollTop,left:a.left-document.body.scrollLeft,width:a.width?a.width:a.right-a.left,height:a.height?a.height:a.bottom-a.top,deltaTop:a.top-document.body.scrollTop,deltaLeft:a.left-document.body.scrollLeft,deltaBottom:a.bottom,deltaRight:a.right}};this.redraw=function(){this._setMapPosition()};
this._setMapPosition=function(){this.size=this._calculateMapSize();var a=this.mapParent;a.currentStyle||window.getComputedStyle&&document.defaultView.getComputedStyle(a,null);this.mapTop=this.size.top;this.mapLeft=this.size.left;this.width=this.size.width;this.height=this.size.height;relativetop=this.size.deltaTop;relativeleft=this.size.deltaLeft;this.clone.style.top="0px";this.clone.style.left="0px";this.clone.style.width="100%";this.clone.style.height="100%";this.clone.style.position="relative";
this.clone.style.overflow="hidden";this.map.style.left="50%";this.map.style.top="50%";this._getCenter()&&this._getZoom()&&this.centerAndZoom(this._getCenter(),this._getZoom());this._copyright()};this.clearMap=function(){if(this.map){for(;this.map.firstChild;)this.map.removeChild(this.map.firstChild);for(;this.layers.length>0;)this.layers.pop();this.redraw()}};var d=function(a){return 180/Math.PI*Math.log(Math.tan(Math.PI/4+a*(Math.PI/180)/2))},e=function(a){return 180/Math.PI*(2*Math.atan(Math.exp(a*
Math.PI/180))-Math.PI/2)};this._imgLoadInfo=function(a,b){if(!this.loadInfoDiv)this.loadInfoDiv=document.createElement("div"),this.loadInfoDiv.style.position="absolute",this.loadInfoDiv.style.top="0px",this.loadInfoDiv.style.right="0px",this.loadInfoDiv.style.backgroundColor="white",this.loadInfoDiv.style.border="1px solid gray",this.loadInfoDiv.style.fontSize="10px",this.map.parentNode.appendChild(this.loadInfoDiv);if(b==0)this.loadInfoDiv.style.display="none";else{for(this.loadInfoDiv.style.display=
"";this.loadInfoDiv.firstChild;)this.loadInfoDiv.removeChild(this.loadInfoDiv.firstChild);this.loadInfoDiv.appendChild(document.createTextNode(b+" images to load"))}};this.copyrightdiv=null;this._copyright=function(){if(this.copyrightdiv==null)this.copyrightdiv=document.createElement("div"),this.overlayDiv.appendChild(this.copyrightdiv);for(;this.copyrightdiv.firstChild;)this.copyrightdiv.removeChild(this.copyrightdiv.firstChild);var a=document.createElement("img"),b=document.createElement("a");b.setAttribute("href",
"http://maplib.khtml.org");b.setAttribute("target","_blank");a.setAttribute("src","http://maplib.khtml.org/favicon.png");a.style.border="0px solid black";a.style.position="absolute";a.style.backgroundColor="transparent";a.style.margin="0px";a.style.padding="0px";var e=this.size.height-26;a.style.top=e+"px";a.style.left="3px";a.style.width="24px";a.style.height="24px";b.appendChild(a);this.copyrightdiv.appendChild(b);a=document.createElement("a");a.appendChild(document.createTextNode("openstreetmap"));
a.style.position="absolute";a.style.top=e+2+"px";a.style.left="28px";a.style.textDecoration="none";a.style.color="gray";a.setAttribute("href","http://www.openstreetmap.org/copyright");this.copyrightdiv.appendChild(a)};this.internetExplorer=!1;if(navigator.userAgent.indexOf("MSIE")!=-1)this.internetExplorer=!0;if(navigator.userAgent.indexOf("Android")!=-1){var g=this;setInterval(function(){g.layerTimer.reset()},300)}this.position={};this.tiles({maxzoom:18,minzoom:1,src:function(a,b,e){switch((a+b)%
3){case 0:var d="a";break;case 1:d="b";break;case 2:d="c";break;default:d="f"}return"http://"+d+".tile.openstreetmap.org/"+e+"/"+a+"/"+b+".png"},copyright:"osm"});this.wheelSpeedConfig=[];this.wheelSpeedConfig.acceleration=2;this.wheelSpeedConfig.maxSpeed=2;this.wheelSpeedConfig.animate=!1;navigator.userAgent.indexOf("AppleWebKit")!=-1&&(this.wheelSpeedConfig.animate=!0);navigator.userAgent.indexOf("Opera")!=-1&&(this.wheelSpeedConfig.animate=!1);this.wheelSpeedConfig.animate=!1;this.wheelSpeedConfig.digizoom=
!0;this.wheelSpeedConfig.zoomAnimationSlowdown=0.02;this.wheelSpeedConfig.animationFPS=50;this.wheelSpeedConfig.moveAnimateDesktop=!0;this.wheelSpeedConfig.rectShiftAnimate=!1;this.wheelSpeedConfig.rectShiftAnimationTime=500;this.wheelSpeedConfig.animateMinSpeed=0.4;this.wheelSpeedConfig.animateMaxSpeed=200;this.wheelSpeedConfig.moveAnimationSlowdown=0.4;this.framesCounter=this.wheelEventCounter=0;this.mapParent=a;khtml.maplib.base.helpers.setCursor(this.mapParent,"grab");this.clone=a.cloneNode(!0);
this.clone=document.createElement("div");this.clone.removeAttribute("id");a.firstChild?a.insertBefore(this.clone,a.firstChild):a.appendChild(this.clone);this.map=document.createElement("div");this.map.style.position="relative";this.clone.appendChild(this.map);this.overlayDiv=document.createElement("div");this.overlayDiv.style.position="absolute";this.clone.appendChild(this.overlayDiv);this._setMapPosition();this.overlays=[];if(khtml.maplib.overlay.GeoJson){var h=new khtml.maplib.overlay.GeoJson;this.addOverlay(h);
this.featureCollection=h.featureCollection}this.distanceMeasuring="no";this.measureLine=this.moveMarker=null;this.moveAnimationMobile=!0;this.moveAnimationBlocked=this.moveAnimationDesktop=!1;this.lastMouseX=this.width/2;this.lastMouseY=this.height/2;this.layers=[];this.intZoom=this.oldVisibleZoom=this.visibleZoom=null;this.lastMoveTime=this.lastMoveY=this.lastMoveX=this.moveY=this.moveX=0;this.zoomDeltaOld=1;this.startMoveY=this.startMoveX=0;this.sc=1;this.blocked=!1;this.tileH=this.tileW=256;this.position.zoom=
1;this.movestarted=!1;this.mousedownTime=null;this._doubleclickTime=400;this.mousedownTime2=null;this._doubleclickTime2=500;this.zoomOutTime=1E3;this.zoomOutSpeed=0.01;this.zoomOutInterval=null;this.zoomOutStarted=!1;this.zoomSpeedTimer=null;this.zoomAcceleration=1;this.css3d=!1;if(navigator.userAgent.indexOf("iPhone OS")!=-1)this.css3d=!0;if(navigator.userAgent.indexOf("iPad")!=-1)this.css3d=!1;if(navigator.userAgent.indexOf("Safari")!=-1)this.css3d=navigator.userAgent.indexOf("Mac")!=-1?!1:!0;if(navigator.userAgent.indexOf("iPhone OS")!=
-1)this.css3d=!0;if(navigator.userAgent.indexOf("Android")!=-1)this.css3d=!1;this.internetExplorer?(h=a,navigator.userAgent.indexOf("Windows Phone OS")!=-1&&khtml.maplib.base.helpers.eventAttach(h,"mouseup",this._mouseupIE,this,!1)):h=window;khtml.maplib.base.helpers.eventAttach(window,"resize",this._setMapPosition,this,!1);navigator.userAgent.indexOf("Konqueror")!=-1&&(h=a);khtml.maplib.base.helpers.eventAttach(a,"touchstart",this._start,this,!1);khtml.maplib.base.helpers.eventAttach(a,"touchmove",
this._move,this,!1);khtml.maplib.base.helpers.eventAttach(a,"touchend",this._end,this,!1);khtml.maplib.base.helpers.eventAttach(h,"mousemove",this._mousemove,this,!1);khtml.maplib.base.helpers.eventAttach(a,"mousedown",this._mousedown,this,!1);khtml.maplib.base.helpers.eventAttach(h,"mouseup",this._mouseup,this,!0);khtml.maplib.base.helpers.eventAttach(h,"orientationchange",this.reSize,this,!1);khtml.maplib.base.helpers.eventAttach(a,"DOMMouseScroll",this._mousewheel,this,!1);khtml.maplib.base.helpers.eventAttach(a,
"dblclick",this._doubleclick,this,!1);khtml.maplib.base.helpers.eventAttach(h,"keydown",this._shiftkeydown,this,!1);khtml.maplib.base.helpers.eventAttach(h,"keyup",this._shiftkeyup,this,!1);khtml.maplib.base.helpers.eventAttach(a,"contextmenu",function(a){a.preventDefault()},this,!1)};khtml.maplib.geometry.Bounds=function(a,b){this.enlarge=function(a){a.lng()>this.southwest.lng()&&a.lng()>this.northeast.lng()&&this.northeast.lng(a.lng());a.lng()<this.southwest.lng()&&a.lng()<this.northeast.lng()&&this.southwest.lng(a.lng());a.lat()>this.southwest.lat()&&a.lat()>this.northeast.lat()&&this.northeast.lat(a.lat());a.lat()<this.southwest.lat()&&a.lat()<this.northeast.lat()&&this.southwest.lat(a.lat())};this.sw=function(a){if(a)this.southwest=a;return this.southwest};this.se=function(){return new khtml.maplib.LatLng(this.southwest.lat(),
this.northeast.lng())};this.ne=function(a){if(a)this.northeast=a;return this.northeast};this.nw=function(){return new khtml.maplib.LatLng(this.northeast.lat(),this.southwest.lng())};this.getCenter=function(){return this.center};this.getOpticalCenter=function(a){var b=a.latlngToXY(this.southwest),d=a.latlngToXY(this.northeast);return a.XYTolatlng(Math.abs(b.x+d.x)/2,Math.abs(b.y+d.y)/2)};this.getZoomLevel=function(a){origZoom=a.getZoom();var b=a.latlngToXY(this.southwest),d=a.latlngToXY(this.northeast),
c=a.width/Math.abs(b.x-d.x);a=a.height/Math.abs(b.y-d.y);if(c>a)var n=a;c<=a&&(n=c);return origZoom+Math.log(n)/Math.log(2)};this.getDistance=function(){return this.distance(this.southwest.lat(),this.southwest.lng(),this.northeast.lat(),this.northeast.lng())};this.getInnerRadius=function(){var a=this.distance(this.center.lat(),this.southwest.lng(),this.center.lat(),this.northeast.lng()),b=this.distance(this.southwest.lat(),this.center.lng(),this.northeast.lat(),this.center.lng());return a>b?b/2:a/
2};this.distance=function(a,b,d,c){a=a*Math.PI/180;d=d*Math.PI/180;return Math.acos(Math.sin(a)*Math.sin(d)+Math.cos(a)*Math.cos(d)*Math.cos(c*Math.PI/180-b*Math.PI/180))*180/Math.PI/360*4E7};this.intersects=function(a){if(!(a instanceof khtml.maplib.geometry.Bounds))return khtml.maplib.base.Log.warn('Bounds.intersects(): Illegal argument. Has to be "khtml.maplib.geometry.Bounds"!'),!1;var b=Math.min(this.sw().lat(),this.ne().lat()),d=Math.max(this.sw().lat(),this.ne().lat()),c=Math.min(this.sw().lng(),
this.ne().lng()),n=Math.max(this.sw().lng(),this.ne().lng()),f=[];f.push(a.ne());f.push(a.se());f.push(a.sw());f.push(a.nw());for(a=0;a<f.length;a++){var A=f[a],D=A.lat()>=b&&A.lat()<=d;A=A.lng()>=c&&A.lng()<=n;if(D&&A)return!0}return!1};this.createBoundsFrom2Points=function(a,b){var d=new khtml.maplib.LatLng(Math.min(a.lat(),b.lat()),Math.min(a.lng(),b.lng())),c=new khtml.maplib.LatLng(Math.max(a.lat(),b.lat()),Math.max(a.lng(),b.lng()));return{sw:d,ne:c}};var d=this.createBoundsFrom2Points(a,b);
this.southwest=d.sw;this.northeast=d.ne;this.center=new khtml.maplib.LatLng((this.southwest.lat()+this.northeast.lat())/2,(this.southwest.lng()+this.northeast.lng())/2)};khtml.maplib.geometry.LatLng=function(a,b){this.callbackFunctions=[];this.addCallbackFunction=function(a){typeof a=="function"&&this.callbackFunctions.push(a)};this.removeCallbackFunction=function(a){for(var b=0;b<this.callbackFunctions.length;b++)this.callbackFunctions[b]==a&&this.callbackFunctions.splice(b,1)};this._executeCallbackFunctions=function(){for(var a=0;a<this.callbackFunctions.length;a++)this.callbackFunctions[a].call(this)};this.lat=function(a){if(typeof a=="number")this.latitude=a,
this._executeCallbackFunctions();else if(typeof a=="string")this.latitude=parseFloat(a),this._executeCallbackFunctions();return this.latitude};this.lng=function(a){if(typeof a=="number")this.longitude=a,this._executeCallbackFunctions();else if(typeof a=="string")this.longitude=parseFloat(a),this._executeCallbackFunctions();return this.longitude};this.equals=function(a){if(null==a)return!1;if(!(a instanceof khtml.maplib.LatLng))return khtml.maplib.base.Log.warn("Point.equals(): Error - illegal argument!",
a),!1;return a.lat()===this.lat()&&a.lng()===this.lng()};a instanceof khtml.maplib.geometry.LatLng?(this.lat(a.lat()),this.lng(a.lng())):typeof a=="object"?(a.lat&&this.lat(a.lat),a.lng&&this.lng(a.lng)):(this.lat(a),this.lng(b))};khtml.maplib.ui.KeyBoard=function(){this.zoomtime=400;this.init=function(a){this.map=a;khtml.maplib.base.helpers.eventAttach(a.mapParent,"keydown",this.keydown,this,!1)};this.keydown=function(a){switch(a.keyCode){case 37:this.moveit(30,0);break;case 38:this.moveit(0,30);break;case 39:this.moveit(-30,0);break;case 40:this.moveit(0,-30);break;case 35:this.moveit(this.map.size.width*0.4,0);break;case 36:this.moveit(-this.map.size.width*0.4,0);break;case 33:this.moveit(0,this.map.size.height*0.4);break;
case 34:this.moveit(0,-this.map.size.height*0.4);break;case 187:case 61:case 43:this.zoomin();break;case 189:case 190:case 109:case 45:this.zoomout();break;default:return}a.preventDefault?a.preventDefault():a.returnValue=!1};this.render=function(){};this.zoomingIn=!1;this.zoomin=function(){var a=Math.ceil(this.map.zoom()+0.1);this.zoomingIn&&a++;this.map.animatedGoto(this.map.center(),a,this.zoomtime);var b=this;setTimeout(function(){b.zoomingIn=!1},this.zoomtime);this.zoomingIn=!0};this.zoomout=
function(){var a=Math.floor(this.map.zoom()-0.1);this.zoomingOut&&a--;this.map.animatedGoto(this.map.center(),a,this.zoomtime);var b=this;setTimeout(function(){b.zoomingOut=!1},this.zoomtime);this.zoomingOut=!0};this.keyup=function(){};this.moveit=function(a,b){for(var d=a/20,e=b/20,g=0;g<20;g++){var h=Math.cos(3*(-10+g)/20)*5;this.moveitexec(d*h,e*h,g)}};this.moveitexec=function(a,b,d){setTimeout(function(){this.map.moveXY(a,b)},20*d)}};
